// SPDX-License-Identifier: Apache-2.0

/// leyline.v1 — bulk plane
/// Sample-bearing streams. Offer/answer negotiation; the answer is authoritative.
/// Payloads are opaque bytes in the negotiated format — samples are never protobuf-encoded per element.
/// No lossless network stream exists: lossless work is a daemon-side FileSink.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/bulk.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - leyline.v1.Bulk

/// Namespace containing generated types for the "leyline.v1.Bulk" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Leyline_V1_Bulk: Sendable {
    /// Service descriptor for the "leyline.v1.Bulk" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Bulk")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Subscribe" metadata.
        public enum Subscribe: Sendable {
            /// Request type for "Subscribe".
            public typealias Input = Leyline_V1_SubscribeRequest
            /// Response type for "Subscribe".
            public typealias Output = Leyline_V1_StreamDescriptor
            /// Descriptor for "Subscribe".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Bulk"),
                method: "Subscribe",
                type: .unary
            )
        }
        /// Namespace for "Stream" metadata.
        public enum Stream: Sendable {
            /// Request type for "Stream".
            public typealias Input = Leyline_V1_StreamRef
            /// Response type for "Stream".
            public typealias Output = Leyline_V1_Frame
            /// Descriptor for "Stream".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Bulk"),
                method: "Stream",
                type: .serverStreaming
            )
        }
        /// Namespace for "Unsubscribe" metadata.
        public enum Unsubscribe: Sendable {
            /// Request type for "Unsubscribe".
            public typealias Input = Leyline_V1_StreamRef
            /// Response type for "Unsubscribe".
            public typealias Output = Leyline_V1_Empty
            /// Descriptor for "Unsubscribe".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Bulk"),
                method: "Unsubscribe",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "leyline.v1.Bulk" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Subscribe.descriptor,
            Stream.descriptor,
            Unsubscribe.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "leyline.v1.Bulk" service.
    public static let leyline_v1_Bulk = GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Bulk")
}

// MARK: leyline.v1.Bulk (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk {
    /// Streaming variant of the service protocol for the "leyline.v1.Bulk" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where the RPC expects only a single
    /// request or response message, you are responsible for ensuring your implementation
    /// maintains this invariant.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_SubscribeRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_StreamDescriptor` messages.
        func subscribe(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_SubscribeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_StreamDescriptor>

        /// Handle the "Stream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GRPC transport only
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_StreamRef` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_Frame` messages.
        func stream(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_StreamRef>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Frame>

        /// Handle the "Unsubscribe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_StreamRef` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_Empty` messages.
        func unsubscribe(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_StreamRef>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Empty>
    }

    /// Service protocol for the "leyline.v1.Bulk" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Leyline_V1_Bulk.StreamingServiceProtocol {
        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_SubscribeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Leyline_V1_StreamDescriptor` message.
        func subscribe(
            request: GRPCCore.ServerRequest<Leyline_V1_SubscribeRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Leyline_V1_StreamDescriptor>

        /// Handle the "Stream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GRPC transport only
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_Frame` messages.
        func stream(
            request: GRPCCore.ServerRequest<Leyline_V1_StreamRef>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Frame>

        /// Handle the "Unsubscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Leyline_V1_Empty` message.
        func unsubscribe(
            request: GRPCCore.ServerRequest<Leyline_V1_StreamRef>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Leyline_V1_Empty>
    }

    /// Simple service protocol for the "leyline.v1.Bulk" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Leyline_V1_Bulk.ServiceProtocol {
        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_SubscribeRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Leyline_V1_StreamDescriptor` to respond with.
        func subscribe(
            request: Leyline_V1_SubscribeRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Leyline_V1_StreamDescriptor

        /// Handle the "Stream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GRPC transport only
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_StreamRef` message.
        ///   - response: A response stream of `Leyline_V1_Frame` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func stream(
            request: Leyline_V1_StreamRef,
            response: GRPCCore.RPCWriter<Leyline_V1_Frame>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "Unsubscribe" method.
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_StreamRef` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Leyline_V1_Empty` to respond with.
        func unsubscribe(
            request: Leyline_V1_StreamRef,
            context: GRPCCore.ServerContext
        ) async throws -> Leyline_V1_Empty
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Leyline_V1_Bulk.Method.Subscribe.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_SubscribeRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_StreamDescriptor>(),
            handler: { request, context in
                try await self.subscribe(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Leyline_V1_Bulk.Method.Stream.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_StreamRef>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_Frame>(),
            handler: { request, context in
                try await self.stream(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Leyline_V1_Bulk.Method.Unsubscribe.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_StreamRef>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_Empty>(),
            handler: { request, context in
                try await self.unsubscribe(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk.ServiceProtocol {
    public func subscribe(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_SubscribeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_StreamDescriptor> {
        let response = try await self.subscribe(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func stream(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_StreamRef>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Frame> {
        let response = try await self.stream(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func unsubscribe(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_StreamRef>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Empty> {
        let response = try await self.unsubscribe(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk.SimpleServiceProtocol {
    public func subscribe(
        request: GRPCCore.ServerRequest<Leyline_V1_SubscribeRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Leyline_V1_StreamDescriptor> {
        return GRPCCore.ServerResponse<Leyline_V1_StreamDescriptor>(
            message: try await self.subscribe(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func stream(
        request: GRPCCore.ServerRequest<Leyline_V1_StreamRef>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_Frame> {
        return GRPCCore.StreamingServerResponse<Leyline_V1_Frame>(
            metadata: [:],
            producer: { writer in
                try await self.stream(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func unsubscribe(
        request: GRPCCore.ServerRequest<Leyline_V1_StreamRef>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Leyline_V1_Empty> {
        return GRPCCore.ServerResponse<Leyline_V1_Empty>(
            message: try await self.unsubscribe(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: leyline.v1.Bulk (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk {
    /// Generated client protocol for the "leyline.v1.Bulk" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_SubscribeRequest` message.
        ///   - serializer: A serializer for `Leyline_V1_SubscribeRequest` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_StreamDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func subscribe<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_SubscribeRequest>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_SubscribeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_StreamDescriptor>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_StreamDescriptor>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Stream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GRPC transport only
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - serializer: A serializer for `Leyline_V1_StreamRef` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_Frame` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func stream<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_StreamRef>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_Frame>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_Frame>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Unsubscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - serializer: A serializer for `Leyline_V1_StreamRef` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func unsubscribe<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_StreamRef>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "leyline.v1.Bulk" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_SubscribeRequest` message.
        ///   - serializer: A serializer for `Leyline_V1_SubscribeRequest` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_StreamDescriptor` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func subscribe<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_SubscribeRequest>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_SubscribeRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_StreamDescriptor>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_StreamDescriptor>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Leyline_V1_Bulk.Method.Subscribe.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Stream" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GRPC transport only
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - serializer: A serializer for `Leyline_V1_StreamRef` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_Frame` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func stream<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_StreamRef>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_Frame>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_Frame>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Leyline_V1_Bulk.Method.Stream.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Unsubscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
        ///   - serializer: A serializer for `Leyline_V1_StreamRef` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func unsubscribe<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_StreamRef>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Leyline_V1_Bulk.Method.Unsubscribe.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk.ClientProtocol {
    /// Call the "Subscribe" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_SubscribeRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribe<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_SubscribeRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_StreamDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.subscribe(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_SubscribeRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_StreamDescriptor>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Stream" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GRPC transport only
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func stream<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_Frame>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.stream(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_StreamRef>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_Frame>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Unsubscribe" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_StreamRef` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func unsubscribe<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_StreamRef>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unsubscribe(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_StreamRef>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Bulk.ClientProtocol {
    /// Call the "Subscribe" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribe<Result>(
        _ message: Leyline_V1_SubscribeRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_StreamDescriptor>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_SubscribeRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.subscribe(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Stream" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GRPC transport only
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func stream<Result>(
        _ message: Leyline_V1_StreamRef,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_Frame>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_StreamRef>(
            message: message,
            metadata: metadata
        )
        return try await self.stream(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Unsubscribe" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func unsubscribe<Result>(
        _ message: Leyline_V1_StreamRef,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_StreamRef>(
            message: message,
            metadata: metadata
        )
        return try await self.unsubscribe(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}