// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/jobs.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-License-Identifier: Apache-2.0

/// leyline.v1 — jobs and resources
/// A job is a daemon-owned persistent intent. Persistence follows intent: job outputs are
/// durable resources; interactive actions are ephemeral unless explicitly kept.
/// This is a table of watches, not a workflow engine — no retry DAG, no replay.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Leyline_V1_JobState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case running // = 1

  /// e.g. watch channel OUT_OF_CAPTURE — logging gaps, will rebind
  case degraded // = 2
  case completed // = 3
  case cancelled // = 4
  case failed // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .running
    case 2: self = .degraded
    case 3: self = .completed
    case 4: self = .cancelled
    case 5: self = .failed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .running: return 1
    case .degraded: return 2
    case .completed: return 3
    case .cancelled: return 4
    case .failed: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_JobState] = [
    .unspecified,
    .running,
    .degraded,
    .completed,
    .cancelled,
    .failed,
  ]

}

/// What opens and closes a recording's parts. A gated recording writes no file while the squelch is
/// closed, and its manifest says where the gaps were: time is never edited (invariant 5).
public nonisolated enum Leyline_V1_RecordGate: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case none // = 1
  case squelch // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .none
    case 2: self = .squelch
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .none: return 1
    case .squelch: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_RecordGate] = [
    .unspecified,
    .none,
    .squelch,
  ]

}

public nonisolated enum Leyline_V1_ResourceKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case recording // = 1
  case scan // = 2
  case snapshot // = 3
  case transcript // = 4

  /// ley://records/<job_id>, a kept decode job's records (decode.proto)
  case records // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .recording
    case 2: self = .scan
    case 3: self = .snapshot
    case 4: self = .transcript
    case 5: self = .records
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .recording: return 1
    case .scan: return 2
    case .snapshot: return 3
    case .transcript: return 4
    case .records: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_ResourceKind] = [
    .unspecified,
    .recording,
    .scan,
    .snapshot,
    .transcript,
    .records,
  ]

}

public nonisolated struct Leyline_V1_Job: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jobID: String {
    get {_storage._jobID}
    set {_uniqueStorage()._jobID = newValue}
  }

  public var state: Leyline_V1_JobState {
    get {_storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  public var createdAtNs: Int64 {
    get {_storage._createdAtNs}
    set {_uniqueStorage()._createdAtNs = newValue}
  }

  public var createdBy: Leyline_V1_ClientInfo {
    get {_storage._createdBy ?? Leyline_V1_ClientInfo()}
    set {_uniqueStorage()._createdBy = newValue}
  }
  /// Returns true if `createdBy` has been explicitly set.
  public var hasCreatedBy: Bool {_storage._createdBy != nil}
  /// Clears the value of `createdBy`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedBy() {_uniqueStorage()._createdBy = nil}

  public var config: OneOf_Config? {
    get {return _storage._config}
    set {_uniqueStorage()._config = newValue}
  }

  public var watch: Leyline_V1_WatchConfig {
    get {
      if case .watch(let v)? = _storage._config {return v}
      return Leyline_V1_WatchConfig()
    }
    set {_uniqueStorage()._config = .watch(newValue)}
  }

  public var scan: Leyline_V1_ScanConfig {
    get {
      if case .scan(let v)? = _storage._config {return v}
      return Leyline_V1_ScanConfig()
    }
    set {_uniqueStorage()._config = .scan(newValue)}
  }

  public var record: Leyline_V1_RecordConfig {
    get {
      if case .record(let v)? = _storage._config {return v}
      return Leyline_V1_RecordConfig()
    }
    set {_uniqueStorage()._config = .record(newValue)}
  }

  public var decode: Leyline_V1_DecodeConfig {
    get {
      if case .decode(let v)? = _storage._config {return v}
      return Leyline_V1_DecodeConfig()
    }
    set {_uniqueStorage()._config = .decode(newValue)}
  }

  public var monitor: Leyline_V1_MonitorConfig {
    get {
      if case .monitor(let v)? = _storage._config {return v}
      return Leyline_V1_MonitorConfig()
    }
    set {_uniqueStorage()._config = .monitor(newValue)}
  }

  /// ley:// resources produced so far. A record job's is ley://recordings/<job_id> and a kept
  /// decode job's ley://records/<job_id>; both are on disk and outlive the daemon, and the
  /// Resources service resolves them. A scan job's ley://scans/<scan_id> is resolved by
  /// Jobs.GetScan for as long as the daemon remembers the job (its last sixteen finished ones,
  /// forgotten on restart); a persisted scan arrives with the durable job store.
  public var resultUris: [String] {
    get {_storage._resultUris}
    set {_uniqueStorage()._resultUris = newValue}
  }

  /// human-readable, e.g. "out of capture since 14:02, 3 gaps logged"
  public var statusDetail: String {
    get {_storage._statusDetail}
    set {_uniqueStorage()._statusDetail = newValue}
  }

  /// Why a FAILED job failed: `code` is the stable string a client branches on and `message` the
  /// daemon's human-readable description. Set only on FAILED; `status_detail` is prose and never
  /// carries the code, so a client that wants to tell "the radio cannot tune that" from "somebody
  /// is using it" reads this rather than splitting an English sentence.
  public var error: Leyline_V1_ErrorDetail {
    get {_storage._error ?? Leyline_V1_ErrorDetail()}
    set {_uniqueStorage()._error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {_storage._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {_uniqueStorage()._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Config: Equatable, Sendable {
    case watch(Leyline_V1_WatchConfig)
    case scan(Leyline_V1_ScanConfig)
    case record(Leyline_V1_RecordConfig)
    case decode(Leyline_V1_DecodeConfig)
    case monitor(Leyline_V1_MonitorConfig)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// "Watch 146.52 and log anything heard." Owns a persistent channel; produces a transcript.
public nonisolated struct Leyline_V1_WatchConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var frequencyHz: UInt64 = 0

  public var mode: Leyline_V1_DemodMode = .unspecified

  public var recordClips: Bool = false

  /// 0 = until cancelled
  public var endAtNs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sweep -> persisted Scan resource. Respects don't-disturb: idle device or decline with reason.
public nonisolated struct Leyline_V1_ScanConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var range: Leyline_V1_FrequencyRange {
    get {_range ?? Leyline_V1_FrequencyRange()}
    set {_range = newValue}
  }
  /// Returns true if `range` has been explicitly set.
  public var hasRange: Bool {self._range != nil}
  /// Clears the value of `range`. Subsequent reads from it will return its default value.
  public mutating func clearRange() {self._range = nil}

  /// The advance between hops, chosen by the daemon from the radio's sample rate and its own
  /// geometry: a value sent here is ignored. `Job.config` echoes the request as it was made, and
  /// the copy carried by the resulting Scan states the advance the sweep really used.
  public var stepHz: UInt32 = 0

  public var dwellMs: UInt32 = 0

  public var schedule: Leyline_V1_ScanConfig.OneOf_Schedule? = nil

  public var once: Bool {
    get {
      if case .once(let v)? = schedule {return v}
      return false
    }
    set {schedule = .once(newValue)}
  }

  public var recurring: String {
    get {
      if case .recurring(let v)? = schedule {return v}
      return String()
    }
    set {schedule = .recurring(newValue)}
  }

  /// Sweep a radio somebody else is using. Off by default: a sweep owns the radio for seconds at a
  /// time, so the allocator declines a capture with channels, a live audio sink or a recent
  /// interactive write, and names what is using it. This is the explicit override.
  public var takeOver: Bool = false

  /// Which radio to sweep. Empty means the daemon picks: an idle device first, then one whose
  /// capture nobody is using. Without this a two-radio setup has no way to say which.
  public var deviceID: String = String()

  /// The tuner gain to sweep at. A sweep always pins the gain for its whole duration, because SNR
  /// measured against a moving AGC is meaningless; this sets the level. `db` pins the element there
  /// (the first gain element when `element` is empty); `auto` asks the driver where its AGC settles
  /// and pins that. Unset, the sweep pins the gain the radio is on -- whatever the last client left it at,
  /// which is why two sweeps of one band could differ by 6 dB of floor. `Scan.gains` reports the
  /// level the sweep ran at either way, and the entry gain is restored when the radio is handed back.
  public var gain: Leyline_V1_GainWrite {
    get {_gain ?? Leyline_V1_GainWrite()}
    set {_gain = newValue}
  }
  /// Returns true if `gain` has been explicitly set.
  public var hasGain: Bool {self._gain != nil}
  /// Clears the value of `gain`. Subsequent reads from it will return its default value.
  public mutating func clearGain() {self._gain = nil}

  /// Gains to pin, one stage at a time, applied in order, each read as `gain` is (an empty element
  /// is the device's first, a name matches ignoring case). When `gains` is non-empty `gain` is
  /// ignored; `gain` stays for a client that sends one stage. A refusal fails the sweep with the
  /// device's code and message, and `Scan.gains` still reports every stage the sweep ran at.
  public var gains: [Leyline_V1_GainWrite] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Schedule: Equatable, Sendable {
    case once(Bool)
    case recurring(String)

  }

  public init() {}

  fileprivate var _range: Leyline_V1_FrequencyRange? = nil
  fileprivate var _gain: Leyline_V1_GainWrite? = nil
}

/// A recording is a job's output (docs/design/recording.md). Control.AttachSink(file) stays
/// refused: a sink attached to somebody's channel dies with that channel's owner and leaves a file
/// nothing indexes, while a job goes through the allocator (invariant 9), outlives the client that
/// started it, and produces a resource (invariant 8). The job's id is the recording's id, so
/// `Job.result_uris` holds ley://recordings/<job_id>.
public nonisolated struct Leyline_V1_RecordConfig: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var frequencyHz: UInt64 {
    get {_storage._frequencyHz}
    set {_uniqueStorage()._frequencyHz = newValue}
  }

  /// RAW_IQ records the capture's IQ; anything else records audio
  public var mode: Leyline_V1_DemodMode {
    get {_storage._mode}
    set {_uniqueStorage()._mode = newValue}
  }

  /// 0 = now; a later start is refused UNIMPLEMENTED in v1
  public var startAtNs: Int64 {
    get {_storage._startAtNs}
    set {_uniqueStorage()._startAtNs = newValue}
  }

  /// 0 = until cancelled or stop_after_quiet_ms
  public var durationMs: Int64 {
    get {_storage._durationMs}
    set {_uniqueStorage()._durationMs = newValue}
  }

  /// Record what an existing channel hears, with its mode, bandwidth and squelch. frequency_hz
  /// and mode are ignored. The job borrows the channel and does not own it: when the channel's
  /// owner destroys it the job ends COMPLETED, "channel ended". With RAW_IQ the channel's capture
  /// is recorded.
  public var channelID: String {
    get {_storage._channelID}
    set {_uniqueStorage()._channelID = newValue}
  }

  /// empty = the daemon picks, as a scan or decode does
  public var deviceID: String {
    get {_storage._deviceID}
    set {_uniqueStorage()._deviceID = newValue}
  }

  /// retune a capture somebody is using; off by default
  public var takeOver: Bool {
    get {_storage._takeOver}
    set {_uniqueStorage()._takeOver = newValue}
  }

  /// 0 = the mode's default, as CreateChannel
  public var bandwidthHz: UInt32 {
    get {_storage._bandwidthHz}
    set {_uniqueStorage()._bandwidthHz = newValue}
  }

  /// NaN or unset = the channel default (auto), as ley tune
  public var squelchDbfs: Double {
    get {_storage._squelchDbfs}
    set {_uniqueStorage()._squelchDbfs = newValue}
  }

  /// absent = leave the radio's gain alone
  public var gain: Leyline_V1_GainWrite {
    get {_storage._gain ?? Leyline_V1_GainWrite()}
    set {_uniqueStorage()._gain = newValue}
  }
  /// Returns true if `gain` has been explicitly set.
  public var hasGain: Bool {_storage._gain != nil}
  /// Clears the value of `gain`. Subsequent reads from it will return its default value.
  public mutating func clearGain() {_uniqueStorage()._gain = nil}

  /// NONE (default) or SQUELCH
  public var gate: Leyline_V1_RecordGate {
    get {_storage._gate}
    set {_uniqueStorage()._gate = newValue}
  }

  /// audio kept from before the squelch opened; default 500
  public var preRollMs: UInt32 {
    get {_storage._preRollMs}
    set {_uniqueStorage()._preRollMs = newValue}
  }

  /// how long after the squelch closes a part stays open; default 5000
  public var hangMs: UInt32 {
    get {_storage._hangMs}
    set {_uniqueStorage()._hangMs = newValue}
  }

  /// end the job after this long with the squelch closed; 0 = never
  public var stopAfterQuietMs: Int64 {
    get {_storage._stopAfterQuietMs}
    set {_uniqueStorage()._stopAfterQuietMs = newValue}
  }

  /// cut parts on this timer; 0 = audio: one part, IQ: 60000
  public var partMs: Int64 {
    get {_storage._partMs}
    set {_uniqueStorage()._partMs = newValue}
  }

  /// Gains to set on the capture the job makes, applied in order, each read as `gain` is (an empty
  /// element is the device's first). A refusal fails the job with the device's code and message.
  /// When `gains` is non-empty `gain` is ignored; `gain` stays for a client that sends one stage.
  /// A borrowed channel's capture is left as its owner set it, whichever is sent.
  public var gains: [Leyline_V1_GainWrite] {
    get {_storage._gains}
    set {_uniqueStorage()._gains = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Watch one band -- narrow enough to fit a single capture -- and report the carriers that come and
/// go, in time order. Unlike a scan it does not sweep: it parks one capture on the band and runs the
/// detector continuously, so it never time-shares and cannot miss a transmission by being tuned
/// elsewhere. Detections stream on the telemetry plane (DETECTION), the same as a scan's;
/// the client folds them into a transmission log. A band wider than one capture can analyse is
/// refused with INVALID_ARGUMENT (use scan, which sweeps). This is the band-watching design's
/// occupancy/burst view (docs/design/band-watching.md), the stationary sibling of ley scan.
public nonisolated struct Leyline_V1_MonitorConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// the band to watch; must fit one capture
  public var range: Leyline_V1_FrequencyRange {
    get {_range ?? Leyline_V1_FrequencyRange()}
    set {_range = newValue}
  }
  /// Returns true if `range` has been explicitly set.
  public var hasRange: Bool {self._range != nil}
  /// Clears the value of `range`. Subsequent reads from it will return its default value.
  public mutating func clearRange() {self._range = nil}

  /// how long to watch; 0 = until cancelled
  public var durationMs: Int64 = 0

  /// Which radio. Empty means the daemon picks, as a scan does.
  public var deviceID: String = String()

  /// Watch even when somebody is using the radio; off by default, same don't-disturb rule as a scan.
  public var takeOver: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _range: Leyline_V1_FrequencyRange? = nil
}

/// Contiguous squelch-open interval on a watched channel. The building block of transcripts.
public nonisolated struct Leyline_V1_ActivitySegment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var start: Leyline_V1_SampleTime {
    get {_start ?? Leyline_V1_SampleTime()}
    set {_start = newValue}
  }
  /// Returns true if `start` has been explicitly set.
  public var hasStart: Bool {self._start != nil}
  /// Clears the value of `start`. Subsequent reads from it will return its default value.
  public mutating func clearStart() {self._start = nil}

  public var end: Leyline_V1_SampleTime {
    get {_end ?? Leyline_V1_SampleTime()}
    set {_end = newValue}
  }
  /// Returns true if `end` has been explicitly set.
  public var hasEnd: Bool {self._end != nil}
  /// Clears the value of `end`. Subsequent reads from it will return its default value.
  public mutating func clearEnd() {self._end = nil}

  public var peakDbfs: Double = 0

  public var meanDbfs: Double = 0

  /// empty if clips weren't recorded
  public var clipUri: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _start: Leyline_V1_SampleTime? = nil
  fileprivate var _end: Leyline_V1_SampleTime? = nil
}

public nonisolated struct Leyline_V1_Transcript: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jobID: String = String()

  public var segments: [Leyline_V1_ActivitySegment] = []

  /// out-of-capture or daemon downtime, listed rather than hidden
  public var coverageGaps: [Leyline_V1_Gap] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_Scan: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scanID: String {
    get {_storage._scanID}
    set {_uniqueStorage()._scanID = newValue}
  }

  public var config: Leyline_V1_ScanConfig {
    get {_storage._config ?? Leyline_V1_ScanConfig()}
    set {_uniqueStorage()._config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {_storage._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {_uniqueStorage()._config = nil}

  public var detections: [Leyline_V1_Detection] {
    get {_storage._detections}
    set {_uniqueStorage()._detections = newValue}
  }

  public var noiseFloor: [Leyline_V1_NoiseFloorSegment] {
    get {_storage._noiseFloor}
    set {_uniqueStorage()._noiseFloor = newValue}
  }

  public var startedAtNs: Int64 {
    get {_storage._startedAtNs}
    set {_uniqueStorage()._startedAtNs = newValue}
  }

  public var completedAtNs: Int64 {
    get {_storage._completedAtNs}
    set {_uniqueStorage()._completedAtNs = newValue}
  }

  /// The gain the sweep pinned for its whole duration. A sweep must not run under the tuner's AGC
  /// -- the gain moves after every hop and SNR against a moving reference is meaningless -- and a
  /// scan that does not say which gain it ran at cannot be compared with another.
  public var gains: [Leyline_V1_GainState] {
    get {_storage._gains}
    set {_uniqueStorage()._gains = newValue}
  }

  /// The analysis bin width, in Hz. Every dB in this message -- floor_dbfs, snr_db -- is per bin,
  /// and those numbers depend on the bin width: a wider bin holds more noise. A
  /// client should print this alongside the floor rather than deriving it from step_hz, which
  /// describes where the radio pointed and not how finely it looked.
  public var resolutionHz: UInt32 {
    get {_storage._resolutionHz}
    set {_uniqueStorage()._resolutionHz = newValue}
  }

  /// What the sweep actually covered. Never wider than config.range, and narrower whenever the
  /// radio could not reach all of it, the request fell partly in the tuner's own blind spot, or the
  /// sweep was stopped early. A client must not report config.range as the searched range: part of
  /// it may never have been measured.
  public var covered: Leyline_V1_FrequencyRange {
    get {_storage._covered ?? Leyline_V1_FrequencyRange()}
    set {_uniqueStorage()._covered = newValue}
  }
  /// Returns true if `covered` has been explicitly set.
  public var hasCovered: Bool {_storage._covered != nil}
  /// Clears the value of `covered`. Subsequent reads from it will return its default value.
  public mutating func clearCovered() {_uniqueStorage()._covered = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Leyline_V1_NoiseFloorSegment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var range: Leyline_V1_FrequencyRange {
    get {_range ?? Leyline_V1_FrequencyRange()}
    set {_range = newValue}
  }
  /// Returns true if `range` has been explicitly set.
  public var hasRange: Bool {self._range != nil}
  /// Clears the value of `range`. Subsequent reads from it will return its default value.
  public mutating func clearRange() {self._range = nil}

  public var floorDbfs: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _range: Leyline_V1_FrequencyRange? = nil
}

public nonisolated struct Leyline_V1_Resource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uri: String = String()

  public var kind: Leyline_V1_ResourceKind = .unspecified

  public var createdAtNs: Int64 = 0

  public var sizeBytes: UInt64 = 0

  /// empty for explicit keeps
  public var originatingJobID: String = String()

  /// Queryable, and frozen per kind because ListResourcesRequest.metadata_filter matches on these
  /// by exact string. A RECORDING carries: kind (audio|iq), frequency_hz, mode, sample_rate,
  /// format, duration_ms, parts, started_at_ns, ended_at_ns, ended_by, device
  /// (docs/design/recording.md, "The wire"). Adding a key is additive; renaming one is not.
  public var metadata: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_StartJobRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var config: Leyline_V1_StartJobRequest.OneOf_Config? = nil

  public var watch: Leyline_V1_WatchConfig {
    get {
      if case .watch(let v)? = config {return v}
      return Leyline_V1_WatchConfig()
    }
    set {config = .watch(newValue)}
  }

  public var scan: Leyline_V1_ScanConfig {
    get {
      if case .scan(let v)? = config {return v}
      return Leyline_V1_ScanConfig()
    }
    set {config = .scan(newValue)}
  }

  public var record: Leyline_V1_RecordConfig {
    get {
      if case .record(let v)? = config {return v}
      return Leyline_V1_RecordConfig()
    }
    set {config = .record(newValue)}
  }

  public var decode: Leyline_V1_DecodeConfig {
    get {
      if case .decode(let v)? = config {return v}
      return Leyline_V1_DecodeConfig()
    }
    set {config = .decode(newValue)}
  }

  public var monitor: Leyline_V1_MonitorConfig {
    get {
      if case .monitor(let v)? = config {return v}
      return Leyline_V1_MonitorConfig()
    }
    set {config = .monitor(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Config: Equatable, Sendable {
    case watch(Leyline_V1_WatchConfig)
    case scan(Leyline_V1_ScanConfig)
    case record(Leyline_V1_RecordConfig)
    case decode(Leyline_V1_DecodeConfig)
    case monitor(Leyline_V1_MonitorConfig)

  }

  public init() {}
}

public nonisolated struct Leyline_V1_ListJobsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var states: [Leyline_V1_JobState] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_ListJobsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jobs: [Leyline_V1_Job] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_JobRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jobID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_TranscriptRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var jobID: String = String()

  public var from: Leyline_V1_StreamPosition {
    get {_from ?? Leyline_V1_StreamPosition()}
    set {_from = newValue}
  }
  /// Returns true if `from` has been explicitly set.
  public var hasFrom: Bool {self._from != nil}
  /// Clears the value of `from`. Subsequent reads from it will return its default value.
  public mutating func clearFrom() {self._from = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _from: Leyline_V1_StreamPosition? = nil
}

public nonisolated struct Leyline_V1_ScanRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scanID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_ListResourcesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Leyline_V1_ResourceKind = .unspecified

  public var metadataFilter: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_ListResourcesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var resources: [Leyline_V1_Resource] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_ResourceRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uri: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_LocalPath: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var path: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "leyline.v1"

nonisolated extension Leyline_V1_JobState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0JOB_STATE_UNSPECIFIED\0\u{1}RUNNING\0\u{1}DEGRADED\0\u{1}COMPLETED\0\u{1}CANCELLED\0\u{1}FAILED\0")
}

nonisolated extension Leyline_V1_RecordGate: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RECORD_GATE_UNSPECIFIED\0\u{1}NONE\0\u{1}SQUELCH\0")
}

nonisolated extension Leyline_V1_ResourceKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESOURCE_KIND_UNSPECIFIED\0\u{1}RECORDING\0\u{1}SCAN\0\u{1}SNAPSHOT\0\u{1}TRANSCRIPT\0\u{1}RECORDS\0")
}

nonisolated extension Leyline_V1_Job: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Job"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}job_id\0\u{1}state\0\u{3}created_at_ns\0\u{3}created_by\0\u{1}watch\0\u{1}scan\0\u{1}record\0\u{3}result_uris\0\u{3}status_detail\0\u{1}error\0\u{1}decode\0\u{1}monitor\0")

  fileprivate class _StorageClass {
    var _jobID: String = String()
    var _state: Leyline_V1_JobState = .unspecified
    var _createdAtNs: Int64 = 0
    var _createdBy: Leyline_V1_ClientInfo? = nil
    var _config: Leyline_V1_Job.OneOf_Config?
    var _resultUris: [String] = []
    var _statusDetail: String = String()
    var _error: Leyline_V1_ErrorDetail? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _jobID = source._jobID
      _state = source._state
      _createdAtNs = source._createdAtNs
      _createdBy = source._createdBy
      _config = source._config
      _resultUris = source._resultUris
      _statusDetail = source._statusDetail
      _error = source._error
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._jobID) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._state) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._createdAtNs) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._createdBy) }()
        case 5: try {
          var v: Leyline_V1_WatchConfig?
          var hadOneofValue = false
          if let current = _storage._config {
            hadOneofValue = true
            if case .watch(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._config = .watch(v)
          }
        }()
        case 6: try {
          var v: Leyline_V1_ScanConfig?
          var hadOneofValue = false
          if let current = _storage._config {
            hadOneofValue = true
            if case .scan(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._config = .scan(v)
          }
        }()
        case 7: try {
          var v: Leyline_V1_RecordConfig?
          var hadOneofValue = false
          if let current = _storage._config {
            hadOneofValue = true
            if case .record(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._config = .record(v)
          }
        }()
        case 8: try { try decoder.decodeRepeatedStringField(value: &_storage._resultUris) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._statusDetail) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._error) }()
        case 11: try {
          var v: Leyline_V1_DecodeConfig?
          var hadOneofValue = false
          if let current = _storage._config {
            hadOneofValue = true
            if case .decode(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._config = .decode(v)
          }
        }()
        case 12: try {
          var v: Leyline_V1_MonitorConfig?
          var hadOneofValue = false
          if let current = _storage._config {
            hadOneofValue = true
            if case .monitor(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._config = .monitor(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._jobID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._jobID, fieldNumber: 1)
      }
      if _storage._state != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._state, fieldNumber: 2)
      }
      if _storage._createdAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._createdAtNs, fieldNumber: 3)
      }
      try { if let v = _storage._createdBy {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      switch _storage._config {
      case .watch?: try {
        guard case .watch(let v)? = _storage._config else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }()
      case .scan?: try {
        guard case .scan(let v)? = _storage._config else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .record?: try {
        guard case .record(let v)? = _storage._config else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      default: break
      }
      if !_storage._resultUris.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._resultUris, fieldNumber: 8)
      }
      if !_storage._statusDetail.isEmpty {
        try visitor.visitSingularStringField(value: _storage._statusDetail, fieldNumber: 9)
      }
      try { if let v = _storage._error {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      switch _storage._config {
      case .decode?: try {
        guard case .decode(let v)? = _storage._config else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }()
      case .monitor?: try {
        guard case .monitor(let v)? = _storage._config else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }()
      default: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Job, rhs: Leyline_V1_Job) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._jobID != rhs_storage._jobID {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._createdAtNs != rhs_storage._createdAtNs {return false}
        if _storage._createdBy != rhs_storage._createdBy {return false}
        if _storage._config != rhs_storage._config {return false}
        if _storage._resultUris != rhs_storage._resultUris {return false}
        if _storage._statusDetail != rhs_storage._statusDetail {return false}
        if _storage._error != rhs_storage._error {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_WatchConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WatchConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}frequency_hz\0\u{1}mode\0\u{3}record_clips\0\u{3}end_at_ns\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.frequencyHz) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.recordClips) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.endAtNs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.frequencyHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.frequencyHz, fieldNumber: 1)
    }
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 2)
    }
    if self.recordClips != false {
      try visitor.visitSingularBoolField(value: self.recordClips, fieldNumber: 3)
    }
    if self.endAtNs != 0 {
      try visitor.visitSingularInt64Field(value: self.endAtNs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_WatchConfig, rhs: Leyline_V1_WatchConfig) -> Bool {
    if lhs.frequencyHz != rhs.frequencyHz {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.recordClips != rhs.recordClips {return false}
    if lhs.endAtNs != rhs.endAtNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ScanConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}range\0\u{3}step_hz\0\u{3}dwell_ms\0\u{1}once\0\u{1}recurring\0\u{3}take_over\0\u{3}device_id\0\u{1}gain\0\u{1}gains\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._range) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.stepHz) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.dwellMs) }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.schedule != nil {try decoder.handleConflictingOneOf()}
          self.schedule = .once(v)
        }
      }()
      case 5: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.schedule != nil {try decoder.handleConflictingOneOf()}
          self.schedule = .recurring(v)
        }
      }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.takeOver) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._gain) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.gains) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._range {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.stepHz != 0 {
      try visitor.visitSingularUInt32Field(value: self.stepHz, fieldNumber: 2)
    }
    if self.dwellMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.dwellMs, fieldNumber: 3)
    }
    switch self.schedule {
    case .once?: try {
      guard case .once(let v)? = self.schedule else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case .recurring?: try {
      guard case .recurring(let v)? = self.schedule else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    if self.takeOver != false {
      try visitor.visitSingularBoolField(value: self.takeOver, fieldNumber: 6)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 7)
    }
    try { if let v = self._gain {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if !self.gains.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.gains, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ScanConfig, rhs: Leyline_V1_ScanConfig) -> Bool {
    if lhs._range != rhs._range {return false}
    if lhs.stepHz != rhs.stepHz {return false}
    if lhs.dwellMs != rhs.dwellMs {return false}
    if lhs.schedule != rhs.schedule {return false}
    if lhs.takeOver != rhs.takeOver {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs._gain != rhs._gain {return false}
    if lhs.gains != rhs.gains {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_RecordConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}frequency_hz\0\u{1}mode\0\u{3}start_at_ns\0\u{3}duration_ms\0\u{3}channel_id\0\u{3}device_id\0\u{3}take_over\0\u{3}bandwidth_hz\0\u{3}squelch_dbfs\0\u{1}gain\0\u{1}gate\0\u{3}pre_roll_ms\0\u{3}hang_ms\0\u{3}stop_after_quiet_ms\0\u{3}part_ms\0\u{1}gains\0")

  fileprivate class _StorageClass {
    var _frequencyHz: UInt64 = 0
    var _mode: Leyline_V1_DemodMode = .unspecified
    var _startAtNs: Int64 = 0
    var _durationMs: Int64 = 0
    var _channelID: String = String()
    var _deviceID: String = String()
    var _takeOver: Bool = false
    var _bandwidthHz: UInt32 = 0
    var _squelchDbfs: Double = 0
    var _gain: Leyline_V1_GainWrite? = nil
    var _gate: Leyline_V1_RecordGate = .unspecified
    var _preRollMs: UInt32 = 0
    var _hangMs: UInt32 = 0
    var _stopAfterQuietMs: Int64 = 0
    var _partMs: Int64 = 0
    var _gains: [Leyline_V1_GainWrite] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _frequencyHz = source._frequencyHz
      _mode = source._mode
      _startAtNs = source._startAtNs
      _durationMs = source._durationMs
      _channelID = source._channelID
      _deviceID = source._deviceID
      _takeOver = source._takeOver
      _bandwidthHz = source._bandwidthHz
      _squelchDbfs = source._squelchDbfs
      _gain = source._gain
      _gate = source._gate
      _preRollMs = source._preRollMs
      _hangMs = source._hangMs
      _stopAfterQuietMs = source._stopAfterQuietMs
      _partMs = source._partMs
      _gains = source._gains
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._frequencyHz) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._mode) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._startAtNs) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._durationMs) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._channelID) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._deviceID) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._takeOver) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._bandwidthHz) }()
        case 9: try { try decoder.decodeSingularDoubleField(value: &_storage._squelchDbfs) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._gain) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._gate) }()
        case 12: try { try decoder.decodeSingularUInt32Field(value: &_storage._preRollMs) }()
        case 13: try { try decoder.decodeSingularUInt32Field(value: &_storage._hangMs) }()
        case 14: try { try decoder.decodeSingularInt64Field(value: &_storage._stopAfterQuietMs) }()
        case 15: try { try decoder.decodeSingularInt64Field(value: &_storage._partMs) }()
        case 16: try { try decoder.decodeRepeatedMessageField(value: &_storage._gains) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._frequencyHz != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._frequencyHz, fieldNumber: 1)
      }
      if _storage._mode != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._mode, fieldNumber: 2)
      }
      if _storage._startAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._startAtNs, fieldNumber: 3)
      }
      if _storage._durationMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._durationMs, fieldNumber: 4)
      }
      if !_storage._channelID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._channelID, fieldNumber: 5)
      }
      if !_storage._deviceID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deviceID, fieldNumber: 6)
      }
      if _storage._takeOver != false {
        try visitor.visitSingularBoolField(value: _storage._takeOver, fieldNumber: 7)
      }
      if _storage._bandwidthHz != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._bandwidthHz, fieldNumber: 8)
      }
      if _storage._squelchDbfs.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._squelchDbfs, fieldNumber: 9)
      }
      try { if let v = _storage._gain {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if _storage._gate != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._gate, fieldNumber: 11)
      }
      if _storage._preRollMs != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._preRollMs, fieldNumber: 12)
      }
      if _storage._hangMs != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._hangMs, fieldNumber: 13)
      }
      if _storage._stopAfterQuietMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._stopAfterQuietMs, fieldNumber: 14)
      }
      if _storage._partMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._partMs, fieldNumber: 15)
      }
      if !_storage._gains.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._gains, fieldNumber: 16)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_RecordConfig, rhs: Leyline_V1_RecordConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._frequencyHz != rhs_storage._frequencyHz {return false}
        if _storage._mode != rhs_storage._mode {return false}
        if _storage._startAtNs != rhs_storage._startAtNs {return false}
        if _storage._durationMs != rhs_storage._durationMs {return false}
        if _storage._channelID != rhs_storage._channelID {return false}
        if _storage._deviceID != rhs_storage._deviceID {return false}
        if _storage._takeOver != rhs_storage._takeOver {return false}
        if _storage._bandwidthHz != rhs_storage._bandwidthHz {return false}
        if _storage._squelchDbfs != rhs_storage._squelchDbfs {return false}
        if _storage._gain != rhs_storage._gain {return false}
        if _storage._gate != rhs_storage._gate {return false}
        if _storage._preRollMs != rhs_storage._preRollMs {return false}
        if _storage._hangMs != rhs_storage._hangMs {return false}
        if _storage._stopAfterQuietMs != rhs_storage._stopAfterQuietMs {return false}
        if _storage._partMs != rhs_storage._partMs {return false}
        if _storage._gains != rhs_storage._gains {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_MonitorConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MonitorConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}range\0\u{3}duration_ms\0\u{3}device_id\0\u{3}take_over\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._range) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.durationMs) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.takeOver) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._range {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.durationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.durationMs, fieldNumber: 2)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 3)
    }
    if self.takeOver != false {
      try visitor.visitSingularBoolField(value: self.takeOver, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_MonitorConfig, rhs: Leyline_V1_MonitorConfig) -> Bool {
    if lhs._range != rhs._range {return false}
    if lhs.durationMs != rhs.durationMs {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.takeOver != rhs.takeOver {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ActivitySegment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ActivitySegment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}start\0\u{1}end\0\u{3}peak_dbfs\0\u{3}mean_dbfs\0\u{3}clip_uri\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._start) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._end) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.peakDbfs) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.meanDbfs) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.clipUri) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._start {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._end {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.peakDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.peakDbfs, fieldNumber: 3)
    }
    if self.meanDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.meanDbfs, fieldNumber: 4)
    }
    if !self.clipUri.isEmpty {
      try visitor.visitSingularStringField(value: self.clipUri, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ActivitySegment, rhs: Leyline_V1_ActivitySegment) -> Bool {
    if lhs._start != rhs._start {return false}
    if lhs._end != rhs._end {return false}
    if lhs.peakDbfs != rhs.peakDbfs {return false}
    if lhs.meanDbfs != rhs.meanDbfs {return false}
    if lhs.clipUri != rhs.clipUri {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Transcript: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Transcript"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}job_id\0\u{1}segments\0\u{3}coverage_gaps\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.segments) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.coverageGaps) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 1)
    }
    if !self.segments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.segments, fieldNumber: 2)
    }
    if !self.coverageGaps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.coverageGaps, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Transcript, rhs: Leyline_V1_Transcript) -> Bool {
    if lhs.jobID != rhs.jobID {return false}
    if lhs.segments != rhs.segments {return false}
    if lhs.coverageGaps != rhs.coverageGaps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Scan: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Scan"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}scan_id\0\u{1}config\0\u{1}detections\0\u{3}noise_floor\0\u{3}started_at_ns\0\u{3}completed_at_ns\0\u{1}gains\0\u{3}resolution_hz\0\u{1}covered\0")

  fileprivate class _StorageClass {
    var _scanID: String = String()
    var _config: Leyline_V1_ScanConfig? = nil
    var _detections: [Leyline_V1_Detection] = []
    var _noiseFloor: [Leyline_V1_NoiseFloorSegment] = []
    var _startedAtNs: Int64 = 0
    var _completedAtNs: Int64 = 0
    var _gains: [Leyline_V1_GainState] = []
    var _resolutionHz: UInt32 = 0
    var _covered: Leyline_V1_FrequencyRange? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _scanID = source._scanID
      _config = source._config
      _detections = source._detections
      _noiseFloor = source._noiseFloor
      _startedAtNs = source._startedAtNs
      _completedAtNs = source._completedAtNs
      _gains = source._gains
      _resolutionHz = source._resolutionHz
      _covered = source._covered
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._scanID) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._config) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._detections) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._noiseFloor) }()
        case 5: try { try decoder.decodeSingularInt64Field(value: &_storage._startedAtNs) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._completedAtNs) }()
        case 7: try { try decoder.decodeRepeatedMessageField(value: &_storage._gains) }()
        case 8: try { try decoder.decodeSingularUInt32Field(value: &_storage._resolutionHz) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._covered) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._scanID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scanID, fieldNumber: 1)
      }
      try { if let v = _storage._config {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._detections.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._detections, fieldNumber: 3)
      }
      if !_storage._noiseFloor.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._noiseFloor, fieldNumber: 4)
      }
      if _storage._startedAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._startedAtNs, fieldNumber: 5)
      }
      if _storage._completedAtNs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._completedAtNs, fieldNumber: 6)
      }
      if !_storage._gains.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._gains, fieldNumber: 7)
      }
      if _storage._resolutionHz != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._resolutionHz, fieldNumber: 8)
      }
      try { if let v = _storage._covered {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Scan, rhs: Leyline_V1_Scan) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._scanID != rhs_storage._scanID {return false}
        if _storage._config != rhs_storage._config {return false}
        if _storage._detections != rhs_storage._detections {return false}
        if _storage._noiseFloor != rhs_storage._noiseFloor {return false}
        if _storage._startedAtNs != rhs_storage._startedAtNs {return false}
        if _storage._completedAtNs != rhs_storage._completedAtNs {return false}
        if _storage._gains != rhs_storage._gains {return false}
        if _storage._resolutionHz != rhs_storage._resolutionHz {return false}
        if _storage._covered != rhs_storage._covered {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_NoiseFloorSegment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NoiseFloorSegment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}range\0\u{3}floor_dbfs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._range) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.floorDbfs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._range {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.floorDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.floorDbfs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_NoiseFloorSegment, rhs: Leyline_V1_NoiseFloorSegment) -> Bool {
    if lhs._range != rhs._range {return false}
    if lhs.floorDbfs != rhs.floorDbfs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Resource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Resource"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0\u{1}kind\0\u{3}created_at_ns\0\u{3}size_bytes\0\u{3}originating_job_id\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.createdAtNs) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.sizeBytes) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.originatingJobID) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if self.createdAtNs != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAtNs, fieldNumber: 3)
    }
    if self.sizeBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.sizeBytes, fieldNumber: 4)
    }
    if !self.originatingJobID.isEmpty {
      try visitor.visitSingularStringField(value: self.originatingJobID, fieldNumber: 5)
    }
    if !self.metadata.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadata, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Resource, rhs: Leyline_V1_Resource) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.createdAtNs != rhs.createdAtNs {return false}
    if lhs.sizeBytes != rhs.sizeBytes {return false}
    if lhs.originatingJobID != rhs.originatingJobID {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_StartJobRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartJobRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}watch\0\u{1}scan\0\u{1}record\0\u{1}decode\0\u{1}monitor\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Leyline_V1_WatchConfig?
        var hadOneofValue = false
        if let current = self.config {
          hadOneofValue = true
          if case .watch(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.config = .watch(v)
        }
      }()
      case 2: try {
        var v: Leyline_V1_ScanConfig?
        var hadOneofValue = false
        if let current = self.config {
          hadOneofValue = true
          if case .scan(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.config = .scan(v)
        }
      }()
      case 3: try {
        var v: Leyline_V1_RecordConfig?
        var hadOneofValue = false
        if let current = self.config {
          hadOneofValue = true
          if case .record(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.config = .record(v)
        }
      }()
      case 4: try {
        var v: Leyline_V1_DecodeConfig?
        var hadOneofValue = false
        if let current = self.config {
          hadOneofValue = true
          if case .decode(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.config = .decode(v)
        }
      }()
      case 5: try {
        var v: Leyline_V1_MonitorConfig?
        var hadOneofValue = false
        if let current = self.config {
          hadOneofValue = true
          if case .monitor(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.config = .monitor(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.config {
    case .watch?: try {
      guard case .watch(let v)? = self.config else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .scan?: try {
      guard case .scan(let v)? = self.config else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .record?: try {
      guard case .record(let v)? = self.config else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .decode?: try {
      guard case .decode(let v)? = self.config else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .monitor?: try {
      guard case .monitor(let v)? = self.config else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_StartJobRequest, rhs: Leyline_V1_StartJobRequest) -> Bool {
    if lhs.config != rhs.config {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListJobsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListJobsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}states\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedEnumField(value: &self.states) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.states.isEmpty {
      try visitor.visitPackedEnumField(value: self.states, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListJobsRequest, rhs: Leyline_V1_ListJobsRequest) -> Bool {
    if lhs.states != rhs.states {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListJobsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListJobsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}jobs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.jobs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jobs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.jobs, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListJobsResponse, rhs: Leyline_V1_ListJobsResponse) -> Bool {
    if lhs.jobs != rhs.jobs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_JobRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".JobRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}job_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_JobRef, rhs: Leyline_V1_JobRef) -> Bool {
    if lhs.jobID != rhs.jobID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_TranscriptRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TranscriptRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}job_id\0\u{1}from\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._from) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 1)
    }
    try { if let v = self._from {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_TranscriptRequest, rhs: Leyline_V1_TranscriptRequest) -> Bool {
    if lhs.jobID != rhs.jobID {return false}
    if lhs._from != rhs._from {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ScanRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScanRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}scan_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.scanID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.scanID.isEmpty {
      try visitor.visitSingularStringField(value: self.scanID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ScanRef, rhs: Leyline_V1_ScanRef) -> Bool {
    if lhs.scanID != rhs.scanID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListResourcesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListResourcesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{3}metadata_filter\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadataFilter) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 1)
    }
    if !self.metadataFilter.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadataFilter, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListResourcesRequest, rhs: Leyline_V1_ListResourcesRequest) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.metadataFilter != rhs.metadataFilter {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListResourcesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListResourcesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}resources\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.resources) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.resources.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.resources, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListResourcesResponse, rhs: Leyline_V1_ListResourcesResponse) -> Bool {
    if lhs.resources != rhs.resources {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ResourceRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ResourceRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uri\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uri) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uri.isEmpty {
      try visitor.visitSingularStringField(value: self.uri, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ResourceRef, rhs: Leyline_V1_ResourceRef) -> Bool {
    if lhs.uri != rhs.uri {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_LocalPath: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalPath"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_LocalPath, rhs: Leyline_V1_LocalPath) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
