import Foundation
import Synchronization
import XCTest
@testable import EngineCore

/// Collects f32 audio frames delivered by a `CallbackSink`.
final class AudioCollector: @unchecked Sendable {
    private let lock = NSLock()
    private var samples: [Float] = []
    private var firstIndex: UInt64?
    private(set) var sink: CallbackSink!

    init() {
        sink = CallbackSink { [unowned self] buffer, time in self.append(buffer, time) }
    }

    private func append(_ buffer: SampleBuffer, _ time: SampleTime) {
        guard buffer.format == .f32 else { return }
        lock.lock()
        if firstIndex == nil { firstIndex = time.sampleIndex }
        samples.append(contentsOf: UnsafeBufferPointer(start: buffer.base.assumingMemoryBound(to: Float.self), count: buffer.count))
        lock.unlock()
    }

    var count: Int { lock.lock(); defer { lock.unlock() }; return samples.count }
    var all: [Float] { lock.lock(); defer { lock.unlock() }; return samples }
    var startIndex: UInt64? { lock.lock(); defer { lock.unlock() }; return firstIndex }
}

enum FixtureAnalysis {
    /// Dominant tone (Hz) and SNR (dB) of the highest-energy `size`-sample window (so keyed CW is
    /// measured while keyed, as `leyfix check` does): Hann window, FFT, peak search above 50 Hz,
    /// SNR = peak lobe (±`lobe` bins) over everything else in 50 Hz … 0.45·rate.
    static func dominantTone(_ audio: [Float], rate: Double, size: Int = 16384, lobe: Int = 5) -> (toneHz: Double, snrDB: Double) {
        precondition(audio.count >= size)
        var start = 0
        var best = -1.0
        var offset = 0
        while offset + size <= audio.count {
            var energy = 0.0
            for i in offset ..< offset + size { energy += Double(audio[i] * audio[i]) }
            if energy > best { best = energy; start = offset }
            offset += size / 4
        }
        let re = UnsafeMutablePointer<Float>.allocate(capacity: size)
        let im = UnsafeMutablePointer<Float>.allocate(capacity: size)
        let outRe = UnsafeMutablePointer<Float>.allocate(capacity: size)
        let outIm = UnsafeMutablePointer<Float>.allocate(capacity: size)
        defer { re.deallocate(); im.deallocate(); outRe.deallocate(); outIm.deallocate() }
        for i in 0 ..< size {
            let w = 0.5 - 0.5 * cos(2 * Double.pi * Double(i) / Double(size))
            re[i] = Float(w) * audio[start + i]
            im[i] = 0
        }
        FFTPlan(size: size).forward(inRe: re, inIm: im, outRe: outRe, outIm: outIm)
        let binHz = rate / Double(size)
        let lo = Int(50 / binHz), hi = Int(0.45 * rate / binHz)
        var power = [Double](repeating: 0, count: size / 2)
        for k in 0 ..< size / 2 { power[k] = Double(outRe[k] * outRe[k] + outIm[k] * outIm[k]) }
        var peak = lo
        for k in lo ... hi where power[k] > power[peak] { peak = k }
        var signal = 0.0, noise = 0.0
        for k in lo ... hi {
            if abs(k - peak) <= lobe { signal += power[k] } else { noise += power[k] }
        }
        // Parabolic interpolation of the peak bin for sub-bin accuracy.
        var frac = 0.0
        if peak > lo, peak < hi {
            let a = log(max(power[peak - 1], 1e-30)), b = log(max(power[peak], 1e-30)), c = log(max(power[peak + 1], 1e-30))
            let d = a - 2 * b + c
            if d != 0 { frac = 0.5 * (a - c) / d }
        }
        return ((Double(peak) + frac) * binHz, 10 * log10(signal / max(noise, 1e-30)))
    }
}

/// Fixture discovery: `$LEYLINE_FIXTURES` if set, else `<repo>/fixtures` relative to this source file.
/// Fixtures are generated by `make fixtures` (`leyfix generate`); the tests skip when none exist.
enum Fixtures {
    static let dir: String = {
        if let env = ProcessInfo.processInfo.environment["LEYLINE_FIXTURES"], !env.isEmpty { return env }
        // <repo>/engine/Tests/EngineCoreTests/FixtureTests.swift → <repo>/fixtures
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0 ..< 4 { url.deleteLastPathComponent() }
        return url.appendingPathComponent("fixtures").path
    }()

    static func sidecars() throws -> [String] {
        let files = ((try? FileManager.default.contentsOfDirectory(atPath: dir)) ?? [])
            .filter { $0.hasSuffix(".cf32") }.sorted()
        if files.isEmpty {
            throw XCTSkip("no .cf32 fixtures in \(dir); run `make fixtures` or set LEYLINE_FIXTURES")
        }
        return files.map { dir + "/" + $0 }
    }
}

/// End-to-end fixture round trips: FilePlaybackDevice → DefaultCaptureEngine → DefaultChannelEngine → CallbackSink.
final class FixtureTests: XCTestCase {
    struct ChannelRun {
        let engine: DefaultChannelEngine
        let audio: AudioCollector
        let meterEngine: DefaultChannelEngine
        var meters: [(power: Double, open: Bool)] = []
    }

    /// Runs every `expect` entry of one fixture concurrently on a single capture and returns the
    /// collected audio + meter readings per entry. `seconds` of audio are collected after `skip` seconds.
    func run(fixture path: String, seconds: Double = 0.6, skip: Double = 0.15) async throws -> [(IQSidecar.Expectation, ChannelRun)] {
        let device = try FilePlaybackDevice(path: path, loop: true, realtime: true)
        let sidecar = device.sidecar
        let capture = DefaultCaptureEngine(device: device, centerHz: UInt64(sidecar.centerHz), sampleRate: UInt64(sidecar.sampleRate))
        var runs: [(IQSidecar.Expectation, ChannelRun)] = []
        for e in sidecar.expect ?? [] {
            guard let mode = DemodMode(rawValue: e.mode.lowercased()) else { throw XCTSkip("unknown mode \(e.mode)") }
            let bw = e.bandwidthHz ?? mode.defaultBandwidthHz
            let engine = try await capture.addChannel(ChannelConfig(offsetHz: e.offsetHz, bandwidthHz: bw, mode: mode)) as! DefaultChannelEngine
            let collector = AudioCollector()
            try await engine.attach(collector.sink)
            // Second channel on the same signal with the reference squelch at −40 dBFS for the meter checks.
            let meterEngine = try await capture.addChannel(ChannelConfig(offsetHz: e.offsetHz, bandwidthHz: bw, mode: mode, squelchDB: -40)) as! DefaultChannelEngine
            runs.append((e, ChannelRun(engine: engine, audio: collector, meterEngine: meterEngine)))
        }
        let meterTasks = runs.map { run in
            Task<[(power: Double, open: Bool)], Never> {
                var out: [(power: Double, open: Bool)] = []
                for await t in run.1.meterEngine.telemetry() {
                    if case let .meter(_, power, _, open, _, _) = t { out.append((power, open)) }
                }
                return out
            }
        }
        try await capture.start()
        let need = runs.map { Int((seconds + skip) * Double($0.1.engine.audioRate)) }
        let deadline = Date().addingTimeInterval(seconds + skip + 10)
        while Date() < deadline, zip(runs, need).contains(where: { $0.0.1.audio.count < $0.1 }) {
            try await Task.sleep(nanoseconds: 20_000_000)
        }
        await capture.stop()
        for i in runs.indices { runs[i].1.meters = await meterTasks[i].value }
        for (_, run) in runs { XCTAssertGreaterThan(run.audio.count, 0, "no audio collected") }
        XCTAssertEqual(capture.stats.overruns, 0, "ring overruns during \(path)")
        return runs
    }

    func check(_ path: String) async throws {
        let name = (path as NSString).lastPathComponent
        for (e, run) in try await run(fixture: path) {
            let rate = Double(run.engine.audioRate)
            if let audio = e.audio, let toneHz = audio.toneHz {
                let result = FixtureAnalysis.dominantTone(run.audio.all, rate: rate, size: e.mode.lowercased() == "cw" ? 8192 : 16384)
                XCTAssertEqual(result.toneHz, toneHz, accuracy: toneHz * 0.02, "\(name) \(e.mode)@\(e.offsetHz): tone")
                if let minSNR = audio.minSnrDb {
                    XCTAssertGreaterThanOrEqual(result.snrDB, minSNR, "\(name) \(e.mode)@\(e.offsetHz): SNR")
                }
                print("fixture \(name) \(e.mode)@\(e.offsetHz): tone \(String(format: "%.1f", result.toneHz)) Hz snr \(String(format: "%.1f", result.snrDB)) dB (min \(audio.minSnrDb ?? .nan)) frames \(run.audio.count)")
            }
            if let meter = e.meter {
                XCTAssertFalse(run.meters.isEmpty, "\(name): no meter telemetry")
                // Strongest 100 ms reading (keyed CW is off between elements); squelch = "ever opened".
                let power = run.meters.map(\.power).max() ?? .nan
                let opened = run.meters.contains { $0.open }
                if let minPower = meter.powerDbfsMin {
                    XCTAssertGreaterThanOrEqual(power, minPower, "\(name) \(e.mode)@\(e.offsetHz): power")
                }
                if let open = meter.squelchOpen {
                    XCTAssertEqual(opened, open, "\(name) \(e.mode)@\(e.offsetHz): squelch @-40 dBFS")
                }
                print("fixture \(name) \(e.mode)@\(e.offsetHz): power \(String(format: "%.1f", power)) dBFS (min \(meter.powerDbfsMin ?? .nan)) squelch opened=\(opened) meters \(run.meters.count)")
            }
        }
    }

    func testAllFixtures() async throws {
        for path in try Fixtures.sidecars() {
            try await check(path)
        }
    }
}
