// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/bulk.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// leyline.v1 — bulk plane
/// Sample-bearing streams. Offer/answer negotiation; the answer is authoritative.
/// Payloads are opaque bytes in the negotiated format — samples are never protobuf-encoded per element.
/// No lossless network stream exists: lossless work is a daemon-side FileSink.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Leyline_V1_StreamKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case iq // = 1
  case fft // = 2
  case audio // = 3
  case decoded // = 4
  case persistence // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .iq
    case 2: self = .fft
    case 3: self = .audio
    case 4: self = .decoded
    case 5: self = .persistence
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .iq: return 1
    case .fft: return 2
    case .audio: return 3
    case .decoded: return 4
    case .persistence: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_StreamKind] = [
    .unspecified,
    .iq,
    .fft,
    .audio,
    .decoded,
    .persistence,
  ]

}

public nonisolated enum Leyline_V1_Transport: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case grpc // = 1
  case shmRing // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .grpc
    case 2: self = .shmRing
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .grpc: return 1
    case .shmRing: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_Transport] = [
    .unspecified,
    .grpc,
    .shmRing,
  ]

}

public nonisolated enum Leyline_V1_FftAccumulation: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Value names are siblings of their type within the package (C++ scoping),
  /// so these carry a ROW_ prefix: a bare SNAPSHOT collides with ResourceKind.
  case rowSnapshot // = 1

  /// power mean over the row: a stable floor, dilutes short bursts
  case rowMean // = 2

  /// max over the row: catches bursts; the noise floor reads
  case rowMax // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .rowSnapshot
    case 2: self = .rowMean
    case 3: self = .rowMax
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .rowSnapshot: return 1
    case .rowMean: return 2
    case .rowMax: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_FftAccumulation] = [
    .unspecified,
    .rowSnapshot,
    .rowMean,
    .rowMax,
  ]

}

public nonisolated enum Leyline_V1_FftBinFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case dbU8 // = 1
  case dbF32 // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .dbU8
    case 2: self = .dbF32
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .dbU8: return 1
    case .dbF32: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_FftBinFormat] = [
    .unspecified,
    .dbU8,
    .dbF32,
  ]

}

public nonisolated enum Leyline_V1_AudioSampleFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case s16 // = 1
  case f32 // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .s16
    case 2: self = .f32
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .s16: return 1
    case .f32: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_AudioSampleFormat] = [
    .unspecified,
    .s16,
    .f32,
  ]

}

public nonisolated struct Leyline_V1_SubscribeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var source: Leyline_V1_SubscribeRequest.OneOf_Source? = nil

  /// IQ / FFT of the whole capture
  public var captureID: String {
    get {
      if case .captureID(let v)? = source {return v}
      return String()
    }
    set {source = .captureID(newValue)}
  }

  /// audio / decoded / channel-filtered IQ
  public var channelID: String {
    get {
      if case .channelID(let v)? = source {return v}
      return String()
    }
    set {source = .channelID(newValue)}
  }

  public var kind: Leyline_V1_StreamKind = .unspecified

  /// default LATEST_WINS
  public var policy: Leyline_V1_DeliveryPolicy = .unspecified

  /// v0: LIVE only
  public var start: Leyline_V1_StreamPosition {
    get {_start ?? Leyline_V1_StreamPosition()}
    set {_start = newValue}
  }
  /// Returns true if `start` has been explicitly set.
  public var hasStart: Bool {self._start != nil}
  /// Clears the value of `start`. Subsequent reads from it will return its default value.
  public mutating func clearStart() {self._start = nil}

  /// default GRPC; SHM_RING local-only
  public var transport: Leyline_V1_Transport = .unspecified

  /// Desired parameters; daemon may downgrade, never upgrade.
  public var params: Leyline_V1_SubscribeRequest.OneOf_Params? = nil

  public var iq: Leyline_V1_IqParams {
    get {
      if case .iq(let v)? = params {return v}
      return Leyline_V1_IqParams()
    }
    set {params = .iq(newValue)}
  }

  public var fft: Leyline_V1_FftParams {
    get {
      if case .fft(let v)? = params {return v}
      return Leyline_V1_FftParams()
    }
    set {params = .fft(newValue)}
  }

  public var audio: Leyline_V1_AudioParams {
    get {
      if case .audio(let v)? = params {return v}
      return Leyline_V1_AudioParams()
    }
    set {params = .audio(newValue)}
  }

  public var persistence: Leyline_V1_PersistenceParams {
    get {
      if case .persistence(let v)? = params {return v}
      return Leyline_V1_PersistenceParams()
    }
    set {params = .persistence(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Source: Equatable, Sendable {
    /// IQ / FFT of the whole capture
    case captureID(String)
    /// audio / decoded / channel-filtered IQ
    case channelID(String)

  }

  /// Desired parameters; daemon may downgrade, never upgrade.
  public nonisolated enum OneOf_Params: Equatable, Sendable {
    case iq(Leyline_V1_IqParams)
    case fft(Leyline_V1_FftParams)
    case audio(Leyline_V1_AudioParams)
    case persistence(Leyline_V1_PersistenceParams)

  }

  public init() {}

  fileprivate var _start: Leyline_V1_StreamPosition? = nil
}

/// v0 IQ contract: the daemon serves raw IQ as CF32 at the capture's native sample rate only.
/// A request must leave `format` UNSPECIFIED or CF32 and `sample_rate` 0 or the capture rate;
/// anything else is refused with INVALID_ARGUMENT (the message names the accepted values) rather
/// than silently overridden. The descriptor always answers CF32 at the capture rate. Integer
/// formats (CS8/CS16) and decimated IQ are additive v1 negotiation, not a v0 promise.
public nonisolated struct Leyline_V1_IqParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sampleRate: UInt64 = 0

  public var format: Leyline_V1_SampleFormat = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_FftParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// daemon serves from a fixed power-of-two ladder
  public var bins: UInt32 = 0

  public var binFormat: Leyline_V1_FftBinFormat = .unspecified

  public var rowsPerSecond: Double = 0

  /// How a row is built from the samples it covers. ROW_SNAPSHOT (the default, and
  /// what a request that leaves this unset gets) computes one periodogram per
  /// row from whichever block crossed the row boundary: at 2.4 MSPS a
  /// 1024-point FFT covers 0.17% of a 250 ms row, so a burst shorter than the
  /// row appears only sometimes. That is fine for a live band chart, whose
  /// reader is looking at "now", and wrong for anything reading duty cycle.
  public var accumulation: Leyline_V1_FftAccumulation = .unspecified

  /// Looks the daemon actually took per row. Answer only: a request must leave
  /// it 0. Always 1 under SNAPSHOT.
  public var looksPerRow: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_AudioParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sampleRate: UInt32 = 0

  public var format: Leyline_V1_AudioSampleFormat = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A persistence (phosphor) frame: for each frequency bin, how often each level
/// has been seen lately. Bright means usual, faint means rare-but-real. It
/// answers a different question from FFT -- "what is usually here" rather than
/// "what is here now" -- and it is the one band view that works without fine
/// time resolution, because it accumulates over time instead of resolving it.
///
/// Payload is `bins * levels` little-endian uint16 counts, bin-major: all of
/// bin 0's level buckets, then bin 1's. Level bucket i covers
/// [floor_db + i*range_db/levels, floor_db + (i+1)*range_db/levels).
///
/// The client supplies floor_db and range_db and the daemon does not guess: a
/// daemon-chosen scale would have to appear in the descriptor before any row
/// had arrived. A request that leaves them 0 is refused rather than defaulted,
/// because a persistence frame on the wrong scale is not obviously wrong to
/// look at.
///
/// Counts halve every half_life_seconds, which bounds them and makes "usual"
/// mean "usual lately". They saturate at uint16 max rather than wrapping.
public nonisolated struct Leyline_V1_PersistenceParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// served from the FFT ladder's power-of-two sizes
  public var bins: UInt32 = 0

  /// level buckets per bin
  public var levels: UInt32 = 0

  /// dBFS at the bottom of the level axis
  public var floorDb: Double = 0

  /// dB the level axis spans
  public var rangeDb: Double = 0

  /// how fast a count decays; 0 = daemon default
  public var halfLifeSeconds: Double = 0

  /// frames delivered, not rows accumulated
  public var rowsPerSecond: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The authoritative answer. Clients interpret frames from this alone.
public nonisolated struct Leyline_V1_StreamDescriptor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: String = String()

  public var kind: Leyline_V1_StreamKind = .unspecified

  public var policy: Leyline_V1_DeliveryPolicy = .unspecified

  public var params: Leyline_V1_StreamDescriptor.OneOf_Params? = nil

  public var iq: Leyline_V1_IqParams {
    get {
      if case .iq(let v)? = params {return v}
      return Leyline_V1_IqParams()
    }
    set {params = .iq(newValue)}
  }

  public var fft: Leyline_V1_FftParams {
    get {
      if case .fft(let v)? = params {return v}
      return Leyline_V1_FftParams()
    }
    set {params = .fft(newValue)}
  }

  public var audio: Leyline_V1_AudioParams {
    get {
      if case .audio(let v)? = params {return v}
      return Leyline_V1_AudioParams()
    }
    set {params = .audio(newValue)}
  }

  public var persistence: Leyline_V1_PersistenceParams {
    get {
      if case .persistence(let v)? = params {return v}
      return Leyline_V1_PersistenceParams()
    }
    set {params = .persistence(newValue)}
  }

  /// FFT/IQ/persistence context
  public var centerHz: UInt64 = 0

  public var spanHz: UInt64 = 0

  public var transport: Leyline_V1_StreamDescriptor.OneOf_Transport? = nil

  /// pull via Stream(stream_id)
  public var grpc: Bool {
    get {
      if case .grpc(let v)? = transport {return v}
      return false
    }
    set {transport = .grpc(newValue)}
  }

  public var shm: Leyline_V1_ShmRing {
    get {
      if case .shm(let v)? = transport {return v}
      return Leyline_V1_ShmRing()
    }
    set {transport = .shm(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Params: Equatable, Sendable {
    case iq(Leyline_V1_IqParams)
    case fft(Leyline_V1_FftParams)
    case audio(Leyline_V1_AudioParams)
    case persistence(Leyline_V1_PersistenceParams)

  }

  public nonisolated enum OneOf_Transport: Equatable, Sendable {
    /// pull via Stream(stream_id)
    case grpc(Bool)
    case shm(Leyline_V1_ShmRing)

  }

  public init() {}
}

/// Local fast path. Ring layout (native byte order):
///   header: magic "LEYR", u32 version, u64 write_seq (monotonic), u32 slot_size, u32 slot_count,
///           serialized StreamDescriptor
///   slot:   u64 seq, u64 sample_index, u32 payload_len, payload
/// Readers chase write_seq; falling behind is detected by seq check -> resync (latest-wins by construction).
public nonisolated struct Leyline_V1_ShmRing: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// POSIX shm name
  public var path: String = String()

  public var slotSize: UInt32 = 0

  public var slotCount: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_Frame: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: String = String()

  public var seq: UInt64 = 0

  public var time: Leyline_V1_SampleTime {
    get {_time ?? Leyline_V1_SampleTime()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {self._time = nil}

  /// present only under GAP_MARKED after a drop
  public var gap: Leyline_V1_Gap {
    get {_gap ?? Leyline_V1_Gap()}
    set {_gap = newValue}
  }
  /// Returns true if `gap` has been explicitly set.
  public var hasGap: Bool {self._gap != nil}
  /// Clears the value of `gap`. Subsequent reads from it will return its default value.
  public mutating func clearGap() {self._gap = nil}

  /// format per StreamDescriptor
  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _time: Leyline_V1_SampleTime? = nil
  fileprivate var _gap: Leyline_V1_Gap? = nil
}

public nonisolated struct Leyline_V1_StreamRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "leyline.v1"

nonisolated extension Leyline_V1_StreamKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STREAM_KIND_UNSPECIFIED\0\u{1}IQ\0\u{1}FFT\0\u{1}AUDIO\0\u{1}DECODED\0\u{1}PERSISTENCE\0")
}

nonisolated extension Leyline_V1_Transport: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TRANSPORT_UNSPECIFIED\0\u{1}GRPC\0\u{1}SHM_RING\0")
}

nonisolated extension Leyline_V1_FftAccumulation: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FFT_ACCUMULATION_UNSPECIFIED\0\u{1}ROW_SNAPSHOT\0\u{1}ROW_MEAN\0\u{1}ROW_MAX\0")
}

nonisolated extension Leyline_V1_FftBinFormat: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FFT_BIN_FORMAT_UNSPECIFIED\0\u{1}DB_U8\0\u{1}DB_F32\0")
}

nonisolated extension Leyline_V1_AudioSampleFormat: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIO_SAMPLE_FORMAT_UNSPECIFIED\0\u{1}S16\0\u{1}F32\0")
}

nonisolated extension Leyline_V1_SubscribeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SubscribeRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_id\0\u{3}channel_id\0\u{1}kind\0\u{1}policy\0\u{1}start\0\u{1}transport\0\u{1}iq\0\u{1}fft\0\u{1}audio\0\u{1}persistence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.source != nil {try decoder.handleConflictingOneOf()}
          self.source = .captureID(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.source != nil {try decoder.handleConflictingOneOf()}
          self.source = .channelID(v)
        }
      }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.policy) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._start) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.transport) }()
      case 7: try {
        var v: Leyline_V1_IqParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .iq(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .iq(v)
        }
      }()
      case 8: try {
        var v: Leyline_V1_FftParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .fft(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .fft(v)
        }
      }()
      case 9: try {
        var v: Leyline_V1_AudioParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .audio(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .audio(v)
        }
      }()
      case 10: try {
        var v: Leyline_V1_PersistenceParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .persistence(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .persistence(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.source {
    case .captureID?: try {
      guard case .captureID(let v)? = self.source else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .channelID?: try {
      guard case .channelID(let v)? = self.source else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 3)
    }
    if self.policy != .unspecified {
      try visitor.visitSingularEnumField(value: self.policy, fieldNumber: 4)
    }
    try { if let v = self._start {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.transport != .unspecified {
      try visitor.visitSingularEnumField(value: self.transport, fieldNumber: 6)
    }
    switch self.params {
    case .iq?: try {
      guard case .iq(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .fft?: try {
      guard case .fft(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .audio?: try {
      guard case .audio(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .persistence?: try {
      guard case .persistence(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_SubscribeRequest, rhs: Leyline_V1_SubscribeRequest) -> Bool {
    if lhs.source != rhs.source {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.policy != rhs.policy {return false}
    if lhs._start != rhs._start {return false}
    if lhs.transport != rhs.transport {return false}
    if lhs.params != rhs.params {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_IqParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IqParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sample_rate\0\u{1}format\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sampleRate) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.format) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sampleRate != 0 {
      try visitor.visitSingularUInt64Field(value: self.sampleRate, fieldNumber: 1)
    }
    if self.format != .unspecified {
      try visitor.visitSingularEnumField(value: self.format, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_IqParams, rhs: Leyline_V1_IqParams) -> Bool {
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.format != rhs.format {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FftParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FftParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bins\0\u{3}bin_format\0\u{3}rows_per_second\0\u{1}accumulation\0\u{3}looks_per_row\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.bins) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.binFormat) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.rowsPerSecond) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.accumulation) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.looksPerRow) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bins != 0 {
      try visitor.visitSingularUInt32Field(value: self.bins, fieldNumber: 1)
    }
    if self.binFormat != .unspecified {
      try visitor.visitSingularEnumField(value: self.binFormat, fieldNumber: 2)
    }
    if self.rowsPerSecond.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.rowsPerSecond, fieldNumber: 3)
    }
    if self.accumulation != .unspecified {
      try visitor.visitSingularEnumField(value: self.accumulation, fieldNumber: 4)
    }
    if self.looksPerRow != 0 {
      try visitor.visitSingularUInt32Field(value: self.looksPerRow, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FftParams, rhs: Leyline_V1_FftParams) -> Bool {
    if lhs.bins != rhs.bins {return false}
    if lhs.binFormat != rhs.binFormat {return false}
    if lhs.rowsPerSecond != rhs.rowsPerSecond {return false}
    if lhs.accumulation != rhs.accumulation {return false}
    if lhs.looksPerRow != rhs.looksPerRow {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_AudioParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AudioParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sample_rate\0\u{1}format\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.sampleRate) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.format) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sampleRate != 0 {
      try visitor.visitSingularUInt32Field(value: self.sampleRate, fieldNumber: 1)
    }
    if self.format != .unspecified {
      try visitor.visitSingularEnumField(value: self.format, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_AudioParams, rhs: Leyline_V1_AudioParams) -> Bool {
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.format != rhs.format {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_PersistenceParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PersistenceParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bins\0\u{1}levels\0\u{3}floor_db\0\u{3}range_db\0\u{3}half_life_seconds\0\u{3}rows_per_second\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.bins) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.levels) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.floorDb) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.rangeDb) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.halfLifeSeconds) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.rowsPerSecond) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.bins != 0 {
      try visitor.visitSingularUInt32Field(value: self.bins, fieldNumber: 1)
    }
    if self.levels != 0 {
      try visitor.visitSingularUInt32Field(value: self.levels, fieldNumber: 2)
    }
    if self.floorDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.floorDb, fieldNumber: 3)
    }
    if self.rangeDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.rangeDb, fieldNumber: 4)
    }
    if self.halfLifeSeconds.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.halfLifeSeconds, fieldNumber: 5)
    }
    if self.rowsPerSecond.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.rowsPerSecond, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_PersistenceParams, rhs: Leyline_V1_PersistenceParams) -> Bool {
    if lhs.bins != rhs.bins {return false}
    if lhs.levels != rhs.levels {return false}
    if lhs.floorDb != rhs.floorDb {return false}
    if lhs.rangeDb != rhs.rangeDb {return false}
    if lhs.halfLifeSeconds != rhs.halfLifeSeconds {return false}
    if lhs.rowsPerSecond != rhs.rowsPerSecond {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_StreamDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamDescriptor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{1}kind\0\u{1}policy\0\u{1}iq\0\u{1}fft\0\u{1}audio\0\u{3}center_hz\0\u{3}span_hz\0\u{1}grpc\0\u{1}shm\0\u{1}persistence\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.policy) }()
      case 4: try {
        var v: Leyline_V1_IqParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .iq(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .iq(v)
        }
      }()
      case 5: try {
        var v: Leyline_V1_FftParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .fft(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .fft(v)
        }
      }()
      case 6: try {
        var v: Leyline_V1_AudioParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .audio(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .audio(v)
        }
      }()
      case 7: try { try decoder.decodeSingularUInt64Field(value: &self.centerHz) }()
      case 8: try { try decoder.decodeSingularUInt64Field(value: &self.spanHz) }()
      case 9: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.transport != nil {try decoder.handleConflictingOneOf()}
          self.transport = .grpc(v)
        }
      }()
      case 10: try {
        var v: Leyline_V1_ShmRing?
        var hadOneofValue = false
        if let current = self.transport {
          hadOneofValue = true
          if case .shm(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.transport = .shm(v)
        }
      }()
      case 11: try {
        var v: Leyline_V1_PersistenceParams?
        var hadOneofValue = false
        if let current = self.params {
          hadOneofValue = true
          if case .persistence(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.params = .persistence(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.streamID.isEmpty {
      try visitor.visitSingularStringField(value: self.streamID, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if self.policy != .unspecified {
      try visitor.visitSingularEnumField(value: self.policy, fieldNumber: 3)
    }
    switch self.params {
    case .iq?: try {
      guard case .iq(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .fft?: try {
      guard case .fft(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .audio?: try {
      guard case .audio(let v)? = self.params else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    default: break
    }
    if self.centerHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.centerHz, fieldNumber: 7)
    }
    if self.spanHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.spanHz, fieldNumber: 8)
    }
    switch self.transport {
    case .grpc?: try {
      guard case .grpc(let v)? = self.transport else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    }()
    case .shm?: try {
      guard case .shm(let v)? = self.transport else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try { if case .persistence(let v)? = self.params {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_StreamDescriptor, rhs: Leyline_V1_StreamDescriptor) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.policy != rhs.policy {return false}
    if lhs.params != rhs.params {return false}
    if lhs.centerHz != rhs.centerHz {return false}
    if lhs.spanHz != rhs.spanHz {return false}
    if lhs.transport != rhs.transport {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ShmRing: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ShmRing"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{3}slot_size\0\u{3}slot_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.slotSize) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.slotCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if self.slotSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.slotSize, fieldNumber: 2)
    }
    if self.slotCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.slotCount, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ShmRing, rhs: Leyline_V1_ShmRing) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.slotSize != rhs.slotSize {return false}
    if lhs.slotCount != rhs.slotCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Frame: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Frame"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{1}seq\0\u{1}time\0\u{1}gap\0\u{1}payload\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.seq) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._time) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._gap) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.streamID.isEmpty {
      try visitor.visitSingularStringField(value: self.streamID, fieldNumber: 1)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt64Field(value: self.seq, fieldNumber: 2)
    }
    try { if let v = self._time {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._gap {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Frame, rhs: Leyline_V1_Frame) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs._time != rhs._time {return false}
    if lhs._gap != rhs._gap {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_StreamRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.streamID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.streamID.isEmpty {
      try visitor.visitSingularStringField(value: self.streamID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_StreamRef, rhs: Leyline_V1_StreamRef) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
