/// leyline.v1 — shared types
/// IDs are prefixed ULIDs: dev_, cap_, chan_, sink_, job_, scan_, rec_, snap_, strm_

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

// This file contained no services.