// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// leyline.v1 — shared types
/// IDs are prefixed ULIDs: dev_, cap_, chan_, sink_, job_, scan_, rec_, snap_, strm_

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Leyline_V1_DeliveryPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// drop oldest silently; sequence numbers expose gaps
  case latestWins // = 1

  /// drops preceded by an explicit gap record
  case gapMarked // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .latestWins
    case 2: self = .gapMarked
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .latestWins: return 1
    case .gapMarked: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_DeliveryPolicy] = [
    .unspecified,
    .latestWins,
    .gapMarked,
  ]

}

/// Demodulators. Here rather than in control.proto because jobs name modes too, and control.proto
/// has to be able to see a Job (Event.body) -- which would be a circular import the other way.
public nonisolated enum Leyline_V1_DemodMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case am // = 1
  case nfm // = 2
  case wfm // = 3
  case usb // = 4
  case lsb // = 5
  case cw // = 6
  case rawIq // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .am
    case 2: self = .nfm
    case 3: self = .wfm
    case 4: self = .usb
    case 5: self = .lsb
    case 6: self = .cw
    case 7: self = .rawIq
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .am: return 1
    case .nfm: return 2
    case .wfm: return 3
    case .usb: return 4
    case .lsb: return 5
    case .cw: return 6
    case .rawIq: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_DemodMode] = [
    .unspecified,
    .am,
    .nfm,
    .wfm,
    .usb,
    .lsb,
    .cw,
    .rawIq,
  ]

}

/// Sample-indexed timebase. Wall clock is derived via CaptureAnchor, never carried per-frame.
/// capture_id scopes the timeline; future non-capture timelines (e.g. tx_ transmissions)
/// reuse this field with their own IDs — do not assume it always names a Capture.
public nonisolated struct Leyline_V1_SampleTime: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var captureID: String = String()

  /// samples since capture start, at the capture's rate
  public var sampleIndex: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One per capture: maps sample 0 to host time.
public nonisolated struct Leyline_V1_CaptureAnchor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var captureID: String = String()

  /// CLOCK_REALTIME at sample 0
  public var hostTimeNs: Int64 = 0

  public var sampleRate: UInt64 = 0

  /// measured, 0 if unknown
  public var driftPpm: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_FrequencyRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var minHz: UInt64 = 0

  public var maxHz: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Attribution — every event names the client that caused it (arbitration by visibility).
public nonisolated struct Leyline_V1_ClientInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// daemon-assigned per connection
  public var clientID: String = String()

  /// "app" | "cli" | "mcp" | "job" | other
  public var kind: String = String()

  /// human-readable, client-supplied
  public var label: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_Gap: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// inclusive
  public var fromSample: UInt64 = 0

  /// exclusive
  public var toSample: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Subscription start position. v0 implements LIVE only; others return UNIMPLEMENTED.
public nonisolated struct Leyline_V1_StreamPosition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var position: Leyline_V1_StreamPosition.OneOf_Position? = nil

  public var live: Bool {
    get {
      if case .live(let v)? = position {return v}
      return false
    }
    set {position = .live(newValue)}
  }

  public var atSample: Leyline_V1_SampleTime {
    get {
      if case .atSample(let v)? = position {return v}
      return Leyline_V1_SampleTime()
    }
    set {position = .atSample(newValue)}
  }

  public var atHostTimeNs: Int64 {
    get {
      if case .atHostTimeNs(let v)? = position {return v}
      return 0
    }
    set {position = .atHostTimeNs(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Position: Equatable, Sendable {
    case live(Bool)
    case atSample(Leyline_V1_SampleTime)
    case atHostTimeNs(Int64)

  }

  public init() {}
}

public nonisolated struct Leyline_V1_ErrorDetail: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// stable machine string, e.g. "FREQ_OUT_OF_RANGE"
  public var code: String = String()

  public var message: String = String()

  /// id of the object the error concerns
  public var target: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Confirmed gain of one element; a capture event carries all of them (full state, never deltas),
/// and a scan carries the ones it pinned for the sweep.
public nonisolated struct Leyline_V1_GainState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var element: String = String()

  public var db: Double = 0

  public var auto: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "leyline.v1"

nonisolated extension Leyline_V1_DeliveryPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DELIVERY_POLICY_UNSPECIFIED\0\u{1}LATEST_WINS\0\u{1}GAP_MARKED\0")
}

nonisolated extension Leyline_V1_DemodMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEMOD_MODE_UNSPECIFIED\0\u{1}AM\0\u{1}NFM\0\u{1}WFM\0\u{1}USB\0\u{1}LSB\0\u{1}CW\0\u{1}RAW_IQ\0")
}

nonisolated extension Leyline_V1_SampleTime: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SampleTime"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_id\0\u{3}sample_index\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.captureID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sampleIndex) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.captureID.isEmpty {
      try visitor.visitSingularStringField(value: self.captureID, fieldNumber: 1)
    }
    if self.sampleIndex != 0 {
      try visitor.visitSingularUInt64Field(value: self.sampleIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_SampleTime, rhs: Leyline_V1_SampleTime) -> Bool {
    if lhs.captureID != rhs.captureID {return false}
    if lhs.sampleIndex != rhs.sampleIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_CaptureAnchor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CaptureAnchor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_id\0\u{3}host_time_ns\0\u{3}sample_rate\0\u{3}drift_ppm\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.captureID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.hostTimeNs) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.sampleRate) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.driftPpm) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.captureID.isEmpty {
      try visitor.visitSingularStringField(value: self.captureID, fieldNumber: 1)
    }
    if self.hostTimeNs != 0 {
      try visitor.visitSingularInt64Field(value: self.hostTimeNs, fieldNumber: 2)
    }
    if self.sampleRate != 0 {
      try visitor.visitSingularUInt64Field(value: self.sampleRate, fieldNumber: 3)
    }
    if self.driftPpm.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.driftPpm, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_CaptureAnchor, rhs: Leyline_V1_CaptureAnchor) -> Bool {
    if lhs.captureID != rhs.captureID {return false}
    if lhs.hostTimeNs != rhs.hostTimeNs {return false}
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.driftPpm != rhs.driftPpm {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FrequencyRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FrequencyRange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}min_hz\0\u{3}max_hz\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.minHz) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.maxHz) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.minHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.minHz, fieldNumber: 1)
    }
    if self.maxHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.maxHz, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FrequencyRange, rhs: Leyline_V1_FrequencyRange) -> Bool {
    if lhs.minHz != rhs.minHz {return false}
    if lhs.maxHz != rhs.maxHz {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ClientInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_id\0\u{1}kind\0\u{1}label\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.clientID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientID.isEmpty {
      try visitor.visitSingularStringField(value: self.clientID, fieldNumber: 1)
    }
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ClientInfo, rhs: Leyline_V1_ClientInfo) -> Bool {
    if lhs.clientID != rhs.clientID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.label != rhs.label {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Gap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Gap"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}from_sample\0\u{3}to_sample\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.fromSample) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.toSample) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.fromSample != 0 {
      try visitor.visitSingularUInt64Field(value: self.fromSample, fieldNumber: 1)
    }
    if self.toSample != 0 {
      try visitor.visitSingularUInt64Field(value: self.toSample, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Gap, rhs: Leyline_V1_Gap) -> Bool {
    if lhs.fromSample != rhs.fromSample {return false}
    if lhs.toSample != rhs.toSample {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_StreamPosition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamPosition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}live\0\u{3}at_sample\0\u{3}at_host_time_ns\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.position != nil {try decoder.handleConflictingOneOf()}
          self.position = .live(v)
        }
      }()
      case 2: try {
        var v: Leyline_V1_SampleTime?
        var hadOneofValue = false
        if let current = self.position {
          hadOneofValue = true
          if case .atSample(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.position = .atSample(v)
        }
      }()
      case 3: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.position != nil {try decoder.handleConflictingOneOf()}
          self.position = .atHostTimeNs(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.position {
    case .live?: try {
      guard case .live(let v)? = self.position else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .atSample?: try {
      guard case .atSample(let v)? = self.position else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .atHostTimeNs?: try {
      guard case .atHostTimeNs(let v)? = self.position else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_StreamPosition, rhs: Leyline_V1_StreamPosition) -> Bool {
    if lhs.position != rhs.position {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ErrorDetail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ErrorDetail"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}target\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.target) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.target.isEmpty {
      try visitor.visitSingularStringField(value: self.target, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ErrorDetail, rhs: Leyline_V1_ErrorDetail) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.target != rhs.target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_GainState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GainState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}element\0\u{1}db\0\u{1}auto\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.element) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.db) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.auto) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.element.isEmpty {
      try visitor.visitSingularStringField(value: self.element, fieldNumber: 1)
    }
    if self.db.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.db, fieldNumber: 2)
    }
    if self.auto != false {
      try visitor.visitSingularBoolField(value: self.auto, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_GainState, rhs: Leyline_V1_GainState) -> Bool {
    if lhs.element != rhs.element {return false}
    if lhs.db != rhs.db {return false}
    if lhs.auto != rhs.auto {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
