// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/decode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-License-Identifier: Apache-2.0

/// leyline.v1 — decoders
/// Turning demodulated signal into typed records (docs/design/decoders.md). A decoder is an
/// out-of-process plugin the daemon spawns: it reads the bulk plane's own frames on stdin and
/// writes DecodeRecords on stdout, both varint-delimited (protobuf's "delimited" convention). The
/// daemon owns the radio, the channel and the job; the plugin sees samples and nothing else.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Leyline_V1_GainPolicy: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// whatever the radio is set to; a capture the job borrows keeps its owner's gain
  case gainLeave // = 1

  /// ask for AGC on a capture the job creates
  case gainAuto // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .gainLeave
    case 2: self = .gainAuto
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .gainLeave: return 1
    case .gainAuto: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_GainPolicy] = [
    .unspecified,
    .gainLeave,
    .gainAuto,
  ]

}

public nonisolated enum Leyline_V1_InputMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case continuous // = 1
  case slotAligned // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .continuous
    case 2: self = .slotAligned
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .continuous: return 1
    case .slotAligned: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_InputMode] = [
    .unspecified,
    .continuous,
    .slotAligned,
  ]

}

public nonisolated enum Leyline_V1_OutputShape: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case shapeRecords // = 1
  case shapeEntities // = 2
  case shapeRegistry // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .shapeRecords
    case 2: self = .shapeEntities
    case 3: self = .shapeRegistry
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .shapeRecords: return 1
    case .shapeEntities: return 2
    case .shapeRegistry: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_OutputShape] = [
    .unspecified,
    .shapeRecords,
    .shapeEntities,
    .shapeRegistry,
  ]

}

public nonisolated enum Leyline_V1_FieldType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case text // = 1
  case integer // = 2
  case number // = 3
  case flag // = 4
  case data // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .text
    case 2: self = .integer
    case 3: self = .number
    case 4: self = .flag
    case 5: self = .data
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .text: return 1
    case .integer: return 2
    case .number: return 3
    case .flag: return 4
    case .data: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_FieldType] = [
    .unspecified,
    .text,
    .integer,
    .number,
    .flag,
    .data,
  ]

}

public nonisolated enum Leyline_V1_PredicateOp: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case predEq // = 1
  case predNe // = 2
  case predLt // = 3
  case predLte // = 4
  case predGt // = 5
  case predGte // = 6
  case predIn // = 7
  case predNotIn // = 8

  /// The field is a delimited list (a SAME alert's FIPS county codes) and one of `values` is in it.
  case predContains // = 9

  /// The field is present and non-empty; `values` is ignored.
  case predExists // = 10
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .predEq
    case 2: self = .predNe
    case 3: self = .predLt
    case 4: self = .predLte
    case 5: self = .predGt
    case 6: self = .predGte
    case 7: self = .predIn
    case 8: self = .predNotIn
    case 9: self = .predContains
    case 10: self = .predExists
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .predEq: return 1
    case .predNe: return 2
    case .predLt: return 3
    case .predLte: return 4
    case .predGt: return 5
    case .predGte: return 6
    case .predIn: return 7
    case .predNotIn: return 8
    case .predContains: return 9
    case .predExists: return 10
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_PredicateOp] = [
    .unspecified,
    .predEq,
    .predNe,
    .predLt,
    .predLte,
    .predGt,
    .predGte,
    .predIn,
    .predNotIn,
    .predContains,
    .predExists,
  ]

}

public nonisolated struct Leyline_V1_DecoderManifest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// registry name and DecodeRecord.protocol: "aprs", "adsb", "rtl433"
  public var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var version: String {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  /// upstream project, when the plugin wraps or derives from one
  public var attribution: String {
    get {_storage._attribution}
    set {_uniqueStorage()._attribution = newValue}
  }

  /// SPDX identifier of the plugin itself
  public var license: String {
    get {_storage._license}
    set {_uniqueStorage()._license = newValue}
  }

  /// What to tune. This is what makes `ley decode aprs` need no parameters.
  public var recipe: Leyline_V1_DecoderRecipe {
    get {_storage._recipe ?? Leyline_V1_DecoderRecipe()}
    set {_uniqueStorage()._recipe = newValue}
  }
  /// Returns true if `recipe` has been explicitly set.
  public var hasRecipe: Bool {_storage._recipe != nil}
  /// Clears the value of `recipe`. Subsequent reads from it will return its default value.
  public mutating func clearRecipe() {_uniqueStorage()._recipe = nil}

  public var input: Leyline_V1_DecoderInput {
    get {_storage._input ?? Leyline_V1_DecoderInput()}
    set {_uniqueStorage()._input = newValue}
  }
  /// Returns true if `input` has been explicitly set.
  public var hasInput: Bool {_storage._input != nil}
  /// Clears the value of `input`. Subsequent reads from it will return its default value.
  public mutating func clearInput() {_uniqueStorage()._input = nil}

  public var outputs: [Leyline_V1_OutputShape] {
    get {_storage._outputs}
    set {_uniqueStorage()._outputs = newValue}
  }

  /// Seconds without a record before a client-side entity table ages a device out. 0 = never.
  public var entitySilenceS: UInt32 {
    get {_storage._entitySilenceS}
    set {_uniqueStorage()._entitySilenceS = newValue}
  }

  /// Advisory: names, types and units of the `fields` this decoder emits, for display and query
  /// planning. A field not listed here still passes through.
  public var fields: [Leyline_V1_FieldHint] {
    get {_storage._fields}
    set {_uniqueStorage()._fields = newValue}
  }

  public var supportsMultiChannel: Bool {
    get {_storage._supportsMultiChannel}
    set {_uniqueStorage()._supportsMultiChannel = newValue}
  }

  public var needsDedicatedCapture: Bool {
    get {_storage._needsDedicatedCapture}
    set {_uniqueStorage()._needsDedicatedCapture = newValue}
  }

  public var statefulPredicatesAvailable: Bool {
    get {_storage._statefulPredicatesAvailable}
    set {_uniqueStorage()._statefulPredicatesAvailable = newValue}
  }

  /// The program to spawn: a path relative to the manifest's directory, or a name on PATH.
  public var executable: String {
    get {_storage._executable}
    set {_uniqueStorage()._executable = newValue}
  }

  public var args: [String] {
    get {_storage._args}
    set {_uniqueStorage()._args = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Leyline_V1_DecoderRecipe: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Where the protocol lives. One entry for most; several for a protocol with regional
  /// allocations (APRS is 144.39 MHz in North America and 144.8 in Europe). The first is the
  /// default and DecodeConfig.frequency_hz picks another or overrides.
  public var frequenciesHz: [UInt64] = []

  /// 0 = the radio's default
  public var sampleRate: UInt64 = 0

  /// 0 = the mode's default
  public var bandwidthHz: UInt32 = 0

  public var mode: Leyline_V1_DemodMode = .unspecified

  public var gain: Leyline_V1_GainPolicy = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_DecoderInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mode: Leyline_V1_InputMode = .unspecified

  /// SLOT_ALIGNED only: the slot length and where slot boundaries sit relative to the epoch
  /// (FT8: 15000 ms, 0). The daemon buffers a whole slot, cut against the capture anchor, and
  /// delivers it as one frame. Not implemented in the first build: a manifest asking for it is
  /// listed by ListDecoders and refused by StartJob with UNIMPLEMENTED.
  public var slotMs: UInt32 = 0

  public var epochOffsetMs: Int64 = 0

  /// Which stage of the channel the plugin reads. TAP_DEMOD is the discriminator before
  /// de-emphasis and the limiter, which a data decoder usually prefers; TAP_AUDIO is what a
  /// listener hears and is the default.
  public var tap: Leyline_V1_AudioTap = .tapAudio

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_FieldHint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var type: Leyline_V1_FieldType = .unspecified

  /// "m", "km/h", "degC", "hPa"; empty for none
  public var unit: String = String()

  public var description_p: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One thing a transmitter said. Promoted fields are present or empty, never invented; everything
/// protocol-specific is in `fields`. Records are immutable: a correction is a new record.
public nonisolated struct Leyline_V1_DecodeRecord: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// rec_<ulid>, assigned by the daemon
  public var recordID: String {
    get {_storage._recordID}
    set {_uniqueStorage()._recordID = newValue}
  }

  /// the manifest's name
  public var `protocol`: String {
    get {_storage._protocol}
    set {_uniqueStorage()._protocol = newValue}
  }

  /// When it was received, on the capture's timeline. The plugin stamps this from the frame it
  /// decoded the packet in, and wall clock comes from the capture's anchor as everywhere else.
  public var time: Leyline_V1_SampleTime {
    get {_storage._time ?? Leyline_V1_SampleTime()}
    set {_uniqueStorage()._time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {_storage._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {_uniqueStorage()._time = nil}

  /// The transmitter as the protocol identifies it: an ICAO hex, an MMSI, "N0CALL-9",
  /// "Acurite-Tower/2937". Empty when the protocol has no identity concept.
  public var deviceID: String {
    get {_storage._deviceID}
    set {_uniqueStorage()._deviceID = newValue}
  }

  public var position: Leyline_V1_Position {
    get {_storage._position ?? Leyline_V1_Position()}
    set {_uniqueStorage()._position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {_storage._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {_uniqueStorage()._position = nil}

  /// Measured by the engine on the channel the packet arrived on, stamped by the daemon when the
  /// record reaches it; a plugin's own values here are overwritten. NaN when not measured.
  public var rssiDbfs: Double {
    get {_storage._rssiDbfs}
    set {_uniqueStorage()._rssiDbfs = newValue}
  }

  public var snrDb: Double {
    get {_storage._snrDb}
    set {_uniqueStorage()._snrDb = newValue}
  }

  /// Present when the record's meaning expires: a weather alert, a NOTAM. Absent for an
  /// instantaneous observation.
  public var validity: Leyline_V1_Validity {
    get {_storage._validity ?? Leyline_V1_Validity()}
    set {_uniqueStorage()._validity = newValue}
  }
  /// Returns true if `validity` has been explicitly set.
  public var hasValidity: Bool {_storage._validity != nil}
  /// Clears the value of `validity`. Subsequent reads from it will return its default value.
  public mutating func clearValidity() {_uniqueStorage()._validity = nil}

  public var fields: Dictionary<String,Leyline_V1_FieldValue> {
    get {_storage._fields}
    set {_uniqueStorage()._fields = newValue}
  }

  /// The payload as decoded, always kept, so a better decoder can reprocess it later. For APRS
  /// this is the AX.25 frame without flags or FCS.
  public var raw: Data {
    get {_storage._raw}
    set {_uniqueStorage()._raw = newValue}
  }

  /// Set by the daemon: the job that produced it, the record's position in that job's stream
  /// (1-based, contiguous per job, so a hole is a drop), and the channel it was decoded on.
  public var jobID: String {
    get {_storage._jobID}
    set {_uniqueStorage()._jobID = newValue}
  }

  public var seq: UInt64 {
    get {_storage._seq}
    set {_uniqueStorage()._seq = newValue}
  }

  public var channelID: String {
    get {_storage._channelID}
    set {_uniqueStorage()._channelID = newValue}
  }

  /// The protocol's own record type, when it has more than one: APRS says "position", "weather",
  /// "telemetry", "message", "status", "object". Empty for a protocol with one kind of record.
  public var kind: String {
    get {_storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Leyline_V1_Position: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// degrees, north positive
  public var latitude: Double = 0

  /// degrees, east positive
  public var longitude: Double = 0

  public var altitudeM: Double {
    get {_altitudeM ?? 0}
    set {_altitudeM = newValue}
  }
  /// Returns true if `altitudeM` has been explicitly set.
  public var hasAltitudeM: Bool {self._altitudeM != nil}
  /// Clears the value of `altitudeM`. Subsequent reads from it will return its default value.
  public mutating func clearAltitudeM() {self._altitudeM = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _altitudeM: Double? = nil
}

/// A window on the wall clock, because that is how protocols state one ("until 14:30 UTC"). It is
/// the transmitter's claim about time, not a frame timestamp, so it does not go through the anchor.
public nonisolated struct Leyline_V1_Validity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// CLOCK_REALTIME; 0 = from receipt
  public var startNs: Int64 = 0

  public var endNs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_FieldValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Leyline_V1_FieldValue.OneOf_Value? = nil

  public var text: String {
    get {
      if case .text(let v)? = value {return v}
      return String()
    }
    set {value = .text(newValue)}
  }

  public var integer: Int64 {
    get {
      if case .integer(let v)? = value {return v}
      return 0
    }
    set {value = .integer(newValue)}
  }

  public var number: Double {
    get {
      if case .number(let v)? = value {return v}
      return 0
    }
    set {value = .number(newValue)}
  }

  public var flag: Bool {
    get {
      if case .flag(let v)? = value {return v}
      return false
    }
    set {value = .flag(newValue)}
  }

  public var data: Data {
    get {
      if case .data(let v)? = value {return v}
      return Data()
    }
    set {value = .data(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Value: Equatable, Sendable {
    case text(String)
    case integer(Int64)
    case number(Double)
    case flag(Bool)
    case data(Data)

  }

  public init() {}
}

/// Run a decoder on its recipe. The allocator finds a capture that covers the frequency, or makes
/// one on an idle radio, or declines naming who has it (docs/design/decoders.md, "Decisions").
public nonisolated struct Leyline_V1_DecodeConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// a manifest name from ListDecoders
  public var decoder: String = String()

  /// 0 = the recipe's first frequency
  public var frequencyHz: UInt64 = 0

  /// empty = the daemon picks
  public var deviceID: String = String()

  /// retune a capture somebody is using; off by default
  public var takeOver: Bool = false

  /// Persistence follows intent: without this the job belongs to the client that started it and
  /// its records exist only on the live stream. With it the job outlives the client and its
  /// records are the resource ley://records/<job_id>.
  public var keep: Bool = false

  /// A daemon-side filter on records before delivery (docs/design/decoders.md, "Predicates and
  /// delivery"). Unset matches everything, which is what `ley decode` uses; `ley watch` sets one so
  /// a trigger fires with no client connected. Stateless: every clause is judged on one record.
  public var predicate: Leyline_V1_Predicate {
    get {_predicate ?? Leyline_V1_Predicate()}
    set {_predicate = newValue}
  }
  /// Returns true if `predicate` has been explicitly set.
  public var hasPredicate: Bool {self._predicate != nil}
  /// Clears the value of `predicate`. Subsequent reads from it will return its default value.
  public mutating func clearPredicate() {self._predicate = nil}

  /// Where a record that passes the predicate goes when it fires: a notification, a webhook, a shell
  /// hook. A triggered alert is a channel output going somewhere, and "somewhere" is now a notifier
  /// (docs/design/decoders.md); it is not a parallel delivery path, it rides the same records.
  public var notify: Leyline_V1_NotifyTarget {
    get {_notify ?? Leyline_V1_NotifyTarget()}
    set {_notify = newValue}
  }
  /// Returns true if `notify` has been explicitly set.
  public var hasNotify: Bool {self._notify != nil}
  /// Clears the value of `notify`. Subsequent reads from it will return its default value.
  public mutating func clearNotify() {self._notify = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _predicate: Leyline_V1_Predicate? = nil
  fileprivate var _notify: Leyline_V1_NotifyTarget? = nil
}

/// A stateless record filter. `all` clauses must match (AND); an empty predicate matches every
/// record. Stateful predicates -- ones that need track history -- are a later, opt-in aggregator and
/// are not this message.
public nonisolated struct Leyline_V1_Predicate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var all: [Leyline_V1_Clause] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_Clause: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var test: Leyline_V1_Clause.OneOf_Test? = nil

  public var field: Leyline_V1_FieldTest {
    get {
      if case .field(let v)? = test {return v}
      return Leyline_V1_FieldTest()
    }
    set {test = .field(newValue)}
  }

  public var geo: Leyline_V1_GeoTest {
    get {
      if case .geo(let v)? = test {return v}
      return Leyline_V1_GeoTest()
    }
    set {test = .geo(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Test: Equatable, Sendable {
    case field(Leyline_V1_FieldTest)
    case geo(Leyline_V1_GeoTest)

  }

  public init() {}
}

/// A test on one field: a promoted name (`device_id`, `kind`, `protocol`) or a `fields` key. Numbers
/// compare numerically, everything else as text; `values` holds one value for the scalar operators
/// and many for IN / NOT_IN.
public nonisolated struct Leyline_V1_FieldTest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var field: String = String()

  public var op: Leyline_V1_PredicateOp = .unspecified

  public var values: [Leyline_V1_FieldValue] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A record whose `position` is within `radius_m` of `center`. A record with no position never
/// matches.
public nonisolated struct Leyline_V1_GeoTest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var center: Leyline_V1_Position {
    get {_center ?? Leyline_V1_Position()}
    set {_center = newValue}
  }
  /// Returns true if `center` has been explicitly set.
  public var hasCenter: Bool {self._center != nil}
  /// Clears the value of `center`. Subsequent reads from it will return its default value.
  public mutating func clearCenter() {self._center = nil}

  public var radiusM: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _center: Leyline_V1_Position? = nil
}

/// Where a matching record goes. External delivery happens in the daemon, so a webhook or a shell
/// hook is the daemon reaching out, never a client relaying; a client that wants records subscribes.
public nonisolated struct Leyline_V1_NotifyTarget: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var target: Leyline_V1_NotifyTarget.OneOf_Target? = nil

  /// HTTP POST of the record as proto3 JSON to this URL.
  public var webhook: String {
    get {
      if case .webhook(let v)? = target {return v}
      return String()
    }
    set {target = .webhook(newValue)}
  }

  /// A command line run with the record's proto3 JSON on stdin and its promoted fields in the
  /// environment (LEYLINE_PROTOCOL, LEYLINE_DEVICE_ID, LEYLINE_KIND, ...). The daemon runs it,
  /// so it runs with the daemon's privileges: the socket already trusts the local user.
  public var shell: String {
    get {
      if case .shell(let v)? = target {return v}
      return String()
    }
    set {target = .shell(newValue)}
  }

  /// A macOS user notification on the machine the daemon runs on. UNIMPLEMENTED off macOS, where
  /// the daemon logs the record instead so a headless run is not silent.
  public var macosNotification: Bool {
    get {
      if case .macosNotification(let v)? = target {return v}
      return false
    }
    set {target = .macosNotification(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Target: Equatable, Sendable {
    /// HTTP POST of the record as proto3 JSON to this URL.
    case webhook(String)
    /// A command line run with the record's proto3 JSON on stdin and its promoted fields in the
    /// environment (LEYLINE_PROTOCOL, LEYLINE_DEVICE_ID, LEYLINE_KIND, ...). The daemon runs it,
    /// so it runs with the daemon's privileges: the socket already trusts the local user.
    case shell(String)
    /// A macOS user notification on the machine the daemon runs on. UNIMPLEMENTED off macOS, where
    /// the daemon logs the record instead so a headless run is not silent.
    case macosNotification(Bool)

  }

  public init() {}
}

public nonisolated struct Leyline_V1_ListDecodersRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_ListDecodersResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var decoders: [Leyline_V1_DecoderManifest] = []

  /// Where the daemon looked, in order, and the retention it applies to kept records.
  public var searchPath: [String] = []

  public var storePath: String = String()

  public var storeCapBytes: UInt64 = 0

  public var storeAgeDays: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_RecordSubscription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scope: Leyline_V1_RecordSubscription.OneOf_Scope? = nil

  public var all: Bool {
    get {
      if case .all(let v)? = scope {return v}
      return false
    }
    set {scope = .all(newValue)}
  }

  public var jobID: String {
    get {
      if case .jobID(let v)? = scope {return v}
      return String()
    }
    set {scope = .jobID(newValue)}
  }

  public var `protocol`: String {
    get {
      if case .protocol(let v)? = scope {return v}
      return String()
    }
    set {scope = .protocol(newValue)}
  }

  /// job_id scope only: replay retained records with seq > since_seq before going live (0 = from
  /// the start of what is retained). Unset = live only.
  public var sinceSeq: UInt64 {
    get {_sinceSeq ?? 0}
    set {_sinceSeq = newValue}
  }
  /// Returns true if `sinceSeq` has been explicitly set.
  public var hasSinceSeq: Bool {self._sinceSeq != nil}
  /// Clears the value of `sinceSeq`. Subsequent reads from it will return its default value.
  public mutating func clearSinceSeq() {self._sinceSeq = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Scope: Equatable, Sendable {
    case all(Bool)
    case jobID(String)
    case `protocol`(String)

  }

  public init() {}

  fileprivate var _sinceSeq: UInt64? = nil
}

public nonisolated struct Leyline_V1_RecordQuery: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// empty = any
  public var `protocol`: String = String()

  /// empty = every kept job
  public var jobID: String = String()

  /// exact match; empty = any
  public var deviceID: String = String()

  /// empty = any
  public var kind: String = String()

  /// Wall clock bounds, answered through each job's stored anchors. 0 = unbounded.
  public var sinceNs: Int64 = 0

  public var untilNs: Int64 = 0

  /// Records with a position within radius_m of `near`. Absent = no spatial filter.
  public var near: Leyline_V1_Position {
    get {_near ?? Leyline_V1_Position()}
    set {_near = newValue}
  }
  /// Returns true if `near` has been explicitly set.
  public var hasNear: Bool {self._near != nil}
  /// Clears the value of `near`. Subsequent reads from it will return its default value.
  public mutating func clearNear() {self._near = nil}

  public var radiusM: Double = 0

  /// Only records whose validity window contains now.
  public var inEffect: Bool = false

  /// Exact-value field filters, all of which must match.
  public var fields: [Leyline_V1_FieldMatch] = []

  /// 0 = the daemon's default (1000); the page says if it was cut
  public var limit: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _near: Leyline_V1_Position? = nil
}

public nonisolated struct Leyline_V1_FieldMatch: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var equals: Leyline_V1_FieldValue {
    get {_equals ?? Leyline_V1_FieldValue()}
    set {_equals = newValue}
  }
  /// Returns true if `equals` has been explicitly set.
  public var hasEquals: Bool {self._equals != nil}
  /// Clears the value of `equals`. Subsequent reads from it will return its default value.
  public mutating func clearEquals() {self._equals = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _equals: Leyline_V1_FieldValue? = nil
}

public nonisolated struct Leyline_V1_RecordPage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var records: [Leyline_V1_DecodeRecord] = []

  /// The anchor of every capture the records name, so a client turns `time` into wall clock the
  /// way it does for a live capture. A capture that re-anchored while a job ran appears once per
  /// anchor, and the one that applies is the newest whose sample_index is not past the record's.
  public var anchors: [Leyline_V1_RecordAnchor] = []

  public var truncated: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Leyline_V1_RecordAnchor: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var anchor: Leyline_V1_CaptureAnchor {
    get {_anchor ?? Leyline_V1_CaptureAnchor()}
    set {_anchor = newValue}
  }
  /// Returns true if `anchor` has been explicitly set.
  public var hasAnchor: Bool {self._anchor != nil}
  /// Clears the value of `anchor`. Subsequent reads from it will return its default value.
  public mutating func clearAnchor() {self._anchor = nil}

  /// the anchor applies from this sample index on its capture
  public var fromSample: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _anchor: Leyline_V1_CaptureAnchor? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "leyline.v1"

nonisolated extension Leyline_V1_GainPolicy: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GAIN_POLICY_UNSPECIFIED\0\u{1}GAIN_LEAVE\0\u{1}GAIN_AUTO\0")
}

nonisolated extension Leyline_V1_InputMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INPUT_MODE_UNSPECIFIED\0\u{1}CONTINUOUS\0\u{1}SLOT_ALIGNED\0")
}

nonisolated extension Leyline_V1_OutputShape: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OUTPUT_SHAPE_UNSPECIFIED\0\u{1}SHAPE_RECORDS\0\u{1}SHAPE_ENTITIES\0\u{1}SHAPE_REGISTRY\0")
}

nonisolated extension Leyline_V1_FieldType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FIELD_TYPE_UNSPECIFIED\0\u{1}TEXT\0\u{1}INTEGER\0\u{1}NUMBER\0\u{1}FLAG\0\u{1}DATA\0")
}

nonisolated extension Leyline_V1_PredicateOp: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PREDICATE_OP_UNSPECIFIED\0\u{1}PRED_EQ\0\u{1}PRED_NE\0\u{1}PRED_LT\0\u{1}PRED_LTE\0\u{1}PRED_GT\0\u{1}PRED_GTE\0\u{1}PRED_IN\0\u{1}PRED_NOT_IN\0\u{1}PRED_CONTAINS\0\u{1}PRED_EXISTS\0")
}

nonisolated extension Leyline_V1_DecoderManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DecoderManifest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{1}description\0\u{1}attribution\0\u{1}license\0\u{1}recipe\0\u{1}input\0\u{1}outputs\0\u{3}entity_silence_s\0\u{1}fields\0\u{3}supports_multi_channel\0\u{3}needs_dedicated_capture\0\u{3}stateful_predicates_available\0\u{1}executable\0\u{1}args\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _version: String = String()
    var _description_p: String = String()
    var _attribution: String = String()
    var _license: String = String()
    var _recipe: Leyline_V1_DecoderRecipe? = nil
    var _input: Leyline_V1_DecoderInput? = nil
    var _outputs: [Leyline_V1_OutputShape] = []
    var _entitySilenceS: UInt32 = 0
    var _fields: [Leyline_V1_FieldHint] = []
    var _supportsMultiChannel: Bool = false
    var _needsDedicatedCapture: Bool = false
    var _statefulPredicatesAvailable: Bool = false
    var _executable: String = String()
    var _args: [String] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _version = source._version
      _description_p = source._description_p
      _attribution = source._attribution
      _license = source._license
      _recipe = source._recipe
      _input = source._input
      _outputs = source._outputs
      _entitySilenceS = source._entitySilenceS
      _fields = source._fields
      _supportsMultiChannel = source._supportsMultiChannel
      _needsDedicatedCapture = source._needsDedicatedCapture
      _statefulPredicatesAvailable = source._statefulPredicatesAvailable
      _executable = source._executable
      _args = source._args
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._version) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._attribution) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._license) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._recipe) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._input) }()
        case 8: try { try decoder.decodeRepeatedEnumField(value: &_storage._outputs) }()
        case 9: try { try decoder.decodeSingularUInt32Field(value: &_storage._entitySilenceS) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._fields) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._supportsMultiChannel) }()
        case 12: try { try decoder.decodeSingularBoolField(value: &_storage._needsDedicatedCapture) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._statefulPredicatesAvailable) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._executable) }()
        case 15: try { try decoder.decodeRepeatedStringField(value: &_storage._args) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 2)
      }
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 3)
      }
      if !_storage._attribution.isEmpty {
        try visitor.visitSingularStringField(value: _storage._attribution, fieldNumber: 4)
      }
      if !_storage._license.isEmpty {
        try visitor.visitSingularStringField(value: _storage._license, fieldNumber: 5)
      }
      try { if let v = _storage._recipe {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._input {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._outputs.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._outputs, fieldNumber: 8)
      }
      if _storage._entitySilenceS != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._entitySilenceS, fieldNumber: 9)
      }
      if !_storage._fields.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._fields, fieldNumber: 10)
      }
      if _storage._supportsMultiChannel != false {
        try visitor.visitSingularBoolField(value: _storage._supportsMultiChannel, fieldNumber: 11)
      }
      if _storage._needsDedicatedCapture != false {
        try visitor.visitSingularBoolField(value: _storage._needsDedicatedCapture, fieldNumber: 12)
      }
      if _storage._statefulPredicatesAvailable != false {
        try visitor.visitSingularBoolField(value: _storage._statefulPredicatesAvailable, fieldNumber: 13)
      }
      if !_storage._executable.isEmpty {
        try visitor.visitSingularStringField(value: _storage._executable, fieldNumber: 14)
      }
      if !_storage._args.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._args, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_DecoderManifest, rhs: Leyline_V1_DecoderManifest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._version != rhs_storage._version {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._attribution != rhs_storage._attribution {return false}
        if _storage._license != rhs_storage._license {return false}
        if _storage._recipe != rhs_storage._recipe {return false}
        if _storage._input != rhs_storage._input {return false}
        if _storage._outputs != rhs_storage._outputs {return false}
        if _storage._entitySilenceS != rhs_storage._entitySilenceS {return false}
        if _storage._fields != rhs_storage._fields {return false}
        if _storage._supportsMultiChannel != rhs_storage._supportsMultiChannel {return false}
        if _storage._needsDedicatedCapture != rhs_storage._needsDedicatedCapture {return false}
        if _storage._statefulPredicatesAvailable != rhs_storage._statefulPredicatesAvailable {return false}
        if _storage._executable != rhs_storage._executable {return false}
        if _storage._args != rhs_storage._args {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_DecoderRecipe: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DecoderRecipe"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}frequencies_hz\0\u{3}sample_rate\0\u{3}bandwidth_hz\0\u{1}mode\0\u{1}gain\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedUInt64Field(value: &self.frequenciesHz) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.sampleRate) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.bandwidthHz) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.gain) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.frequenciesHz.isEmpty {
      try visitor.visitPackedUInt64Field(value: self.frequenciesHz, fieldNumber: 1)
    }
    if self.sampleRate != 0 {
      try visitor.visitSingularUInt64Field(value: self.sampleRate, fieldNumber: 2)
    }
    if self.bandwidthHz != 0 {
      try visitor.visitSingularUInt32Field(value: self.bandwidthHz, fieldNumber: 3)
    }
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 4)
    }
    if self.gain != .unspecified {
      try visitor.visitSingularEnumField(value: self.gain, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_DecoderRecipe, rhs: Leyline_V1_DecoderRecipe) -> Bool {
    if lhs.frequenciesHz != rhs.frequenciesHz {return false}
    if lhs.sampleRate != rhs.sampleRate {return false}
    if lhs.bandwidthHz != rhs.bandwidthHz {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.gain != rhs.gain {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_DecoderInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DecoderInput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0\u{3}slot_ms\0\u{3}epoch_offset_ms\0\u{1}tap\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.slotMs) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.epochOffsetMs) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.tap) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 1)
    }
    if self.slotMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.slotMs, fieldNumber: 2)
    }
    if self.epochOffsetMs != 0 {
      try visitor.visitSingularInt64Field(value: self.epochOffsetMs, fieldNumber: 3)
    }
    if self.tap != .tapAudio {
      try visitor.visitSingularEnumField(value: self.tap, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_DecoderInput, rhs: Leyline_V1_DecoderInput) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.slotMs != rhs.slotMs {return false}
    if lhs.epochOffsetMs != rhs.epochOffsetMs {return false}
    if lhs.tap != rhs.tap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FieldHint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldHint"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}type\0\u{1}unit\0\u{1}description\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.unit) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    if !self.unit.isEmpty {
      try visitor.visitSingularStringField(value: self.unit, fieldNumber: 3)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FieldHint, rhs: Leyline_V1_FieldHint) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_DecodeRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DecodeRecord"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}record_id\0\u{1}protocol\0\u{1}time\0\u{3}device_id\0\u{1}position\0\u{3}rssi_dbfs\0\u{3}snr_db\0\u{1}validity\0\u{1}fields\0\u{1}raw\0\u{3}job_id\0\u{1}seq\0\u{3}channel_id\0\u{1}kind\0")

  fileprivate class _StorageClass {
    var _recordID: String = String()
    var _protocol: String = String()
    var _time: Leyline_V1_SampleTime? = nil
    var _deviceID: String = String()
    var _position: Leyline_V1_Position? = nil
    var _rssiDbfs: Double = 0
    var _snrDb: Double = 0
    var _validity: Leyline_V1_Validity? = nil
    var _fields: Dictionary<String,Leyline_V1_FieldValue> = [:]
    var _raw: Data = Data()
    var _jobID: String = String()
    var _seq: UInt64 = 0
    var _channelID: String = String()
    var _kind: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _recordID = source._recordID
      _protocol = source._protocol
      _time = source._time
      _deviceID = source._deviceID
      _position = source._position
      _rssiDbfs = source._rssiDbfs
      _snrDb = source._snrDb
      _validity = source._validity
      _fields = source._fields
      _raw = source._raw
      _jobID = source._jobID
      _seq = source._seq
      _channelID = source._channelID
      _kind = source._kind
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._recordID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._protocol) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._time) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._deviceID) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._position) }()
        case 6: try { try decoder.decodeSingularDoubleField(value: &_storage._rssiDbfs) }()
        case 7: try { try decoder.decodeSingularDoubleField(value: &_storage._snrDb) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._validity) }()
        case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Leyline_V1_FieldValue>.self, value: &_storage._fields) }()
        case 10: try { try decoder.decodeSingularBytesField(value: &_storage._raw) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._jobID) }()
        case 12: try { try decoder.decodeSingularUInt64Field(value: &_storage._seq) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._channelID) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._kind) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._recordID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._recordID, fieldNumber: 1)
      }
      if !_storage._protocol.isEmpty {
        try visitor.visitSingularStringField(value: _storage._protocol, fieldNumber: 2)
      }
      try { if let v = _storage._time {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._deviceID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deviceID, fieldNumber: 4)
      }
      try { if let v = _storage._position {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._rssiDbfs.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._rssiDbfs, fieldNumber: 6)
      }
      if _storage._snrDb.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._snrDb, fieldNumber: 7)
      }
      try { if let v = _storage._validity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      if !_storage._fields.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Leyline_V1_FieldValue>.self, value: _storage._fields, fieldNumber: 9)
      }
      if !_storage._raw.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._raw, fieldNumber: 10)
      }
      if !_storage._jobID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._jobID, fieldNumber: 11)
      }
      if _storage._seq != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._seq, fieldNumber: 12)
      }
      if !_storage._channelID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._channelID, fieldNumber: 13)
      }
      if !_storage._kind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._kind, fieldNumber: 14)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_DecodeRecord, rhs: Leyline_V1_DecodeRecord) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._recordID != rhs_storage._recordID {return false}
        if _storage._protocol != rhs_storage._protocol {return false}
        if _storage._time != rhs_storage._time {return false}
        if _storage._deviceID != rhs_storage._deviceID {return false}
        if _storage._position != rhs_storage._position {return false}
        if _storage._rssiDbfs != rhs_storage._rssiDbfs {return false}
        if _storage._snrDb != rhs_storage._snrDb {return false}
        if _storage._validity != rhs_storage._validity {return false}
        if _storage._fields != rhs_storage._fields {return false}
        if _storage._raw != rhs_storage._raw {return false}
        if _storage._jobID != rhs_storage._jobID {return false}
        if _storage._seq != rhs_storage._seq {return false}
        if _storage._channelID != rhs_storage._channelID {return false}
        if _storage._kind != rhs_storage._kind {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Position: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Position"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}latitude\0\u{1}longitude\0\u{3}altitude_m\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.latitude) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.longitude) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._altitudeM) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.latitude.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.latitude, fieldNumber: 1)
    }
    if self.longitude.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.longitude, fieldNumber: 2)
    }
    try { if let v = self._altitudeM {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Position, rhs: Leyline_V1_Position) -> Bool {
    if lhs.latitude != rhs.latitude {return false}
    if lhs.longitude != rhs.longitude {return false}
    if lhs._altitudeM != rhs._altitudeM {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Validity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Validity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_ns\0\u{3}end_ns\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startNs) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.endNs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startNs != 0 {
      try visitor.visitSingularInt64Field(value: self.startNs, fieldNumber: 1)
    }
    if self.endNs != 0 {
      try visitor.visitSingularInt64Field(value: self.endNs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Validity, rhs: Leyline_V1_Validity) -> Bool {
    if lhs.startNs != rhs.startNs {return false}
    if lhs.endNs != rhs.endNs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FieldValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldValue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}integer\0\u{1}number\0\u{1}flag\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .text(v)
        }
      }()
      case 2: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .integer(v)
        }
      }()
      case 3: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .number(v)
        }
      }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .flag(v)
        }
      }()
      case 5: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .data(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .text?: try {
      guard case .text(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .integer?: try {
      guard case .integer(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    }()
    case .number?: try {
      guard case .number(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    }()
    case .flag?: try {
      guard case .flag(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case .data?: try {
      guard case .data(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FieldValue, rhs: Leyline_V1_FieldValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_DecodeConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DecodeConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}decoder\0\u{3}frequency_hz\0\u{3}device_id\0\u{3}take_over\0\u{1}keep\0\u{1}predicate\0\u{1}notify\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.decoder) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.frequencyHz) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.takeOver) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.keep) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._predicate) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._notify) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.decoder.isEmpty {
      try visitor.visitSingularStringField(value: self.decoder, fieldNumber: 1)
    }
    if self.frequencyHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.frequencyHz, fieldNumber: 2)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 3)
    }
    if self.takeOver != false {
      try visitor.visitSingularBoolField(value: self.takeOver, fieldNumber: 4)
    }
    if self.keep != false {
      try visitor.visitSingularBoolField(value: self.keep, fieldNumber: 5)
    }
    try { if let v = self._predicate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._notify {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_DecodeConfig, rhs: Leyline_V1_DecodeConfig) -> Bool {
    if lhs.decoder != rhs.decoder {return false}
    if lhs.frequencyHz != rhs.frequencyHz {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.takeOver != rhs.takeOver {return false}
    if lhs.keep != rhs.keep {return false}
    if lhs._predicate != rhs._predicate {return false}
    if lhs._notify != rhs._notify {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Predicate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Predicate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}all\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.all) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.all.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.all, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Predicate, rhs: Leyline_V1_Predicate) -> Bool {
    if lhs.all != rhs.all {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Clause: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Clause"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}field\0\u{1}geo\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Leyline_V1_FieldTest?
        var hadOneofValue = false
        if let current = self.test {
          hadOneofValue = true
          if case .field(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.test = .field(v)
        }
      }()
      case 2: try {
        var v: Leyline_V1_GeoTest?
        var hadOneofValue = false
        if let current = self.test {
          hadOneofValue = true
          if case .geo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.test = .geo(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.test {
    case .field?: try {
      guard case .field(let v)? = self.test else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .geo?: try {
      guard case .geo(let v)? = self.test else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Clause, rhs: Leyline_V1_Clause) -> Bool {
    if lhs.test != rhs.test {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FieldTest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldTest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}field\0\u{1}op\0\u{1}values\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.field) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.op) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.field.isEmpty {
      try visitor.visitSingularStringField(value: self.field, fieldNumber: 1)
    }
    if self.op != .unspecified {
      try visitor.visitSingularEnumField(value: self.op, fieldNumber: 2)
    }
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FieldTest, rhs: Leyline_V1_FieldTest) -> Bool {
    if lhs.field != rhs.field {return false}
    if lhs.op != rhs.op {return false}
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_GeoTest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GeoTest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}center\0\u{3}radius_m\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._center) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.radiusM) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._center {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.radiusM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.radiusM, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_GeoTest, rhs: Leyline_V1_GeoTest) -> Bool {
    if lhs._center != rhs._center {return false}
    if lhs.radiusM != rhs.radiusM {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_NotifyTarget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotifyTarget"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}webhook\0\u{1}shell\0\u{3}macos_notification\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.target != nil {try decoder.handleConflictingOneOf()}
          self.target = .webhook(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.target != nil {try decoder.handleConflictingOneOf()}
          self.target = .shell(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.target != nil {try decoder.handleConflictingOneOf()}
          self.target = .macosNotification(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.target {
    case .webhook?: try {
      guard case .webhook(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .shell?: try {
      guard case .shell(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .macosNotification?: try {
      guard case .macosNotification(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_NotifyTarget, rhs: Leyline_V1_NotifyTarget) -> Bool {
    if lhs.target != rhs.target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListDecodersRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListDecodersRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListDecodersRequest, rhs: Leyline_V1_ListDecodersRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_ListDecodersResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListDecodersResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}decoders\0\u{3}search_path\0\u{3}store_path\0\u{3}store_cap_bytes\0\u{3}store_age_days\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.decoders) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.searchPath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.storePath) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.storeCapBytes) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.storeAgeDays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.decoders.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.decoders, fieldNumber: 1)
    }
    if !self.searchPath.isEmpty {
      try visitor.visitRepeatedStringField(value: self.searchPath, fieldNumber: 2)
    }
    if !self.storePath.isEmpty {
      try visitor.visitSingularStringField(value: self.storePath, fieldNumber: 3)
    }
    if self.storeCapBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.storeCapBytes, fieldNumber: 4)
    }
    if self.storeAgeDays != 0 {
      try visitor.visitSingularUInt32Field(value: self.storeAgeDays, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_ListDecodersResponse, rhs: Leyline_V1_ListDecodersResponse) -> Bool {
    if lhs.decoders != rhs.decoders {return false}
    if lhs.searchPath != rhs.searchPath {return false}
    if lhs.storePath != rhs.storePath {return false}
    if lhs.storeCapBytes != rhs.storeCapBytes {return false}
    if lhs.storeAgeDays != rhs.storeAgeDays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_RecordSubscription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordSubscription"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}all\0\u{3}job_id\0\u{1}protocol\0\u{3}since_seq\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .all(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .jobID(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .protocol(v)
        }
      }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self._sinceSeq) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.scope {
    case .all?: try {
      guard case .all(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .jobID?: try {
      guard case .jobID(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .protocol?: try {
      guard case .protocol(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try { if let v = self._sinceSeq {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_RecordSubscription, rhs: Leyline_V1_RecordSubscription) -> Bool {
    if lhs.scope != rhs.scope {return false}
    if lhs._sinceSeq != rhs._sinceSeq {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_RecordQuery: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordQuery"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}protocol\0\u{3}job_id\0\u{3}device_id\0\u{1}kind\0\u{3}since_ns\0\u{3}until_ns\0\u{1}near\0\u{3}radius_m\0\u{3}in_effect\0\u{1}fields\0\u{1}limit\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.`protocol`) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.sinceNs) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.untilNs) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._near) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.radiusM) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.inEffect) }()
      case 10: try { try decoder.decodeRepeatedMessageField(value: &self.fields) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.limit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.`protocol`.isEmpty {
      try visitor.visitSingularStringField(value: self.`protocol`, fieldNumber: 1)
    }
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 2)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 3)
    }
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 4)
    }
    if self.sinceNs != 0 {
      try visitor.visitSingularInt64Field(value: self.sinceNs, fieldNumber: 5)
    }
    if self.untilNs != 0 {
      try visitor.visitSingularInt64Field(value: self.untilNs, fieldNumber: 6)
    }
    try { if let v = self._near {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if self.radiusM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.radiusM, fieldNumber: 8)
    }
    if self.inEffect != false {
      try visitor.visitSingularBoolField(value: self.inEffect, fieldNumber: 9)
    }
    if !self.fields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fields, fieldNumber: 10)
    }
    if self.limit != 0 {
      try visitor.visitSingularUInt32Field(value: self.limit, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_RecordQuery, rhs: Leyline_V1_RecordQuery) -> Bool {
    if lhs.`protocol` != rhs.`protocol` {return false}
    if lhs.jobID != rhs.jobID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.sinceNs != rhs.sinceNs {return false}
    if lhs.untilNs != rhs.untilNs {return false}
    if lhs._near != rhs._near {return false}
    if lhs.radiusM != rhs.radiusM {return false}
    if lhs.inEffect != rhs.inEffect {return false}
    if lhs.fields != rhs.fields {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_FieldMatch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldMatch"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}equals\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._equals) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._equals {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_FieldMatch, rhs: Leyline_V1_FieldMatch) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._equals != rhs._equals {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_RecordPage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordPage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}records\0\u{1}anchors\0\u{1}truncated\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.records) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.anchors) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.truncated) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.records.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.records, fieldNumber: 1)
    }
    if !self.anchors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.anchors, fieldNumber: 2)
    }
    if self.truncated != false {
      try visitor.visitSingularBoolField(value: self.truncated, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_RecordPage, rhs: Leyline_V1_RecordPage) -> Bool {
    if lhs.records != rhs.records {return false}
    if lhs.anchors != rhs.anchors {return false}
    if lhs.truncated != rhs.truncated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_RecordAnchor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RecordAnchor"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}anchor\0\u{3}from_sample\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._anchor) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.fromSample) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._anchor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.fromSample != 0 {
      try visitor.visitSingularUInt64Field(value: self.fromSample, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_RecordAnchor, rhs: Leyline_V1_RecordAnchor) -> Bool {
    if lhs._anchor != rhs._anchor {return false}
    if lhs.fromSample != rhs.fromSample {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
