// SPDX-License-Identifier: Apache-2.0

/// leyline.v1 — decoders
/// Turning demodulated signal into typed records (docs/design/decoders.md). A decoder is an
/// out-of-process plugin the daemon spawns: it reads the bulk plane's own frames on stdin and
/// writes DecodeRecords on stdout, both varint-delimited (protobuf's "delimited" convention). The
/// daemon owns the radio, the channel and the job; the plugin sees samples and nothing else.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/decode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - leyline.v1.Decoders

/// Namespace containing generated types for the "leyline.v1.Decoders" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Leyline_V1_Decoders: Sendable {
    /// Service descriptor for the "leyline.v1.Decoders" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Decoders")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "ListDecoders" metadata.
        public enum ListDecoders: Sendable {
            /// Request type for "ListDecoders".
            public typealias Input = Leyline_V1_ListDecodersRequest
            /// Response type for "ListDecoders".
            public typealias Output = Leyline_V1_ListDecodersResponse
            /// Descriptor for "ListDecoders".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Decoders"),
                method: "ListDecoders",
                type: .unary
            )
        }
        /// Namespace for "SubscribeRecords" metadata.
        public enum SubscribeRecords: Sendable {
            /// Request type for "SubscribeRecords".
            public typealias Input = Leyline_V1_RecordSubscription
            /// Response type for "SubscribeRecords".
            public typealias Output = Leyline_V1_DecodeRecord
            /// Descriptor for "SubscribeRecords".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Decoders"),
                method: "SubscribeRecords",
                type: .serverStreaming
            )
        }
        /// Namespace for "QueryRecords" metadata.
        public enum QueryRecords: Sendable {
            /// Request type for "QueryRecords".
            public typealias Input = Leyline_V1_RecordQuery
            /// Response type for "QueryRecords".
            public typealias Output = Leyline_V1_RecordPage
            /// Descriptor for "QueryRecords".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Decoders"),
                method: "QueryRecords",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "leyline.v1.Decoders" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ListDecoders.descriptor,
            SubscribeRecords.descriptor,
            QueryRecords.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "leyline.v1.Decoders" service.
    public static let leyline_v1_Decoders = GRPCCore.ServiceDescriptor(fullyQualifiedService: "leyline.v1.Decoders")
}

// MARK: leyline.v1.Decoders (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders {
    /// Streaming variant of the service protocol for the "leyline.v1.Decoders" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where the RPC expects only a single
    /// request or response message, you are responsible for ensuring your implementation
    /// maintains this invariant.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ListDecoders" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_ListDecodersRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_ListDecodersResponse` messages.
        func listDecoders(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_ListDecodersRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_ListDecodersResponse>

        /// Handle the "SubscribeRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
        /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_RecordSubscription` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_DecodeRecord` messages.
        func subscribeRecords(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_RecordSubscription>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_DecodeRecord>

        /// Handle the "QueryRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Records from the store: kept jobs only, newest first.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Leyline_V1_RecordQuery` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_RecordPage` messages.
        func queryRecords(
            request: GRPCCore.StreamingServerRequest<Leyline_V1_RecordQuery>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_RecordPage>
    }

    /// Service protocol for the "leyline.v1.Decoders" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Leyline_V1_Decoders.StreamingServiceProtocol {
        /// Handle the "ListDecoders" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_ListDecodersRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Leyline_V1_ListDecodersResponse` message.
        func listDecoders(
            request: GRPCCore.ServerRequest<Leyline_V1_ListDecodersRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Leyline_V1_ListDecodersResponse>

        /// Handle the "SubscribeRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
        /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordSubscription` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Leyline_V1_DecodeRecord` messages.
        func subscribeRecords(
            request: GRPCCore.ServerRequest<Leyline_V1_RecordSubscription>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_DecodeRecord>

        /// Handle the "QueryRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Records from the store: kept jobs only, newest first.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordQuery` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Leyline_V1_RecordPage` message.
        func queryRecords(
            request: GRPCCore.ServerRequest<Leyline_V1_RecordQuery>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Leyline_V1_RecordPage>
    }

    /// Simple service protocol for the "leyline.v1.Decoders" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Leyline_V1_Decoders.ServiceProtocol {
        /// Handle the "ListDecoders" method.
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_ListDecodersRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Leyline_V1_ListDecodersResponse` to respond with.
        func listDecoders(
            request: Leyline_V1_ListDecodersRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Leyline_V1_ListDecodersResponse

        /// Handle the "SubscribeRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
        /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_RecordSubscription` message.
        ///   - response: A response stream of `Leyline_V1_DecodeRecord` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func subscribeRecords(
            request: Leyline_V1_RecordSubscription,
            response: GRPCCore.RPCWriter<Leyline_V1_DecodeRecord>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "QueryRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Records from the store: kept jobs only, newest first.
        ///
        /// - Parameters:
        ///   - request: A `Leyline_V1_RecordQuery` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Leyline_V1_RecordPage` to respond with.
        func queryRecords(
            request: Leyline_V1_RecordQuery,
            context: GRPCCore.ServerContext
        ) async throws -> Leyline_V1_RecordPage
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Leyline_V1_Decoders.Method.ListDecoders.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_ListDecodersRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_ListDecodersResponse>(),
            handler: { request, context in
                try await self.listDecoders(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Leyline_V1_Decoders.Method.SubscribeRecords.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_RecordSubscription>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_DecodeRecord>(),
            handler: { request, context in
                try await self.subscribeRecords(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Leyline_V1_Decoders.Method.QueryRecords.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_RecordQuery>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_RecordPage>(),
            handler: { request, context in
                try await self.queryRecords(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders.ServiceProtocol {
    public func listDecoders(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_ListDecodersRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_ListDecodersResponse> {
        let response = try await self.listDecoders(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func subscribeRecords(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_RecordSubscription>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_DecodeRecord> {
        let response = try await self.subscribeRecords(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func queryRecords(
        request: GRPCCore.StreamingServerRequest<Leyline_V1_RecordQuery>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_RecordPage> {
        let response = try await self.queryRecords(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders.SimpleServiceProtocol {
    public func listDecoders(
        request: GRPCCore.ServerRequest<Leyline_V1_ListDecodersRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Leyline_V1_ListDecodersResponse> {
        return GRPCCore.ServerResponse<Leyline_V1_ListDecodersResponse>(
            message: try await self.listDecoders(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func subscribeRecords(
        request: GRPCCore.ServerRequest<Leyline_V1_RecordSubscription>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Leyline_V1_DecodeRecord> {
        return GRPCCore.StreamingServerResponse<Leyline_V1_DecodeRecord>(
            metadata: [:],
            producer: { writer in
                try await self.subscribeRecords(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func queryRecords(
        request: GRPCCore.ServerRequest<Leyline_V1_RecordQuery>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Leyline_V1_RecordPage> {
        return GRPCCore.ServerResponse<Leyline_V1_RecordPage>(
            message: try await self.queryRecords(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: leyline.v1.Decoders (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders {
    /// Generated client protocol for the "leyline.v1.Decoders" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "ListDecoders" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_ListDecodersRequest` message.
        ///   - serializer: A serializer for `Leyline_V1_ListDecodersRequest` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_ListDecodersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func listDecoders<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_ListDecodersRequest>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_ListDecodersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_ListDecodersResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_ListDecodersResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SubscribeRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
        /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordSubscription` message.
        ///   - serializer: A serializer for `Leyline_V1_RecordSubscription` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_DecodeRecord` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func subscribeRecords<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_RecordSubscription>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_RecordSubscription>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_DecodeRecord>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_DecodeRecord>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "QueryRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Records from the store: kept jobs only, newest first.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordQuery` message.
        ///   - serializer: A serializer for `Leyline_V1_RecordQuery` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_RecordPage` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func queryRecords<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_RecordQuery>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_RecordQuery>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_RecordPage>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_RecordPage>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "leyline.v1.Decoders" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ListDecoders" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_ListDecodersRequest` message.
        ///   - serializer: A serializer for `Leyline_V1_ListDecodersRequest` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_ListDecodersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func listDecoders<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_ListDecodersRequest>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_ListDecodersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_ListDecodersResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_ListDecodersResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Leyline_V1_Decoders.Method.ListDecoders.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SubscribeRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
        /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordSubscription` message.
        ///   - serializer: A serializer for `Leyline_V1_RecordSubscription` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_DecodeRecord` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func subscribeRecords<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_RecordSubscription>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_RecordSubscription>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_DecodeRecord>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_DecodeRecord>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Leyline_V1_Decoders.Method.SubscribeRecords.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "QueryRecords" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Records from the store: kept jobs only, newest first.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Leyline_V1_RecordQuery` message.
        ///   - serializer: A serializer for `Leyline_V1_RecordQuery` messages.
        ///   - deserializer: A deserializer for `Leyline_V1_RecordPage` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func queryRecords<Result>(
            request: GRPCCore.ClientRequest<Leyline_V1_RecordQuery>,
            serializer: some GRPCCore.MessageSerializer<Leyline_V1_RecordQuery>,
            deserializer: some GRPCCore.MessageDeserializer<Leyline_V1_RecordPage>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_RecordPage>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Leyline_V1_Decoders.Method.QueryRecords.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders.ClientProtocol {
    /// Call the "ListDecoders" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_ListDecodersRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func listDecoders<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_ListDecodersRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_ListDecodersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listDecoders(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_ListDecodersRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_ListDecodersResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubscribeRecords" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
    /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_RecordSubscription` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribeRecords<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_RecordSubscription>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_DecodeRecord>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.subscribeRecords(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_RecordSubscription>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_DecodeRecord>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "QueryRecords" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Records from the store: kept jobs only, newest first.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Leyline_V1_RecordQuery` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func queryRecords<Result>(
        request: GRPCCore.ClientRequest<Leyline_V1_RecordQuery>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_RecordPage>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.queryRecords(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Leyline_V1_RecordQuery>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Leyline_V1_RecordPage>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Leyline_V1_Decoders.ClientProtocol {
    /// Call the "ListDecoders" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func listDecoders<Result>(
        _ message: Leyline_V1_ListDecodersRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_ListDecodersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_ListDecodersRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listDecoders(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubscribeRecords" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Live records. Drop-oldest with a per-job `seq`; a retained window of 256 records per job is
    /// > replayed for `since_seq`, so "StartJob then Subscribe" misses nothing.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func subscribeRecords<Result>(
        _ message: Leyline_V1_RecordSubscription,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Leyline_V1_DecodeRecord>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_RecordSubscription>(
            message: message,
            metadata: metadata
        )
        return try await self.subscribeRecords(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "QueryRecords" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Records from the store: kept jobs only, newest first.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func queryRecords<Result>(
        _ message: Leyline_V1_RecordQuery,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Leyline_V1_RecordPage>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Leyline_V1_RecordQuery>(
            message: message,
            metadata: metadata
        )
        return try await self.queryRecords(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}