// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: leyline/v1/telemetry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// leyline.v1 — telemetry plane
/// Low-rate structured observations: what the radio sees, as opposed to state someone changed.
/// Full protobuf messages (unlike bulk payloads); all carry the sample timebase.
/// Delivery is latest-wins with sequence numbers.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Leyline_V1_TelemetryType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case meter // = 1
  case squelchTransition // = 2
  case detection // = 3
  case captureActivity // = 4
  case subAudible // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .meter
    case 2: self = .squelchTransition
    case 3: self = .detection
    case 4: self = .captureActivity
    case 5: self = .subAudible
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .meter: return 1
    case .squelchTransition: return 2
    case .detection: return 3
    case .captureActivity: return 4
    case .subAudible: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_TelemetryType] = [
    .unspecified,
    .meter,
    .squelchTransition,
    .detection,
    .captureActivity,
    .subAudible,
  ]

}

public nonisolated enum Leyline_V1_SubAudibleKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// looked, found nothing
  case subAudibleNone // = 1
  case subAudibleCtcss // = 2
  case subAudibleDcs // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .subAudibleNone
    case 2: self = .subAudibleCtcss
    case 3: self = .subAudibleDcs
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .subAudibleNone: return 1
    case .subAudibleCtcss: return 2
    case .subAudibleDcs: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Leyline_V1_SubAudibleKind] = [
    .unspecified,
    .subAudibleNone,
    .subAudibleCtcss,
    .subAudibleDcs,
  ]

}

public nonisolated struct Leyline_V1_TelemetrySubscription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scope: Leyline_V1_TelemetrySubscription.OneOf_Scope? = nil

  public var daemon: Bool {
    get {
      if case .daemon(let v)? = scope {return v}
      return false
    }
    set {scope = .daemon(newValue)}
  }

  public var captureID: String {
    get {
      if case .captureID(let v)? = scope {return v}
      return String()
    }
    set {scope = .captureID(newValue)}
  }

  public var channelID: String {
    get {
      if case .channelID(let v)? = scope {return v}
      return String()
    }
    set {scope = .channelID(newValue)}
  }

  /// empty = all
  public var types: [Leyline_V1_TelemetryType] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Scope: Equatable, Sendable {
    case daemon(Bool)
    case captureID(String)
    case channelID(String)

  }

  public init() {}
}

public nonisolated struct Leyline_V1_TelemetryMsg: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var seq: UInt64 {
    get {_storage._seq}
    set {_uniqueStorage()._seq = newValue}
  }

  public var time: Leyline_V1_SampleTime {
    get {_storage._time ?? Leyline_V1_SampleTime()}
    set {_uniqueStorage()._time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {_storage._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {_uniqueStorage()._time = nil}

  public var body: OneOf_Body? {
    get {return _storage._body}
    set {_uniqueStorage()._body = newValue}
  }

  public var meter: Leyline_V1_Meter {
    get {
      if case .meter(let v)? = _storage._body {return v}
      return Leyline_V1_Meter()
    }
    set {_uniqueStorage()._body = .meter(newValue)}
  }

  public var squelch: Leyline_V1_SquelchTransition {
    get {
      if case .squelch(let v)? = _storage._body {return v}
      return Leyline_V1_SquelchTransition()
    }
    set {_uniqueStorage()._body = .squelch(newValue)}
  }

  public var detection: Leyline_V1_Detection {
    get {
      if case .detection(let v)? = _storage._body {return v}
      return Leyline_V1_Detection()
    }
    set {_uniqueStorage()._body = .detection(newValue)}
  }

  public var activity: Leyline_V1_CaptureActivityMsg {
    get {
      if case .activity(let v)? = _storage._body {return v}
      return Leyline_V1_CaptureActivityMsg()
    }
    set {_uniqueStorage()._body = .activity(newValue)}
  }

  public var subAudible: Leyline_V1_SubAudible {
    get {
      if case .subAudible(let v)? = _storage._body {return v}
      return Leyline_V1_SubAudible()
    }
    set {_uniqueStorage()._body = .subAudible(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Body: Equatable, Sendable {
    case meter(Leyline_V1_Meter)
    case squelch(Leyline_V1_SquelchTransition)
    case detection(Leyline_V1_Detection)
    case activity(Leyline_V1_CaptureActivityMsg)
    case subAudible(Leyline_V1_SubAudible)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// A sub-audible tone under an FM transmission: CTCSS/PL today, DCS later.
///
/// Edge-triggered on a change of identity or confidence band, plus a 1 Hz
/// heartbeat while a tone is held (the telemetry plane has no GetState, so a
/// client that subscribes mid-transmission has to be told what is already
/// there). Full state every message.
///
/// The honesty rules this message exists to encode:
///   - tone_hz is measured; standard_tone_hz is classified, and is 0 when two
///     standard tones could both explain the measurement. The EIA ladder is
///     spaced as tightly as 2.3 Hz (67.0/69.3), and snapping to the nearer one
///     names the wrong tone with a straight face.
///   - confidence is a STATED SCORE, not a probability:
///       clamp((tone_snr_db-6)/14) * clamp(1-|tone_hz-standard_tone_hz|/tol)
///                                 * min(hops_agreeing,3)/3
///     Calibrating a real probability needs a corpus of off-air recordings we do
///     not have. The measured fields are always populated, so a client can
///     threshold on those and ignore the score.
///   - Known false positive: 50 Hz mains hum lands on exactly 100.0 Hz, is
///     perfectly stable, and passes every frequency test; 100.0 Hz is also one
///     of the commonest real PL tones. Only deviation_hz separates them.
public nonisolated struct Leyline_V1_SubAudible: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channelID: String = String()

  public var kind: Leyline_V1_SubAudibleKind = .unspecified

  /// measured; NaN when nothing was measured
  public var toneHz: Double = 0

  /// classified; 0 = measured but not classifiable
  public var standardToneHz: Double = 0

  /// octal as decimal (023 -> 23); 0 unless DCS
  public var dcsCode: UInt32 = 0

  public var dcsInverted: Bool = false

  /// peak deviation the tone was sent at
  public var deviationHz: Double = 0

  /// the tone against the rest of the 60-260 Hz band
  public var toneSnrDb: Double = 0

  /// stated score, not a probability; formula above
  public var confidence: Double = 0

  public var firstSeen: Leyline_V1_SampleTime {
    get {_firstSeen ?? Leyline_V1_SampleTime()}
    set {_firstSeen = newValue}
  }
  /// Returns true if `firstSeen` has been explicitly set.
  public var hasFirstSeen: Bool {self._firstSeen != nil}
  /// Clears the value of `firstSeen`. Subsequent reads from it will return its default value.
  public mutating func clearFirstSeen() {self._firstSeen = nil}

  public var hopsAgreeing: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _firstSeen: Leyline_V1_SampleTime? = nil
}

/// Fixed cadence while the channel is active (default 10 Hz, daemon-configured).
public nonisolated struct Leyline_V1_Meter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channelID: String = String()

  /// channel IQ power: what the squelch measures
  public var powerDbfs: Double = 0

  /// NaN if noise floor not yet estimated
  public var snrDb: Double = 0

  public var squelchOpen: Bool = false

  /// What the listener actually hears, measured on the demodulated block rather
  /// than on the channel IQ. A strong carrier with no modulation has a high
  /// power_dbfs and a low audio_dbfs; the two answer different questions.
  /// Both are NaN before the first block, and NaN (never 0) whenever the value
  /// was not measured -- 0 dBFS is a real, very loud level.
  public var audioDbfs: Double = 0

  /// largest sample in the interval; -inf when digitally silent
  public var audioPeakDbfs: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Edge-triggered, exact in sample time — transcript features key on this, not on Meter.
///
/// Fields 3-5 summarise the transmission that just ended and are set on the CLOSE edge only
/// (open == false). On an open edge duration_samples is 0 and both peaks are NaN: a transmission
/// that has not finished has no duration and no final peak. They cost the hot path two compares
/// and let a client keep a log of what happened on a frequency without subscribing to meters.
public nonisolated struct Leyline_V1_SquelchTransition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var channelID: String = String()

  public var `open`: Bool = false

  /// CAPTURE samples the squelch was open (SampleTime's rate,
  public var durationSamples: UInt64 = 0

  /// not the channel's), so a client converts it with the capture
  /// sample rate it already knows
  public var peakSnrDb: Double = 0

  /// loudest block power seen while open; NaN on an open edge
  public var peakAudioDbfs: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The atom of the semantic tier. v0 detector: energy detection over the FFT ladder.
public nonisolated struct Leyline_V1_Detection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var detectionID: String = String()

  public var captureID: String = String()

  public var centerHz: UInt64 = 0

  public var bandwidthHz: UInt32 = 0

  public var snrDb: Double = 0

  public var firstSeen: Leyline_V1_SampleTime {
    get {_firstSeen ?? Leyline_V1_SampleTime()}
    set {_firstSeen = newValue}
  }
  /// Returns true if `firstSeen` has been explicitly set.
  public var hasFirstSeen: Bool {self._firstSeen != nil}
  /// Clears the value of `firstSeen`. Subsequent reads from it will return its default value.
  public mutating func clearFirstSeen() {self._firstSeen = nil}

  public var lastSeen: Leyline_V1_SampleTime {
    get {_lastSeen ?? Leyline_V1_SampleTime()}
    set {_lastSeen = newValue}
  }
  /// Returns true if `lastSeen` has been explicitly set.
  public var hasLastSeen: Bool {self._lastSeen != nil}
  /// Clears the value of `lastSeen`. Subsequent reads from it will return its default value.
  public mutating func clearLastSeen() {self._lastSeen = nil}

  /// Sparse in v0: cheap heuristics only (bandwidth class, carrier presence) or absent.
  /// A real classifier slots in here later without schema change.
  public var modulationGuess: String = String()

  /// 0 when guess is absent
  public var guessConfidence: Double = 0

  /// The evidence, so a client can tell a carrier from a burst instead of the daemon deciding.
  /// looks = spectrum rows in which this cleared the threshold; looks_possible = rows that covered
  /// this frequency at all. A repeater reads 8/8, a packet burst 1/8. Persistence is reported, not
  /// used as a gate: the threshold already spends a whole sweep's false-alarm budget, and demanding
  /// presence in half a dwell would make exactly the intermittent traffic an operator cares about
  /// invisible.
  public var looks: UInt32 = 0

  public var looksPossible: UInt32 = 0

  /// The local noise floor snr_db was measured against, dBFS per bin. Local because the tuner's IF
  /// response tilts the floor several dB across a span -- one number per row cannot describe it.
  public var floorDbfs: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _firstSeen: Leyline_V1_SampleTime? = nil
  fileprivate var _lastSeen: Leyline_V1_SampleTime? = nil
}

public nonisolated struct Leyline_V1_CaptureActivityMsg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var captureID: String = String()

  public var snapshot: Leyline_V1_CaptureActivitySnapshot {
    get {_snapshot ?? Leyline_V1_CaptureActivitySnapshot()}
    set {_snapshot = newValue}
  }
  /// Returns true if `snapshot` has been explicitly set.
  public var hasSnapshot: Bool {self._snapshot != nil}
  /// Clears the value of `snapshot`. Subsequent reads from it will return its default value.
  public mutating func clearSnapshot() {self._snapshot = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _snapshot: Leyline_V1_CaptureActivitySnapshot? = nil
}

public nonisolated struct Leyline_V1_CaptureActivitySnapshot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var lastInteractiveWriteNs: Int64 = 0

  public var liveAudioSinks: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "leyline.v1"

nonisolated extension Leyline_V1_TelemetryType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TELEMETRY_TYPE_UNSPECIFIED\0\u{1}METER\0\u{1}SQUELCH_TRANSITION\0\u{1}DETECTION\0\u{1}CAPTURE_ACTIVITY\0\u{1}SUB_AUDIBLE\0")
}

nonisolated extension Leyline_V1_SubAudibleKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SUB_AUDIBLE_KIND_UNSPECIFIED\0\u{1}SUB_AUDIBLE_NONE\0\u{1}SUB_AUDIBLE_CTCSS\0\u{1}SUB_AUDIBLE_DCS\0")
}

nonisolated extension Leyline_V1_TelemetrySubscription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TelemetrySubscription"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}daemon\0\u{3}capture_id\0\u{3}channel_id\0\u{1}types\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .daemon(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .captureID(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.scope != nil {try decoder.handleConflictingOneOf()}
          self.scope = .channelID(v)
        }
      }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.types) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.scope {
    case .daemon?: try {
      guard case .daemon(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .captureID?: try {
      guard case .captureID(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .channelID?: try {
      guard case .channelID(let v)? = self.scope else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    if !self.types.isEmpty {
      try visitor.visitPackedEnumField(value: self.types, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_TelemetrySubscription, rhs: Leyline_V1_TelemetrySubscription) -> Bool {
    if lhs.scope != rhs.scope {return false}
    if lhs.types != rhs.types {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_TelemetryMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TelemetryMsg"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}seq\0\u{1}time\0\u{1}meter\0\u{1}squelch\0\u{1}detection\0\u{1}activity\0\u{3}sub_audible\0")

  fileprivate class _StorageClass {
    var _seq: UInt64 = 0
    var _time: Leyline_V1_SampleTime? = nil
    var _body: Leyline_V1_TelemetryMsg.OneOf_Body?

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _seq = source._seq
      _time = source._time
      _body = source._body
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt64Field(value: &_storage._seq) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._time) }()
        case 3: try {
          var v: Leyline_V1_Meter?
          var hadOneofValue = false
          if let current = _storage._body {
            hadOneofValue = true
            if case .meter(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._body = .meter(v)
          }
        }()
        case 4: try {
          var v: Leyline_V1_SquelchTransition?
          var hadOneofValue = false
          if let current = _storage._body {
            hadOneofValue = true
            if case .squelch(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._body = .squelch(v)
          }
        }()
        case 5: try {
          var v: Leyline_V1_Detection?
          var hadOneofValue = false
          if let current = _storage._body {
            hadOneofValue = true
            if case .detection(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._body = .detection(v)
          }
        }()
        case 6: try {
          var v: Leyline_V1_CaptureActivityMsg?
          var hadOneofValue = false
          if let current = _storage._body {
            hadOneofValue = true
            if case .activity(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._body = .activity(v)
          }
        }()
        case 7: try {
          var v: Leyline_V1_SubAudible?
          var hadOneofValue = false
          if let current = _storage._body {
            hadOneofValue = true
            if case .subAudible(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._body = .subAudible(v)
          }
        }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._seq != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._seq, fieldNumber: 1)
      }
      try { if let v = _storage._time {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      switch _storage._body {
      case .meter?: try {
        guard case .meter(let v)? = _storage._body else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }()
      case .squelch?: try {
        guard case .squelch(let v)? = _storage._body else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }()
      case .detection?: try {
        guard case .detection(let v)? = _storage._body else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }()
      case .activity?: try {
        guard case .activity(let v)? = _storage._body else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case .subAudible?: try {
        guard case .subAudible(let v)? = _storage._body else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_TelemetryMsg, rhs: Leyline_V1_TelemetryMsg) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._seq != rhs_storage._seq {return false}
        if _storage._time != rhs_storage._time {return false}
        if _storage._body != rhs_storage._body {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_SubAudible: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SubAudible"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_id\0\u{1}kind\0\u{3}tone_hz\0\u{3}standard_tone_hz\0\u{3}dcs_code\0\u{3}dcs_inverted\0\u{3}deviation_hz\0\u{3}tone_snr_db\0\u{1}confidence\0\u{3}first_seen\0\u{3}hops_agreeing\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.channelID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.toneHz) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.standardToneHz) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.dcsCode) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.dcsInverted) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.deviationHz) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.toneSnrDb) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.confidence) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._firstSeen) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.hopsAgreeing) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.channelID.isEmpty {
      try visitor.visitSingularStringField(value: self.channelID, fieldNumber: 1)
    }
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if self.toneHz.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.toneHz, fieldNumber: 3)
    }
    if self.standardToneHz.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.standardToneHz, fieldNumber: 4)
    }
    if self.dcsCode != 0 {
      try visitor.visitSingularUInt32Field(value: self.dcsCode, fieldNumber: 5)
    }
    if self.dcsInverted != false {
      try visitor.visitSingularBoolField(value: self.dcsInverted, fieldNumber: 6)
    }
    if self.deviationHz.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.deviationHz, fieldNumber: 7)
    }
    if self.toneSnrDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.toneSnrDb, fieldNumber: 8)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.confidence, fieldNumber: 9)
    }
    try { if let v = self._firstSeen {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    if self.hopsAgreeing != 0 {
      try visitor.visitSingularUInt32Field(value: self.hopsAgreeing, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_SubAudible, rhs: Leyline_V1_SubAudible) -> Bool {
    if lhs.channelID != rhs.channelID {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.toneHz != rhs.toneHz {return false}
    if lhs.standardToneHz != rhs.standardToneHz {return false}
    if lhs.dcsCode != rhs.dcsCode {return false}
    if lhs.dcsInverted != rhs.dcsInverted {return false}
    if lhs.deviationHz != rhs.deviationHz {return false}
    if lhs.toneSnrDb != rhs.toneSnrDb {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs._firstSeen != rhs._firstSeen {return false}
    if lhs.hopsAgreeing != rhs.hopsAgreeing {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Meter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Meter"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_id\0\u{3}power_dbfs\0\u{3}snr_db\0\u{3}squelch_open\0\u{3}audio_dbfs\0\u{3}audio_peak_dbfs\0\u{c}\u{7}\u{1}\u{c}\u{8}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.channelID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.powerDbfs) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.snrDb) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.squelchOpen) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.audioDbfs) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.audioPeakDbfs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.channelID.isEmpty {
      try visitor.visitSingularStringField(value: self.channelID, fieldNumber: 1)
    }
    if self.powerDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.powerDbfs, fieldNumber: 2)
    }
    if self.snrDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.snrDb, fieldNumber: 3)
    }
    if self.squelchOpen != false {
      try visitor.visitSingularBoolField(value: self.squelchOpen, fieldNumber: 4)
    }
    if self.audioDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.audioDbfs, fieldNumber: 5)
    }
    if self.audioPeakDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.audioPeakDbfs, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Meter, rhs: Leyline_V1_Meter) -> Bool {
    if lhs.channelID != rhs.channelID {return false}
    if lhs.powerDbfs != rhs.powerDbfs {return false}
    if lhs.snrDb != rhs.snrDb {return false}
    if lhs.squelchOpen != rhs.squelchOpen {return false}
    if lhs.audioDbfs != rhs.audioDbfs {return false}
    if lhs.audioPeakDbfs != rhs.audioPeakDbfs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_SquelchTransition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SquelchTransition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}channel_id\0\u{1}open\0\u{3}duration_samples\0\u{3}peak_snr_db\0\u{3}peak_audio_dbfs\0\u{c}\u{6}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.channelID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.`open`) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.durationSamples) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.peakSnrDb) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.peakAudioDbfs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.channelID.isEmpty {
      try visitor.visitSingularStringField(value: self.channelID, fieldNumber: 1)
    }
    if self.`open` != false {
      try visitor.visitSingularBoolField(value: self.`open`, fieldNumber: 2)
    }
    if self.durationSamples != 0 {
      try visitor.visitSingularUInt64Field(value: self.durationSamples, fieldNumber: 3)
    }
    if self.peakSnrDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.peakSnrDb, fieldNumber: 4)
    }
    if self.peakAudioDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.peakAudioDbfs, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_SquelchTransition, rhs: Leyline_V1_SquelchTransition) -> Bool {
    if lhs.channelID != rhs.channelID {return false}
    if lhs.`open` != rhs.`open` {return false}
    if lhs.durationSamples != rhs.durationSamples {return false}
    if lhs.peakSnrDb != rhs.peakSnrDb {return false}
    if lhs.peakAudioDbfs != rhs.peakAudioDbfs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_Detection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Detection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}detection_id\0\u{3}capture_id\0\u{3}center_hz\0\u{3}bandwidth_hz\0\u{3}snr_db\0\u{3}first_seen\0\u{3}last_seen\0\u{3}modulation_guess\0\u{3}guess_confidence\0\u{1}looks\0\u{3}looks_possible\0\u{3}floor_dbfs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.detectionID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.captureID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.centerHz) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.bandwidthHz) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.snrDb) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._firstSeen) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._lastSeen) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.modulationGuess) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.guessConfidence) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.looks) }()
      case 11: try { try decoder.decodeSingularUInt32Field(value: &self.looksPossible) }()
      case 12: try { try decoder.decodeSingularDoubleField(value: &self.floorDbfs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.detectionID.isEmpty {
      try visitor.visitSingularStringField(value: self.detectionID, fieldNumber: 1)
    }
    if !self.captureID.isEmpty {
      try visitor.visitSingularStringField(value: self.captureID, fieldNumber: 2)
    }
    if self.centerHz != 0 {
      try visitor.visitSingularUInt64Field(value: self.centerHz, fieldNumber: 3)
    }
    if self.bandwidthHz != 0 {
      try visitor.visitSingularUInt32Field(value: self.bandwidthHz, fieldNumber: 4)
    }
    if self.snrDb.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.snrDb, fieldNumber: 5)
    }
    try { if let v = self._firstSeen {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._lastSeen {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.modulationGuess.isEmpty {
      try visitor.visitSingularStringField(value: self.modulationGuess, fieldNumber: 8)
    }
    if self.guessConfidence.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.guessConfidence, fieldNumber: 9)
    }
    if self.looks != 0 {
      try visitor.visitSingularUInt32Field(value: self.looks, fieldNumber: 10)
    }
    if self.looksPossible != 0 {
      try visitor.visitSingularUInt32Field(value: self.looksPossible, fieldNumber: 11)
    }
    if self.floorDbfs.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.floorDbfs, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_Detection, rhs: Leyline_V1_Detection) -> Bool {
    if lhs.detectionID != rhs.detectionID {return false}
    if lhs.captureID != rhs.captureID {return false}
    if lhs.centerHz != rhs.centerHz {return false}
    if lhs.bandwidthHz != rhs.bandwidthHz {return false}
    if lhs.snrDb != rhs.snrDb {return false}
    if lhs._firstSeen != rhs._firstSeen {return false}
    if lhs._lastSeen != rhs._lastSeen {return false}
    if lhs.modulationGuess != rhs.modulationGuess {return false}
    if lhs.guessConfidence != rhs.guessConfidence {return false}
    if lhs.looks != rhs.looks {return false}
    if lhs.looksPossible != rhs.looksPossible {return false}
    if lhs.floorDbfs != rhs.floorDbfs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_CaptureActivityMsg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CaptureActivityMsg"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_id\0\u{1}snapshot\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.captureID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._snapshot) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.captureID.isEmpty {
      try visitor.visitSingularStringField(value: self.captureID, fieldNumber: 1)
    }
    try { if let v = self._snapshot {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_CaptureActivityMsg, rhs: Leyline_V1_CaptureActivityMsg) -> Bool {
    if lhs.captureID != rhs.captureID {return false}
    if lhs._snapshot != rhs._snapshot {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Leyline_V1_CaptureActivitySnapshot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CaptureActivitySnapshot"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}last_interactive_write_ns\0\u{3}live_audio_sinks\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.lastInteractiveWriteNs) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.liveAudioSinks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lastInteractiveWriteNs != 0 {
      try visitor.visitSingularInt64Field(value: self.lastInteractiveWriteNs, fieldNumber: 1)
    }
    if self.liveAudioSinks != 0 {
      try visitor.visitSingularUInt32Field(value: self.liveAudioSinks, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Leyline_V1_CaptureActivitySnapshot, rhs: Leyline_V1_CaptureActivitySnapshot) -> Bool {
    if lhs.lastInteractiveWriteNs != rhs.lastInteractiveWriteNs {return false}
    if lhs.liveAudioSinks != rhs.liveAudioSinks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
