#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# The parts of scripts/release.sh that need no Mac: which VERSION may be released, the engine's
# version constant as the release compares it, the drivers.json reader, the source download's
# SHA-256 check and the release's asset list. Then the Makefile's release targets, and
# scripts/cut-release.sh: its version arithmetic and CHANGELOG rewrite, and whole runs in a scratch
# repository with a bare origin, where make, brew, Xcode's tools, security and gh are stubs that
# log what they were asked. The signing, notarization and DMG steps run only on the Mac
# (docs/plans/distribution.md, "Sign, notarize, package", Verification).
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=release.sh
. "$here/release.sh"
set +e

tmp=$(mktemp -d "${TMPDIR:-/tmp}/test-release.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
failures=0
fail() { echo "FAIL: $*" >&2; failures=$((failures + 1)); }

for v in 0.1.0 0.1.1 1.2.3; do
  [ -z "$(release_version_refusal "$v")" ] || fail "$v was refused: $(release_version_refusal "$v")"
done
for v in "" 0.1.0-dev 0.2.0-dev.1 0.1.0+3 "0.1.0 x" 0.1.0/x; do
  [ -n "$(release_version_refusal "$v")" ] || fail "\"$v\" was not refused"
done

# The constant as scripts/gen-version.sh writes it.
cat > "$tmp/Version.swift" <<'SWIFT'
// SPDX-License-Identifier: GPL-3.0-or-later

// Generated by scripts/gen-version.sh from the root VERSION file. Do not edit.

/// The version reported in `DaemonInfo` and by `--version`.
let leylinedVersion = "0.1.2"
SWIFT
[ "$(engine_version "$tmp/Version.swift")" = 0.1.2 ] \
  || fail "engine_version read \"$(engine_version "$tmp/Version.swift")\""

# drivers.json as bundle-app.sh's bundle_drivers writes it, one driver per line.
mkdir -p "$tmp/src" "$tmp/out"
printf 'librtlsdr source\n' > "$tmp/src/rtl.tar.gz"
printf 'hackrf source\n' > "$tmp/src/hackrf.tar.xz"
sha_rtl=$(shasum -a 256 "$tmp/src/rtl.tar.gz" | awk '{print $1}')
sha_hackrf=$(shasum -a 256 "$tmp/src/hackrf.tar.xz" | awk '{print $1}')
cat > "$tmp/out/drivers.json" <<JSON
{
  "drivers": [
    {"library": "librtlsdr.0.dylib", "formula": "librtlsdr", "version": "2.0.2", "source_url": "https://example.com/rtl/v2.0.2.tar.gz", "sha256": "$sha_rtl"},
    {"library": "libhackrf.0.dylib", "formula": "hackrf", "version": "2024.02.1", "source_url": "https://example.com/hackrf/hackrf-2024.02.1.tar.xz", "sha256": "$sha_hackrf"}
  ]
}
JSON
want="librtlsdr-2.0.2-source.tar.gz|https://example.com/rtl/v2.0.2.tar.gz|$sha_rtl
hackrf-2024.02.1-source.tar.xz|https://example.com/hackrf/hackrf-2024.02.1.tar.xz|$sha_hackrf"
got=$(driver_sources "$tmp/out/drivers.json")
[ "$got" = "$want" ] || fail "driver_sources printed:
$got
want:
$want"

printf '{"drivers": [\n    {"library": "x.dylib", "formula": "x", "source_url": "https://example.com/x.zip", "sha256": "00"}\n]}\n' \
  > "$tmp/missing.json"
driver_sources "$tmp/missing.json" >/dev/null 2>&1 && fail "driver_sources accepted a driver without a version"

# curl on PATH is a stub that serves the files above by the URL's last path element.
mkdir -p "$tmp/bin"
cat > "$tmp/bin/curl" <<SH
#!/usr/bin/env bash
out=; url=
while [ \$# -gt 0 ]; do case "\$1" in -o) out=\$2; shift 2 ;; -*) shift ;; *) url=\$1; shift ;; esac; done
case "\$url" in
  */v2.0.2.tar.gz) cp "$tmp/src/rtl.tar.gz" "\$out" ;;
  */hackrf-2024.02.1.tar.xz) cp "$tmp/src/hackrf.tar.xz" "\$out" ;;
  *) exit 22 ;;
esac
SH
chmod +x "$tmp/bin/curl"
PATH="$tmp/bin:$PATH" fetch_driver_sources "$tmp/out/drivers.json" "$tmp/out" >/dev/null \
  || fail "fetch_driver_sources failed against matching tarballs"
[ -f "$tmp/out/librtlsdr-2.0.2-source.tar.gz" ] && [ -f "$tmp/out/hackrf-2024.02.1-source.tar.xz" ] \
  || fail "fetch_driver_sources did not write both tarballs: $(ls "$tmp/out")"

printf 'tampered\n' > "$tmp/src/hackrf.tar.xz"
PATH="$tmp/bin:$PATH" fetch_driver_sources "$tmp/out/drivers.json" "$tmp/out" >/dev/null 2>&1 \
  && fail "fetch_driver_sources accepted a tarball whose SHA-256 differs"

want="$tmp/out/Leyline-0.1.2.dmg
$tmp/out/leysdr-0.1.2-source.tar.gz
$tmp/out/librtlsdr-2.0.2-source.tar.gz
$tmp/out/hackrf-2024.02.1-source.tar.xz
$tmp/out/drivers.json
$tmp/out/appcast.xml"
got=$(release_assets "$tmp/out" 0.1.2)
[ "$got" = "$want" ] || fail "release_assets printed:
$got
want:
$want"

# The Makefile's release targets, as make -n prints their recipes: release cuts a release and
# passes the version's knobs through, release-build, release-publish and release-rehearse call
# scripts/release.sh, and there is no alpha target.
mk() { make --no-print-directory -n -C "$here/.." "$@" 2>&1; }
case "$(mk release NEXT=0.4.2 BUMP=minor YES=1 DRY_RUN=1)" in
  *'NEXT="0.4.2" BUMP="minor" YES="1" DRY_RUN="1" ./scripts/cut-release.sh'*) ;;
  *) fail "make release runs: $(mk release NEXT=0.4.2 BUMP=minor YES=1 DRY_RUN=1)" ;;
esac
case "$(mk release-build)" in *'./scripts/release.sh') ;; *) fail "make release-build runs: $(mk release-build)" ;; esac
case "$(mk release-publish)" in *'./scripts/release.sh publish') ;; *) fail "make release-publish runs: $(mk release-publish)" ;; esac
case "$(mk release-rehearse OUT=/x)" in *'./scripts/release.sh rehearse "/x"') ;; *) fail "make release-rehearse runs: $(mk release-rehearse OUT=/x)" ;; esac
mk alpha >/dev/null && fail "the Makefile still has an alpha target"

# --- scripts/release-appcast.sh and scripts/cut-release.sh

# shellcheck source=release-appcast.sh
. "$here/release-appcast.sh"
# shellcheck source=cut-release.sh
. "$here/cut-release.sh"
set +e

# next_version: X-dev releases as X; a released X.Y.Z is followed by the next patch, or by the
# next minor or major with a bump.
for case in 0.1.0-dev::0.1.0 1.0.0-dev::1.0.0 0.1.0::0.1.1 0.1.9::0.1.10 0.1.0:patch:0.1.1 \
  0.1.3:minor:0.2.0 0.9.3:major:1.0.0 1.2.3:minor:1.3.0 0.10.0::0.10.1; do
  IFS=: read -r from bump want <<<"$case"
  got=$(next_version "$from" "$bump")
  [ "$got" = "$want" ] || fail "next_version $from ${bump:-(no bump)} printed \"$got\", want $want"
done
for case in 0.1.0-rc.1: 0.1.0-beta.1: 0.1: 0.1.0.1: 01.2.3: -dev: : 0.1.0-dev:minor 0.1.0:huge \
  0.1-dev: 0.1.0-rc.1-dev:; do
  IFS=: read -r from bump <<<"$case"
  next_version "$from" "$bump" >/dev/null 2>&1 && fail "next_version accepted \"$from\" ${bump:+with $bump}"
done

for pair in 0.1.1:0.1.0 0.2.0:0.1.9 1.0.0:0.99.99 0.1.10:0.1.9 0.10.0:0.9.0; do
  version_gt "${pair%%:*}" "${pair#*:}" || fail "version_gt says ${pair%%:*} is not greater than ${pair#*:}"
  version_gt "${pair#*:}" "${pair%%:*}" && fail "version_gt says ${pair#*:} is greater than ${pair%%:*}"
done
version_gt 0.1.0 0.1.0 && fail "version_gt says 0.1.0 is greater than itself"

# last_release: the greatest vX.Y.Z tag by number, not by name; other tags are not releases.
git init -q "$tmp/tags"
(cd "$tmp/tags" && git -c user.name=T -c user.email=t@example.com commit -q --allow-empty -m x \
  && for t in v0.1.9 v0.1.10 v0.1.2 v0.2.0-rc.1 v1 shots-2026-10-05; do git tag "$t"; done)
got=$(cd "$tmp/tags" && last_release)
[ "$got" = 0.1.10 ] || fail "last_release printed \"$got\", want 0.1.10"
got=$(cd "$tmp/tags" && git tag -d v0.1.9 v0.1.10 v0.1.2 >/dev/null && last_release)
[ -z "$got" ] || fail "last_release printed \"$got\" with no vX.Y.Z tag"

# The first release drops the sentence saying nothing has been released, and leaves an empty
# Unreleased above the dated section.
cat > "$tmp/CHANGELOG.md" <<'MD'
# Changelog

Nothing has been released yet. This file starts with everything that exists on `main`.

## Unreleased

- A thing.

- Another thing.
MD
[ "$(unreleased_notes "$tmp/CHANGELOG.md")" = "- A thing.

- Another thing." ] || fail "unreleased_notes printed: $(unreleased_notes "$tmp/CHANGELOG.md")"
changelog_cut "$tmp/CHANGELOG.md" 0.1.0 2026-10-05 || fail "changelog_cut failed"
want='# Changelog

## Unreleased

## 0.1.0 (2026-10-05)

- A thing.

- Another thing.'
[ "$(cat "$tmp/CHANGELOG.md")" = "$want" ] || fail "changelog_cut wrote:
$(cat "$tmp/CHANGELOG.md")
want:
$want"
[ -z "$(unreleased_notes "$tmp/CHANGELOG.md")" ] || fail "the new Unreleased section is not empty"
[ "$(notes_for 0.1.0 "$tmp/CHANGELOG.md")" = "- A thing.

- Another thing." ] || fail "notes_for does not read the dated heading: $(notes_for 0.1.0 "$tmp/CHANGELOG.md")"
changelog_has_section 0.1.0 "$tmp/CHANGELOG.md" || fail "changelog_has_section missed the dated heading"
changelog_has_section 0.1 "$tmp/CHANGELOG.md" && fail "changelog_has_section matched a prefix"

# The second release keeps the first's section below its own.
printf '%s\n' '# Changelog' '' '## Unreleased' '' '- New.' '' '## 0.1.0 (2026-10-05)' '' '- Old.' \
  > "$tmp/CHANGELOG.md"
changelog_cut "$tmp/CHANGELOG.md" 0.1.1 2026-10-12 || fail "changelog_cut failed on the second release"
want='# Changelog

## Unreleased

## 0.1.1 (2026-10-12)

- New.

## 0.1.0 (2026-10-05)

- Old.'
[ "$(cat "$tmp/CHANGELOG.md")" = "$want" ] || fail "changelog_cut on the second release wrote:
$(cat "$tmp/CHANGELOG.md")"
[ "$(notes_for 0.1.1 "$tmp/CHANGELOG.md")" = "- New." ] || fail "notes_for 0.1.1 is wrong"
printf '# Changelog\n\n- No heading.\n' > "$tmp/nohead.md"
changelog_cut "$tmp/nohead.md" 0.1.0 2026-10-05 && fail "changelog_cut accepted a changelog without ## Unreleased"
[ "$(cat "$tmp/nohead.md")" = "$(printf '# Changelog\n\n- No heading.')" ] || fail "changelog_cut changed a file it refused"

# Stubs for whole runs. Each scenario's $STUB directory holds switches (files) and the logs.
stubs=$tmp/stubs
mkdir -p "$stubs"
cat > "$stubs/uname" <<'SH'
#!/usr/bin/env bash
case "$1" in -s) echo "${STUB_UNAME:-Darwin}" ;; -m) echo arm64 ;; *) for u in /usr/bin/uname /bin/uname; do [ -x "$u" ] && exec "$u" "$@"; done ;; esac
SH
cat > "$stubs/brew" <<'SH'
#!/usr/bin/env bash
echo "brew $*" >> "$STUB/brew.log"
case "$1" in
  list) grep -qx "$3" "$STUB/brew-installed" ;;
  install) shift; printf '%s\n' "$@" >> "$STUB/brew-installed" ;;
esac
SH
cat > "$stubs/xcode-select" <<'SH'
#!/usr/bin/env bash
echo /Library/Developer/CommandLineTools
SH
cat > "$stubs/swift" <<'SH'
#!/usr/bin/env bash
SH
cp "$stubs/swift" "$stubs/go"
cat > "$stubs/security" <<'SH'
#!/usr/bin/env bash
echo "security $*" >> "$STUB/credentials.log"
if [ -e "$STUB/no-identity" ]; then echo "     0 valid identities found"; exit 0; fi
echo '  1) 0123456789ABCDEF "Developer ID Application: Test Labs (TEAM123)"'
echo "     1 valid identities found"
SH
cat > "$stubs/xcrun" <<'SH'
#!/usr/bin/env bash
echo "xcrun $*" >> "$STUB/credentials.log"
case "$1" in
  --find) echo "/usr/bin/$2" ;;
  notarytool) [ ! -e "$STUB/no-notary" ] ;;
esac
SH
cat > "$stubs/gh" <<'SH'
#!/usr/bin/env bash
echo "gh $*" >> "$STUB/gh.log"
case "$1 $2" in
  "auth status") [ ! -e "$STUB/no-gh" ] ;;
  "repo view") exit 0 ;;
  "release view") [ -e "$STUB/gh-release-$3" ] ;;
  "release create") touch "$STUB/gh-release-$3" ;;
esac
SH
# make: version runs the real generator; release-build lays out dist/<VERSION>/ as
# scripts/release.sh does, or a partial one and a failure when $STUB/fail-release exists, and logs
# what git describe says at that moment; release-publish and release-rehearse only log. Any other
# target, release itself included, is a failure.
cat > "$stubs/make" <<'SH'
#!/usr/bin/env bash
target=; out=
for a in "$@"; do case "$a" in --*) ;; OUT=*) out=${a#OUT=} ;; *) target=$a ;; esac; done
v=$(tr -d '[:space:]' < VERSION)
case "$target" in
  version) echo "make version" >> "$STUB/make.log"; ./scripts/gen-version.sh >/dev/null ;;
  release-build)
    echo "make release-build $v describe=$(git describe --tags --exact-match 2>/dev/null)" >> "$STUB/make.log"
    d=dist/$v
    [ ! -e "$d" ] || { echo "release.sh: $d already exists" >&2; exit 1; }
    mkdir -p "$d"
    touch "$d/Leyline-$v.dmg"
    if [ -e "$STUB/fail-release" ]; then echo "notarization Invalid" >&2; exit 1; fi
    touch "$d/leysdr-$v-source.tar.gz" "$d/libusb-1.0.29-source.tar.bz2" "$d/appcast.xml" "$d/notes.md"
    printf '{\n  "drivers": [\n    {"library": "libusb-1.0.0.dylib", "formula": "libusb", "version": "1.0.29", "source_url": "https://example.com/libusb-1.0.29.tar.bz2", "sha256": "00"}\n  ]\n}\n' > "$d/drivers.json"
    git rev-parse HEAD > "$d/commit"
    ;;
  release-publish) echo "make release-publish $v" >> "$STUB/make.log"; touch "$STUB/gh-release-v$v" ;;
  release-rehearse) echo "make release-rehearse $v" >> "$STUB/make.log"; touch "$out/Leyline-$v.dmg" ;;
  *) echo "make: unexpected target $target" >&2; exit 2 ;;
esac
SH
chmod +x "$stubs"/*

# scenario <name>: a scratch repository at $repo with a bare origin, VERSION 0.1.0-dev, the
# scripts cut-release.sh runs and a first-release CHANGELOG, pushed; $STUB holds its switches and
# logs.
scenario() {
  local s=$tmp/scenario-$1
  mkdir -p "$s/stub"
  STUB=$s/stub
  repo=$s/work
  printf '%s\n' librtlsdr hackrf libusb > "$STUB/brew-installed"
  : > "$STUB/make.log"; : > "$STUB/gh.log"; : > "$STUB/credentials.log"
  git init -q --bare -b main "$s/origin.git"
  git init -q -b main "$repo"
  mkdir -p "$repo/scripts" "$repo/engine/Sources/LeylineDaemon" "$repo/go/internal/cli"
  cp "$here/cut-release.sh" "$here/release.sh" "$here/release-appcast.sh" "$here/gen-version.sh" "$repo/scripts/"
  echo 0.1.0-dev > "$repo/VERSION"
  printf 'package cli\n\nconst defaultVersion = "0.1.0-dev"\n' > "$repo/go/internal/cli/root.go"
  printf '/dist/\n' > "$repo/.gitignore"
  cat > "$repo/CHANGELOG.md" <<'MD'
# Changelog

Nothing has been released yet. This file starts with everything that exists on `main`.

## Unreleased

- The first thing.
MD
  (cd "$repo" && ./scripts/gen-version.sh >/dev/null \
    && git config user.name Tester && git config user.email tester@example.com \
    && git config commit.gpgsign false && git config tag.gpgsign false \
    && git add -A && git commit -q -m "start" && git remote add origin "$s/origin.git" \
    && git push -q origin main)
}

# report <prefix> <lines>: one failure per non-empty line.
report() {
  local line
  while IFS= read -r line; do
    [ -z "$line" ] || fail "$1: $line"
  done <<<"$2"
}

# cutrel [VAR=value…]: scripts/cut-release.sh in $repo with the stubs first on PATH, YES=1 unless
# given; its output in $out, its status returned.
cutrel() {
  out=$(cd "$repo" && env PATH="$stubs:$PATH" STUB="$STUB" TMPDIR="$tmp" MAKE=make YES=1 \
    CODESIGN_IDENTITY="Developer ID Application: Test Labs (TEAM123)" NOTARY_PROFILE=test-notary \
    "$@" ./scripts/cut-release.sh 2>&1 </dev/null)
}

# note <text>: a line under CHANGELOG.md's `## Unreleased` in $repo, committed and pushed.
note() {
  (cd "$repo" && awk -v n="- $1" '{ print } /^## Unreleased$/ { print ""; print n }' CHANGELOG.md > CHANGELOG.new \
    && cat CHANGELOG.new > CHANGELOG.md && rm CHANGELOG.new && git commit -q -am "notes" && git push -q origin main)
}

# snapshot: what a refused or rehearsed run must leave as it was.
snapshot() {
  (cd "$repo" && git rev-parse HEAD && git status --porcelain && git tag && cat VERSION CHANGELOG.md \
    && git ls-remote origin)
}

# refused <want> [VAR=value…]: the run stops, changes nothing, and its last line ends with <want>.
refused() {
  local want=$1 before
  shift
  before=$(snapshot)
  if cutrel "$@"; then
    fail "cut-release ran where it should have stopped with \"…$want\":
$out"
    return
  fi
  case "$(printf '%s\n' "$out" | tail -1)" in
    cut-release:*"$want") ;;
    *) fail "cut-release's last line does not end with \"$want\":
$out" ;;
  esac
  [ "$(snapshot)" = "$before" ] || fail "cut-release changed the repository while refusing (\"$want\")"
}

# rehearsed <version> [VAR=value…]: a rehearsal that names <version> as the next release.
rehearsed() {
  local want=$1
  shift
  cutrel DRY_RUN=1 "$@" || { fail "the rehearsal with $* failed:
$out"; return; }
  case "$out" in *"Next release: $want "*) ;; *) fail "the rehearsal with $* did not name $want:
$out" ;; esac
}

# released <version> <date>: what a finished release of <version> leaves in $repo, one problem
# per line.
released() {
  local v=$1
  (
    cd "$repo" || exit 1
    [ "$(cat VERSION)" = "$v" ] || echo "VERSION is $(cat VERSION)"
    [ "$(git log -1 --format=%s)" = "release: $v" ] || echo "HEAD is \"$(git log -1 --format=%s)\""
    git log -1 --format=%B | grep -q '^Signed-off-by: Tester <tester@example.com>$' || echo "the release commit is not signed off"
    [ "$(git cat-file -t "v$v")" = tag ] || echo "v$v is not an annotated tag"
    [ "$(git rev-parse "v$v^{commit}")" = "$(git rev-parse HEAD)" ] || echo "the tag is not at HEAD"
    [ "$(git show --name-only --format= HEAD | sort | xargs)" \
      = "CHANGELOG.md VERSION engine/Sources/LeylineDaemon/Version.swift go/internal/cli/root.go" ] \
      || echo "the release commit holds: $(git show --name-only --format= HEAD | xargs)"
    grep -q "leylinedVersion = \"$v\"" engine/Sources/LeylineDaemon/Version.swift || echo "Version.swift was not regenerated"
    grep -q "defaultVersion = \"$v\"" go/internal/cli/root.go || echo "root.go was not regenerated"
    grep -q '^Nothing has been released' CHANGELOG.md && echo "the first-release sentence is still there"
    grep -qx "## $v ($(date +%Y-%m-%d))" CHANGELOG.md || echo "CHANGELOG.md has no dated section"
    [ "$(git ls-remote origin refs/heads/main | cut -f1)" = "$(git rev-parse HEAD)" ] || echo "main was not pushed"
    git ls-remote --exit-code origin "refs/tags/v$v" >/dev/null || echo "the tag was not pushed"
  )
}

# A whole run: VERSION 0.1.0-dev releases as 0.1.0; the commit and tag come before the build, the
# build sees the tag, then the push and the publish.
scenario full
cutrel || fail "the full run failed:
$out"
report "full run" "$(released 0.1.0)"
[ "$(cat "$STUB/make.log")" = "make version
make release-build 0.1.0 describe=v0.1.0
make release-publish 0.1.0" ] || fail "the full run called make as:
$(cat "$STUB/make.log")"
case "$out" in *"Two steps are left"*"Acceptance, on a second"*"pins v0.1.0"*) ;; *) fail "the full run did not name what is left:
$out" ;; esac

# release.sh publish uses the pushed tag rather than making one, and makes a full release that
# does not take Latest from the shots-* releases.
(cd "$repo" && env PATH="$stubs:$PATH" STUB="$STUB" ./scripts/release.sh publish >/dev/null 2>&1) \
  || fail "release.sh publish failed after the full run"
create=$(grep 'release create v0.1.0 ' "$STUB/gh.log")
case "$create" in *--verify-tag*) ;; *) fail "release.sh publish did not pass --verify-tag: $create" ;; esac
case "$create" in *--target*) fail "release.sh publish passed --target beside an existing tag: $create" ;; esac
case "$create" in *--prerelease*) fail "release.sh publish made a prerelease: $create" ;; esac
case "$create" in *--latest=false*) ;; *) fail "release.sh publish did not pass --latest=false: $create" ;; esac

# Run again on the finished release, it changes nothing and builds and publishes nothing.
: > "$STUB/make.log"
cutrel || fail "a second run on a finished release failed:
$out"
[ ! -s "$STUB/make.log" ] || fail "a second run on a finished release called make: $(cat "$STUB/make.log")"
[ "$(cd "$repo" && git log --format=%s | grep -c '^release:')" = 1 ] || fail "a second run cut another release"

# After the release VERSION is 0.1.0, and the next is 0.1.1 unless BUMP or NEXT says otherwise.
note "The second thing."
rehearsed 0.1.1
rehearsed 0.1.1 BUMP=patch
rehearsed 0.2.0 BUMP=minor
rehearsed 1.0.0 BUMP=major
rehearsed 0.4.2 NEXT=0.4.2
refused "make release NEXT=<version>" NEXT=0.1.0
refused "make release NEXT=<version>" NEXT=0.0.9
case "$out" in *"0.0.9 is not greater than 0.1.0"*) ;; *) fail "NEXT=0.0.9 was refused for another reason:
$out" ;; esac
refused "make release NEXT=<version>" NEXT=0.2.0-rc.1
refused "make release NEXT=<version>" NEXT=0.2
refused "make release BUMP=minor" BUMP=huge
refused "make release NEXT=0.3.0" NEXT=0.3.0 BUMP=minor
: > "$STUB/make.log"
cutrel || fail "the second release failed:
$out"
report "second release" "$(released 0.1.1)"
[ "$(cat "$STUB/make.log")" = "make version
make release-build 0.1.1 describe=v0.1.1
make release-publish 0.1.1" ] || fail "the second release called make as:
$(cat "$STUB/make.log")"
[ "$(cd "$repo" && grep -c '^## 0\.1\.[01] (' CHANGELOG.md)" = 2 ] || fail "the second release lost the first's section:
$(cat "$repo/CHANGELOG.md")"

# A tag greater than VERSION's next patch, made outside make release, is the last release.
note "The third thing."
(cd "$repo" && git tag -a v0.3.0 -m x)
refused "make release NEXT=<version>"
case "$out" in *"0.1.2 is not greater than 0.3.0"*) ;; *) fail "the run below v0.3.0 was refused for another reason:
$out" ;; esac
rehearsed 0.4.0 NEXT=0.4.0
(cd "$repo" && git tag -d v0.3.0 >/dev/null)

# A build that fails leaves the commit and tag; the next run builds again from them, without a
# second bump.
scenario resume
touch "$STUB/fail-release"
cutrel && fail "the run whose build fails succeeded"
(cd "$repo" && [ "$(git log -1 --format=%s)" = "release: 0.1.0" ] && git rev-parse -q --verify refs/tags/v0.1.0 >/dev/null) \
  || fail "the failed run did not leave the release commit and tag"
(cd "$repo" && git ls-remote --exit-code origin refs/tags/v0.1.0 >/dev/null) && fail "the failed run pushed the tag"
case "$(printf '%s\n' "$out" | tail -1)" in *"make release-build failed"*": make release") ;; *) fail "the failed run's last line is: $(printf '%s\n' "$out" | tail -1)" ;; esac
rm "$STUB/fail-release"
cutrel || fail "the resumed run failed:
$out"
case "$out" in *"carrying on"*"unfinished; building it again"*) ;; *) fail "the resumed run did not say it carried on and rebuilt:
$out" ;; esac
problems=$(
  cd "$repo" || exit 1
  [ "$(cat VERSION)" = 0.1.0 ] || echo "VERSION is $(cat VERSION)"
  [ "$(git log --format=%s | grep -c '^release:')" = 1 ] || echo "there are $(git log --format=%s | grep -c '^release:') release commits"
  [ -f dist/0.1.0/commit ] || echo "dist/0.1.0 was not rebuilt"
  git ls-remote --exit-code origin refs/tags/v0.1.0 >/dev/null || echo "the tag was not pushed"
)
report "resumed run" "$problems"
[ "$(grep -c '^make release-build 0.1.0' "$STUB/make.log")" = 2 ] && grep -q '^make release-publish' "$STUB/make.log" \
  && [ "$(grep -c '^make version' "$STUB/make.log")" = 1 ] \
  || fail "the two runs called make as:
$(cat "$STUB/make.log")"

# A run stopped between the commit and the tag: the next one tags HEAD and goes on.
scenario untagged
(cd "$repo" && echo 0.1.0 > VERSION && ./scripts/gen-version.sh >/dev/null \
  && git commit -q -a -m "release: 0.1.0")
cutrel || fail "the run after an untagged release commit failed:
$out"
[ "$(cd "$repo" && git rev-parse 'v0.1.0^{commit}')" = "$(cd "$repo" && git rev-parse HEAD)" ] \
  || fail "the run after an untagged release commit did not tag HEAD"

# A rehearsal changes nothing, asks for no credentials, and builds through release-rehearse.
scenario dry
before=$(snapshot)
cutrel DRY_RUN=1 || fail "the rehearsal failed:
$out"
[ "$(snapshot)" = "$before" ] || fail "the rehearsal changed the repository"
[ "$(cat "$STUB/make.log")" = "make release-rehearse 0.1.0-dev" ] || fail "the rehearsal called make as: $(cat "$STUB/make.log")"
[ ! -s "$STUB/credentials.log" ] && [ ! -s "$STUB/gh.log" ] \
  || fail "the rehearsal checked credentials: $(cat "$STUB/credentials.log" "$STUB/gh.log")"
case "$out" in *"Next release: 0.1.0 "*"Rehearsal of 0.1.0 done"*"Skipped:"*) ;; *) fail "the rehearsal did not say what it built and skipped:
$out" ;; esac

# A missing driver formula is installed, not refused.
grep -v hackrf "$STUB/brew-installed" > "$STUB/b" && mv "$STUB/b" "$STUB/brew-installed"
cutrel DRY_RUN=1 || fail "the rehearsal without hackrf failed:
$out"
grep -qx 'brew install hackrf' "$STUB/brew.log" || fail "the missing formula was not installed: $(cat "$STUB/brew.log")"

# NEXT names the version; before the first release, X-dev is the version and BUMP has nothing to
# pick.
rehearsed 0.2.0 NEXT=0.2.0
[ "$(snapshot)" = "$before" ] || fail "the rehearsal with NEXT changed the repository"

# Refusals: each stops before changing anything, its last line ending in the command that fixes it.
scenario refusals
refused "make release NEXT=<version>" NEXT=0.2.0-dev
refused "make release NEXT=<version>" BUMP=minor
refused "Run it there with: make release" STUB_UNAME=Linux
(cd "$repo" && git switch -q -c feature)
refused "git switch main"
(cd "$repo" && git switch -q main && echo x >> VERSION)
refused "git stash -u"
(cd "$repo" && git checkout -q -- VERSION && git commit -q --allow-empty -m ahead && git push -q origin main \
  && git reset -q --hard HEAD~1)
refused "git pull --ff-only origin main"
(cd "$repo" && git pull -q --ff-only origin main)
touch "$STUB/no-identity"
refused "security import <file>.p12 -k ~/Library/Keychains/login.keychain-db"
rm "$STUB/no-identity"; touch "$STUB/no-notary"
refused "xcrun notarytool store-credentials test-notary --apple-id <Apple ID> --team-id TEAM123"
rm "$STUB/no-notary"; touch "$STUB/no-gh"
refused "gh auth login"
rm "$STUB/no-gh"
(cd "$repo" && git tag -a v0.1.0 -m x HEAD~0 2>/dev/null)
refused "make release NEXT=<version>"
(cd "$repo" && git tag -d v0.1.0 >/dev/null)
refused "Run again when ready, with YES=1 to skip this question: make release" YES=
(cd "$repo" && printf '# Changelog\n\n## Unreleased\n\n## 0.0.1 (2026-01-01)\n\n- Old.\n' > CHANGELOG.md \
  && git commit -q -am "empty notes" && git push -q origin main)
refused "\$EDITOR CHANGELOG.md"

if [ $failures -gt 0 ]; then
  echo "test-release.sh: $failures failed" >&2
  exit 1
fi
echo "test-release.sh: ok"
