#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# The parts of scripts/release.sh that need no Mac: which VERSION may be released, the engine's
# version constant as the release compares it, the drivers.json reader, the source download's
# SHA-256 check and the release's asset list. The signing, notarization and DMG steps run only on
# the Mac (docs/plans/distribution.md, "Sign, notarize, package", Verification).
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=release.sh
. "$here/release.sh"
set +e

tmp=$(mktemp -d "${TMPDIR:-/tmp}/test-release.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
failures=0
fail() { echo "FAIL: $*" >&2; failures=$((failures + 1)); }

for v in 0.1.0-alpha.1 0.1.0 1.2.3-beta.4; do
  [ -z "$(release_version_refusal "$v")" ] || fail "$v was refused: $(release_version_refusal "$v")"
done
for v in "" 0.1.0-dev 0.2.0-dev.1 0.1.0-alpha.1+3 "0.1.0 alpha" 0.1.0/x; do
  [ -n "$(release_version_refusal "$v")" ] || fail "\"$v\" was not refused"
done

# The constant as scripts/gen-version.sh writes it.
cat > "$tmp/Version.swift" <<'SWIFT'
// SPDX-License-Identifier: GPL-3.0-or-later

// Generated by scripts/gen-version.sh from the root VERSION file. Do not edit.

/// The version reported in `DaemonInfo` and by `--version`.
let leylinedVersion = "0.1.0-alpha.2"
SWIFT
[ "$(engine_version "$tmp/Version.swift")" = 0.1.0-alpha.2 ] \
  || fail "engine_version read \"$(engine_version "$tmp/Version.swift")\""

# drivers.json as bundle-app.sh's bundle_drivers writes it, one driver per line.
mkdir -p "$tmp/src" "$tmp/out"
printf 'librtlsdr source\n' > "$tmp/src/rtl.tar.gz"
printf 'hackrf source\n' > "$tmp/src/hackrf.tar.xz"
sha_rtl=$(shasum -a 256 "$tmp/src/rtl.tar.gz" | awk '{print $1}')
sha_hackrf=$(shasum -a 256 "$tmp/src/hackrf.tar.xz" | awk '{print $1}')
cat > "$tmp/out/drivers.json" <<JSON
{
  "drivers": [
    {"library": "librtlsdr.0.dylib", "formula": "librtlsdr", "version": "2.0.2", "source_url": "https://example.com/rtl/v2.0.2.tar.gz", "sha256": "$sha_rtl"},
    {"library": "libhackrf.0.dylib", "formula": "hackrf", "version": "2024.02.1", "source_url": "https://example.com/hackrf/hackrf-2024.02.1.tar.xz", "sha256": "$sha_hackrf"}
  ]
}
JSON
want="librtlsdr-2.0.2-source.tar.gz|https://example.com/rtl/v2.0.2.tar.gz|$sha_rtl
hackrf-2024.02.1-source.tar.xz|https://example.com/hackrf/hackrf-2024.02.1.tar.xz|$sha_hackrf"
got=$(driver_sources "$tmp/out/drivers.json")
[ "$got" = "$want" ] || fail "driver_sources printed:
$got
want:
$want"

printf '{"drivers": [\n    {"library": "x.dylib", "formula": "x", "source_url": "https://example.com/x.zip", "sha256": "00"}\n]}\n' \
  > "$tmp/missing.json"
driver_sources "$tmp/missing.json" >/dev/null 2>&1 && fail "driver_sources accepted a driver without a version"

# curl on PATH is a stub that serves the files above by the URL's last path element.
mkdir -p "$tmp/bin"
cat > "$tmp/bin/curl" <<SH
#!/usr/bin/env bash
out=; url=
while [ \$# -gt 0 ]; do case "\$1" in -o) out=\$2; shift 2 ;; -*) shift ;; *) url=\$1; shift ;; esac; done
case "\$url" in
  */v2.0.2.tar.gz) cp "$tmp/src/rtl.tar.gz" "\$out" ;;
  */hackrf-2024.02.1.tar.xz) cp "$tmp/src/hackrf.tar.xz" "\$out" ;;
  *) exit 22 ;;
esac
SH
chmod +x "$tmp/bin/curl"
PATH="$tmp/bin:$PATH" fetch_driver_sources "$tmp/out/drivers.json" "$tmp/out" >/dev/null \
  || fail "fetch_driver_sources failed against matching tarballs"
[ -f "$tmp/out/librtlsdr-2.0.2-source.tar.gz" ] && [ -f "$tmp/out/hackrf-2024.02.1-source.tar.xz" ] \
  || fail "fetch_driver_sources did not write both tarballs: $(ls "$tmp/out")"

printf 'tampered\n' > "$tmp/src/hackrf.tar.xz"
PATH="$tmp/bin:$PATH" fetch_driver_sources "$tmp/out/drivers.json" "$tmp/out" >/dev/null 2>&1 \
  && fail "fetch_driver_sources accepted a tarball whose SHA-256 differs"

want="$tmp/out/Leyline-0.1.0-alpha.2.dmg
$tmp/out/leysdr-0.1.0-alpha.2-source.tar.gz
$tmp/out/librtlsdr-2.0.2-source.tar.gz
$tmp/out/hackrf-2024.02.1-source.tar.xz
$tmp/out/drivers.json
$tmp/out/appcast.xml"
got=$(release_assets "$tmp/out" 0.1.0-alpha.2)
[ "$got" = "$want" ] || fail "release_assets printed:
$got
want:
$want"

if [ $failures -gt 0 ]; then
  echo "test-release.sh: $failures failed" >&2
  exit 1
fi
echo "test-release.sh: ok"
